$axure.loadCurrentPage({
  "url":"选择配送农场（宅配）.html",
  "generationDate":new Date(1505384736563.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"59dc160d3827488c82ea0ba4e109d25a",
    "type":"Axure:Page",
    "name":"选择配送农场（宅配）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5536c31a292a41d8bfdd80f7fcc5d1af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":359,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c411e2cc49f4e9ca37a1cdf09b95de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":359,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择配送农场/u0.png"}},
{
          "id":"0f17684f7e1b486b9ff015d56664c569",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":359,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05e332e3c3274a588701f280a73bf3d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":359,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择配送农场/u2.png"}},
{
          "id":"d4d8cb00187f41b5b763d9c25aa65c14",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b793fc32a0e47189a57b4ac66f90d22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u107.png"}},
{
          "id":"6f7a9e484ce64c90a4d802bf6ef88f97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":1,
              "y":40},
            "size":{
              "width":357,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b94fded2a67c484aaf8af4b7453876a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":1,
                  "y":40},
                "size":{
                  "width":357,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择配送农场/u6.png"}},
{
          "id":"31af01d8d6c64aedba0e288046f94f15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":46},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccdd568642f741aab411dd5f20991c2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":46},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d91e0e3f309e4603be6f6a6973909088",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"78d5e0c4e90241dcae2e0dc3c35242a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":75},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb203f2221554adc8614c22bdb54a15a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":75},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00ac39735aa64fdca0686f931ae6f34c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2de4c7086c1644a2b76dad9d21cb0b04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b1e327352924217aa111b871290235f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":146},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"47a884057b9d468a8851576bee56feb5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":190},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"ef69620d28c04a2588e98dcf02ba8b10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":164},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ec0708855a64a01bc48449c42afac06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":164},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1446efc242b04bc3965bbb3d2007d9b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":1,
              "y":196},
            "size":{
              "width":357,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db903ba8aaa54e0d8abec8088c31353c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":1,
                  "y":196},
                "size":{
                  "width":357,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择配送农场/u6.png"}},
{
          "id":"ba72843dc9184b289d44d5f9c6773a03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":9,
              "y":202},
            "size":{
              "width":9,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fe5c0b1bb954970ba2be1fc506e6afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":9,
                  "y":202},
                "size":{
                  "width":9,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a2857d68e9d42aaa9311764f548093c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":257},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"6accfef8f55e45b398a6076c73838461",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":232},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"156378eba8a44e609e3a584410e23628",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":232},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a68ded7d65b4519a5edac7a2eb36f88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":277},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08cd3f0531c648a697c3fe09276af25a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":277},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f88b9050b2a34f57b9589278aa33eda8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":303},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"2098b805636845f6a75694115c2e74ac",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":347},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"87cf7cc4c8f546658f7b291840539fe3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":321},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d90fdcc9942440f9cb6739e294b3c2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":321},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13577854b50b4624afd4da19cc152217",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":352},
            "size":{
              "width":357,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"996ccc41a87d4341a8f053c4cc4bc5d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":352},
                "size":{
                  "width":357,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择配送农场/u6.png"}},
{
          "id":"a4e5721cca0e4cf9b3ae4bb342c49b25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":8,
              "y":358},
            "size":{
              "width":9,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9f5fd9ea83c4845bff1f76b6cce21b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":8,
                  "y":358},
                "size":{
                  "width":9,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7e84be44fe94e17a1c0c610dea00aeb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":413},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"ae939643a7244bc2b2cea26985e8b371",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":387},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8672ec1c509f4b40832956e151463647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":387},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1cda9a8d3fa4d8f82a4ac7b8ffa6004",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":1,
              "y":419},
            "size":{
              "width":357,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"549de5ea7edd4fe18f44fb25eac33839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":1,
                  "y":419},
                "size":{
                  "width":357,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择配送农场/u6.png"}},
{
          "id":"bc683a04da7044b79bded769d56835fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":9,
              "y":425},
            "size":{
              "width":8,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84f7fe68cd68486183afe369a004da31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":9,
                  "y":425},
                "size":{
                  "width":8,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a88310f021a8437681a6b071bc090910",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":480},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"f566d26738c24b38a5fb38868a8a6d30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":454},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aa3c18fd9db4beeabd639afe19a4322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":454},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"566545396af24b48a231296ebb31982c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":1,
              "y":530},
            "size":{
              "width":357,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0ae7d0fa4024592bb19cd4f91341200",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":1,
                  "y":530},
                "size":{
                  "width":357,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择配送农场/u6.png"}},
{
          "id":"b049e587cb5b496491033885346b0b15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":9,
              "y":536},
            "size":{
              "width":8,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0da4cab557b453f8701f00473f15fe6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":9,
                  "y":536},
                "size":{
                  "width":8,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6926bfca56ae42a69e055a91e84aebf2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":591},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"540f314570554461814cffd3e3e5e750",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":565},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72169ade80cc4909ae63e0b03909fbf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":565},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ba23514cdc34d2fb5728fc269a5576a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":335,
              "y":159},
            "size":{
              "width":19,
              "height":144},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b19665d277940f2b9b414e858082fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":335,
                  "y":159},
                "size":{
                  "width":19,
                  "height":144},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择配送农场/u75.png"}},
{
          "id":"5b7c50fef56c404f8c87f04646900baa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":175},
            "size":{
              "width":11,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f173b395c30d47458270049c980291f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":175},
                "size":{
                  "width":11,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91c266d9631b44ff8e81f8488640e4d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":60,
              "y":7},
            "size":{
              "width":288,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"636ef4e75b4f40eaa92149dcbeeb0155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":60,
                  "y":7},
                "size":{
                  "width":288,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u6.png"}},
{
          "id":"86e978164ae944b4bfe3b4c14024ac01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":93,
              "y":12},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84696916c87848f3a5a78a7c1dc35e8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":12},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"445caa48a6d7484a923ffa65b82ad750",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":9.5},
            "size":{
              "width":18,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d21e2e4aa924c9c8d2a64ce4093f421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":9.5},
                "size":{
                  "width":18,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u56.png"}},
{
          "id":"29131c7c3e7a444189cd5d9dc195f850",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":64},
            "size":{
              "width":360,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 宅配详情",
                      "target":{
                        "targetType":"page",
                        "url":"宅配详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"64fb5ad551f64aa7be7aec2269215510",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":108},
            "size":{
              "width":360,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 宅配详情",
                      "target":{
                        "targetType":"page",
                        "url":"宅配详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2777739ee4084ec2a5dea7d898f4fd99",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":153},
            "size":{
              "width":360,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 宅配详情的副本",
                      "target":{
                        "targetType":"page",
                        "url":"宅配详情的副本.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"982654fda3c347dea9caac97a0c3a77b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":221},
            "size":{
              "width":360,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 宅配详情",
                      "target":{
                        "targetType":"page",
                        "url":"宅配详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b4a6313ebdb940b491528ff9304c6634",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":265},
            "size":{
              "width":360,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 宅配详情",
                      "target":{
                        "targetType":"page",
                        "url":"宅配详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"71286e7f4d894ad6979e4666f6a01d39",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":309},
            "size":{
              "width":360,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 宅配详情",
                      "target":{
                        "targetType":"page",
                        "url":"宅配详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"dce7feaac41b426d9966888614330022",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":526},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择配送农场/u10_line.png"}},
{
          "id":"adbad7b2defb47f4a856c9ba80584508",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":500},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0d25fc746ed4671b6fba77641892f32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":500},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0dfa6da868c4c2d860491e49a37048a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":487},
            "size":{
              "width":360,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 宅配详情的副本",
                      "target":{
                        "targetType":"page",
                        "url":"宅配详情的副本.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "5536c31a292a41d8bfdd80f7fcc5d1af":{
      "scriptId":"u0"},
    "4c411e2cc49f4e9ca37a1cdf09b95de9":{
      "scriptId":"u1"},
    "0f17684f7e1b486b9ff015d56664c569":{
      "scriptId":"u2"},
    "05e332e3c3274a588701f280a73bf3d0":{
      "scriptId":"u3"},
    "d4d8cb00187f41b5b763d9c25aa65c14":{
      "scriptId":"u4"},
    "5b793fc32a0e47189a57b4ac66f90d22":{
      "scriptId":"u5"},
    "6f7a9e484ce64c90a4d802bf6ef88f97":{
      "scriptId":"u6"},
    "b94fded2a67c484aaf8af4b7453876a2":{
      "scriptId":"u7"},
    "31af01d8d6c64aedba0e288046f94f15":{
      "scriptId":"u8"},
    "ccdd568642f741aab411dd5f20991c2b":{
      "scriptId":"u9"},
    "d91e0e3f309e4603be6f6a6973909088":{
      "scriptId":"u10"},
    "78d5e0c4e90241dcae2e0dc3c35242a5":{
      "scriptId":"u11"},
    "fb203f2221554adc8614c22bdb54a15a":{
      "scriptId":"u12"},
    "00ac39735aa64fdca0686f931ae6f34c":{
      "scriptId":"u13"},
    "2de4c7086c1644a2b76dad9d21cb0b04":{
      "scriptId":"u14"},
    "1b1e327352924217aa111b871290235f":{
      "scriptId":"u15"},
    "47a884057b9d468a8851576bee56feb5":{
      "scriptId":"u16"},
    "ef69620d28c04a2588e98dcf02ba8b10":{
      "scriptId":"u17"},
    "8ec0708855a64a01bc48449c42afac06":{
      "scriptId":"u18"},
    "1446efc242b04bc3965bbb3d2007d9b2":{
      "scriptId":"u19"},
    "db903ba8aaa54e0d8abec8088c31353c":{
      "scriptId":"u20"},
    "ba72843dc9184b289d44d5f9c6773a03":{
      "scriptId":"u21"},
    "5fe5c0b1bb954970ba2be1fc506e6afd":{
      "scriptId":"u22"},
    "2a2857d68e9d42aaa9311764f548093c":{
      "scriptId":"u23"},
    "6accfef8f55e45b398a6076c73838461":{
      "scriptId":"u24"},
    "156378eba8a44e609e3a584410e23628":{
      "scriptId":"u25"},
    "4a68ded7d65b4519a5edac7a2eb36f88":{
      "scriptId":"u26"},
    "08cd3f0531c648a697c3fe09276af25a":{
      "scriptId":"u27"},
    "f88b9050b2a34f57b9589278aa33eda8":{
      "scriptId":"u28"},
    "2098b805636845f6a75694115c2e74ac":{
      "scriptId":"u29"},
    "87cf7cc4c8f546658f7b291840539fe3":{
      "scriptId":"u30"},
    "5d90fdcc9942440f9cb6739e294b3c2a":{
      "scriptId":"u31"},
    "13577854b50b4624afd4da19cc152217":{
      "scriptId":"u32"},
    "996ccc41a87d4341a8f053c4cc4bc5d1":{
      "scriptId":"u33"},
    "a4e5721cca0e4cf9b3ae4bb342c49b25":{
      "scriptId":"u34"},
    "e9f5fd9ea83c4845bff1f76b6cce21b6":{
      "scriptId":"u35"},
    "f7e84be44fe94e17a1c0c610dea00aeb":{
      "scriptId":"u36"},
    "ae939643a7244bc2b2cea26985e8b371":{
      "scriptId":"u37"},
    "8672ec1c509f4b40832956e151463647":{
      "scriptId":"u38"},
    "b1cda9a8d3fa4d8f82a4ac7b8ffa6004":{
      "scriptId":"u39"},
    "549de5ea7edd4fe18f44fb25eac33839":{
      "scriptId":"u40"},
    "bc683a04da7044b79bded769d56835fb":{
      "scriptId":"u41"},
    "84f7fe68cd68486183afe369a004da31":{
      "scriptId":"u42"},
    "a88310f021a8437681a6b071bc090910":{
      "scriptId":"u43"},
    "f566d26738c24b38a5fb38868a8a6d30":{
      "scriptId":"u44"},
    "4aa3c18fd9db4beeabd639afe19a4322":{
      "scriptId":"u45"},
    "566545396af24b48a231296ebb31982c":{
      "scriptId":"u46"},
    "e0ae7d0fa4024592bb19cd4f91341200":{
      "scriptId":"u47"},
    "b049e587cb5b496491033885346b0b15":{
      "scriptId":"u48"},
    "c0da4cab557b453f8701f00473f15fe6":{
      "scriptId":"u49"},
    "6926bfca56ae42a69e055a91e84aebf2":{
      "scriptId":"u50"},
    "540f314570554461814cffd3e3e5e750":{
      "scriptId":"u51"},
    "72169ade80cc4909ae63e0b03909fbf3":{
      "scriptId":"u52"},
    "0ba23514cdc34d2fb5728fc269a5576a":{
      "scriptId":"u53"},
    "1b19665d277940f2b9b414e858082fa2":{
      "scriptId":"u54"},
    "5b7c50fef56c404f8c87f04646900baa":{
      "scriptId":"u55"},
    "f173b395c30d47458270049c980291f5":{
      "scriptId":"u56"},
    "91c266d9631b44ff8e81f8488640e4d0":{
      "scriptId":"u57"},
    "636ef4e75b4f40eaa92149dcbeeb0155":{
      "scriptId":"u58"},
    "86e978164ae944b4bfe3b4c14024ac01":{
      "scriptId":"u59"},
    "84696916c87848f3a5a78a7c1dc35e8e":{
      "scriptId":"u60"},
    "445caa48a6d7484a923ffa65b82ad750":{
      "scriptId":"u61"},
    "0d21e2e4aa924c9c8d2a64ce4093f421":{
      "scriptId":"u62"},
    "29131c7c3e7a444189cd5d9dc195f850":{
      "scriptId":"u63"},
    "64fb5ad551f64aa7be7aec2269215510":{
      "scriptId":"u64"},
    "2777739ee4084ec2a5dea7d898f4fd99":{
      "scriptId":"u65"},
    "982654fda3c347dea9caac97a0c3a77b":{
      "scriptId":"u66"},
    "b4a6313ebdb940b491528ff9304c6634":{
      "scriptId":"u67"},
    "71286e7f4d894ad6979e4666f6a01d39":{
      "scriptId":"u68"},
    "dce7feaac41b426d9966888614330022":{
      "scriptId":"u69"},
    "adbad7b2defb47f4a856c9ba80584508":{
      "scriptId":"u70"},
    "b0d25fc746ed4671b6fba77641892f32":{
      "scriptId":"u71"},
    "a0dfa6da868c4c2d860491e49a37048a":{
      "scriptId":"u72"}}});