$axure.loadCurrentPage({
  "url":"0_3注册.html",
  "generationDate":new Date(1505906338713.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"0be300c4bd334e20a6bec862049eb11e",
    "type":"Axure:Page",
    "name":"0.3注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f66e17d51fe84a149909231884241b86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f7ea8ab2ec4ccb8516131cc8e36583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_2登录/u0.png"}},
{
          "id":"b84bf0c862e34e8f8c8f2ffb3dfc8d2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":55},
            "size":{
              "width":36,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81d3a40bf852436fb6a0046355959c14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":55},
                "size":{
                  "width":36,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/u111.png"}},
{
          "id":"60fb413c57634c95be5989033edac766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文新魏 Regular', '华文新魏'",
            "fontSize":"28px",
            "location":{
              "x":152,
              "y":63},
            "size":{
              "width":113,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9a956b0f7404978b57460798bb65db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文新魏 Regular', '华文新魏'",
                "fontSize":"28px",
                "location":{
                  "x":152,
                  "y":63},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1038f34adde45edac90a66d06ddd794",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":320,
              "height":360},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab01fcc81ff4010a4dc6f17d0fcfea5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":170},
                "size":{
                  "width":320,
                  "height":360},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_3注册/u6.png"}},
{
          "id":"cf597934cc094078855ce5b019bac3a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":190},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01350a58a97442d6b41144e83a8403c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":190},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7aa23461c0954bd09ecb399e2646010c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":249},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7d934a37bc64d5ba16f3f6e1f0417bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":249},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fe79d48e04a40fe8fa7251e8e9dece6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":214},
            "size":{
              "width":279,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bee50fc055384e4cb7af263166ad3a5e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":273},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"531aef2bc4e648be958ccf2e7446fc07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":40,
              "y":436},
            "size":{
              "width":279,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41f9259124694124af65f7df54069230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":40,
                  "y":436},
                "size":{
                  "width":279,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_2登录/u14.png"}},
{
          "id":"41343d7e78594ef1bd6243a79670099e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":62,
              "y":486},
            "size":{
              "width":199,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15d81e4496704720a0bb55c7a71939f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":62,
                  "y":486},
                "size":{
                  "width":199,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edb9bb7d1aab4df8afddfe48b6d80b1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":285,
              "y":486},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32d820a4f59a4a3d9b72d159443d7045",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":285,
                  "y":486},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ad6cd8b51804533a488b1affa8e7c77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":230,
              "y":273},
            "size":{
              "width":89,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51eff9911997433480492c732b63d9b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":230,
                  "y":273},
                "size":{
                  "width":89,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_3注册/u20.png"}},
{
          "id":"908aec1a5a8d4071a821380f2fff8768",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":310},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d56912be8a6742a1868c9badb2b851d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":310},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b007c9a0f83e46859ce34c532a7be88b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":334.5},
            "size":{
              "width":279,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4bfb78e2c7f5498ab0cbade48e077e0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":369},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9613ef37639246d0a54c2397d24855b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":369},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c520f0b88305421ab3f20fbb27bc9f51",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":393},
            "size":{
              "width":279,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5196b0ad160f46b29789e351e15cc0bf",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":485},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b7bfa68beb44b1fad1edd2cf77b16f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":485},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"31dfd9d2c401408d9597ab94f602d40a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":43},
            "size":{
              "width":233,
              "height":67}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 0.0主页",
                      "target":{
                        "targetType":"page",
                        "url":"0_0主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "f66e17d51fe84a149909231884241b86":{
      "scriptId":"u0"},
    "d5f7ea8ab2ec4ccb8516131cc8e36583":{
      "scriptId":"u1"},
    "b84bf0c862e34e8f8c8f2ffb3dfc8d2d":{
      "scriptId":"u2"},
    "81d3a40bf852436fb6a0046355959c14":{
      "scriptId":"u3"},
    "60fb413c57634c95be5989033edac766":{
      "scriptId":"u4"},
    "e9a956b0f7404978b57460798bb65db5":{
      "scriptId":"u5"},
    "c1038f34adde45edac90a66d06ddd794":{
      "scriptId":"u6"},
    "2ab01fcc81ff4010a4dc6f17d0fcfea5":{
      "scriptId":"u7"},
    "cf597934cc094078855ce5b019bac3a2":{
      "scriptId":"u8"},
    "01350a58a97442d6b41144e83a8403c5":{
      "scriptId":"u9"},
    "7aa23461c0954bd09ecb399e2646010c":{
      "scriptId":"u10"},
    "e7d934a37bc64d5ba16f3f6e1f0417bb":{
      "scriptId":"u11"},
    "3fe79d48e04a40fe8fa7251e8e9dece6":{
      "scriptId":"u12"},
    "bee50fc055384e4cb7af263166ad3a5e":{
      "scriptId":"u13"},
    "531aef2bc4e648be958ccf2e7446fc07":{
      "scriptId":"u14"},
    "41f9259124694124af65f7df54069230":{
      "scriptId":"u15"},
    "41343d7e78594ef1bd6243a79670099e":{
      "scriptId":"u16"},
    "15d81e4496704720a0bb55c7a71939f2":{
      "scriptId":"u17"},
    "edb9bb7d1aab4df8afddfe48b6d80b1d":{
      "scriptId":"u18"},
    "32d820a4f59a4a3d9b72d159443d7045":{
      "scriptId":"u19"},
    "7ad6cd8b51804533a488b1affa8e7c77":{
      "scriptId":"u20"},
    "51eff9911997433480492c732b63d9b1":{
      "scriptId":"u21"},
    "908aec1a5a8d4071a821380f2fff8768":{
      "scriptId":"u22"},
    "d56912be8a6742a1868c9badb2b851d1":{
      "scriptId":"u23"},
    "b007c9a0f83e46859ce34c532a7be88b":{
      "scriptId":"u24"},
    "4bfb78e2c7f5498ab0cbade48e077e0c":{
      "scriptId":"u25"},
    "9613ef37639246d0a54c2397d24855b3":{
      "scriptId":"u26"},
    "c520f0b88305421ab3f20fbb27bc9f51":{
      "scriptId":"u27"},
    "5196b0ad160f46b29789e351e15cc0bf":{
      "scriptId":"u28"},
    "5b7bfa68beb44b1fad1edd2cf77b16f0":{
      "scriptId":"u29"},
    "31dfd9d2c401408d9597ab94f602d40a":{
      "scriptId":"u30"}}});