$axure.loadCurrentPage({
  "url":"2_3_2订单详情（蔬菜宅配）.html",
  "generationDate":new Date(1510229488107.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"e396ec90e5fc4659871ea7cffbf58383",
    "type":"Axure:Page",
    "name":"2.3.2订单详情（蔬菜宅配）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f71ab9f2b5eb4ccfada89c7c945b091e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac626980264340e9a8601c7efa943bc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u0.png"}},
{
          "id":"6514a15f0c164eed895ec10eae992464",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f0ac57c554b4a019ec97b01f5e27b5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"54215657aa204d649cbe67344ec0084d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc1f07e6821b49efaf334485359e8cda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"0537fa734f214518b09113054f8164bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":145,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b98b3e1ea09489a8dac9b6674585df7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":145,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec166e24a8ec4adb87faef19fe727f15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":47},
            "size":{
              "width":360,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b19ccf2a37a40f68c32c9993a5a8adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":47},
                "size":{
                  "width":360,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u8.png"}},
{
          "id":"e7e89fbd006a460d98787ac14fed2027",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":89},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"225375215a554e9f962a608249941d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":89},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e431a95188647639c335275e044258c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":56},
            "size":{
              "width":302,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97e76a4058df4f149847298cbd33cc72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":56},
                "size":{
                  "width":302,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6e2560c446e413e8866361f0f1ec82c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":258},
            "size":{
              "width":360,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9121c41030547c0a35a5dd120900d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":258},
                "size":{
                  "width":360,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u49.png"}},
{
          "id":"12cbe6452eeb42efb2f189e4f60d4128",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":268},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75e5896252e34c37a5137c9bf71a9ac8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":268},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38207f7d856a4eb0bc821f15c49f7bd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":268},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7048fceb127e4428a1e96865a416b5f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":268},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42947167373e4e53a6278c447f1c6509",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":288},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18bb2920ab444b4b91a006325d6c298e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":288},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"718db051a4f0445daec633c15d4e65a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":288},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43aa72c78d65407a9d816c8d13952654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":288},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81a1742bc4a94ff1915e44de10267543",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":368.5},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e60df6ccec8a4e79b7e7e87230e19f52",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"17bb2dc0ba2746829b48dc5e5b79f49d",
                  "label":"",
                  "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"875c65c30fcf4222a28478e4b580d194",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
                  "id":"4bdaf3a37ac64ce390539e49e8b16206",
                  "label":"",
                  "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":12},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f13abec700544bd59d44340361102c2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":12},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c7c9d4acc2c34ffd8e541ab5deaf5244",
                  "label":"",
                  "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":280,
                      "y":5},
                    "size":{
                      "width":67,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84d6dc9faf694e5f9c3eadf10dc77404",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":280,
                          "y":5},
                        "size":{
                          "width":67,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/1_9订单详情（农旅卡）/u34.png"}},
{
                  "id":"10b030cb4eb646c18366e6dcc6d1de51",
                  "label":"",
                  "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 2.5意见反馈",
                              "target":{
                                "targetType":"page",
                                "url":"2_5意见反馈.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]},
{
          "id":"ae5e0e1696c54723832627145082dd0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":61},
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59b6eab8e508496e998912204d7ecdff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":61},
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u22.png"}},
{
          "id":"2fd652a27d12486da195555779da14ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b4996757b944bfaec45a364b78a2d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"b83fb0e072064b058c1609d19c308866",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":125},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c0fcdefc8774df28e6a01896fc1d948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":125},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u25.png"}},
{
          "id":"2dad89276cf047f5950e59c421ff6886",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":132},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5dd5d71e1cf4a42b0b351e2d463ac70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":132},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d84f1ca714f45edb8385b9abc77911c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":79,
              "y":132},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8803394313745ac8db0816d27588f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":132},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90810df82a854d36a0edc6ccae12ec0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":306},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c774beb09a44de1b3eee9a60ff5bac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":306},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5dead737bcf94d9da2c53566eff2fdd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":304},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46aaae04cc7c49198f7944b5f720a41e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":304},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97c64bfacee24a8297dc8a51bf133a5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":11},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d45bb8132f484ddfa846af15f4f8db70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":11},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_3订单详情（权益农旅）/u34.png"}},
{
          "id":"b851d16fb041435fbd7c1d094f28f8c2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":0},
            "size":{
              "width":45,
              "height":41}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.0个人中心主页",
                      "target":{
                        "targetType":"page",
                        "url":"2_0个人中心主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eb9272332fb44fa483cb4276c8364edd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.3.1.1物流跟踪",
                      "target":{
                        "targetType":"page",
                        "url":"2_3_1_1物流跟踪.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"541d91a93ae448f88394e2068e2c34c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":360,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1dbc28cf9ff4c10b0e8e116088af650",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":360,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_3支付成功（农旅卡购卡）/u14.png"}},
{
          "id":"1105721ff7c44bd18957f33ad212cda6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":67,
              "y":178},
            "size":{
              "width":279,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beff460ff52c42abb80088a3d1718258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":67,
                  "y":178},
                "size":{
                  "width":279,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c5008eb01394fa5a6e52c6b47059039",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":211},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e172b448c8f14c3bb7c726bf5094764e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":211},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d7d34e6a58b483b897433ba613408d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":180},
            "size":{
              "width":48,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8108fc6bae084c40aa4975bbda2d05dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":180},
                "size":{
                  "width":48,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u141.jpg"}},
{
          "id":"224dcc48fdd148d3befbac3d8466d461",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":329,
              "y":216},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4de9ac5b1e1a4008963d57c4723c1c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":329,
                  "y":216},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f71ab9f2b5eb4ccfada89c7c945b091e":{
      "scriptId":"u0"},
    "ac626980264340e9a8601c7efa943bc9":{
      "scriptId":"u1"},
    "6514a15f0c164eed895ec10eae992464":{
      "scriptId":"u2"},
    "6f0ac57c554b4a019ec97b01f5e27b5e":{
      "scriptId":"u3"},
    "54215657aa204d649cbe67344ec0084d":{
      "scriptId":"u4"},
    "cc1f07e6821b49efaf334485359e8cda":{
      "scriptId":"u5"},
    "0537fa734f214518b09113054f8164bd":{
      "scriptId":"u6"},
    "4b98b3e1ea09489a8dac9b6674585df7":{
      "scriptId":"u7"},
    "ec166e24a8ec4adb87faef19fe727f15":{
      "scriptId":"u8"},
    "9b19ccf2a37a40f68c32c9993a5a8adf":{
      "scriptId":"u9"},
    "e7e89fbd006a460d98787ac14fed2027":{
      "scriptId":"u10"},
    "225375215a554e9f962a608249941d8d":{
      "scriptId":"u11"},
    "7e431a95188647639c335275e044258c":{
      "scriptId":"u12"},
    "97e76a4058df4f149847298cbd33cc72":{
      "scriptId":"u13"},
    "d6e2560c446e413e8866361f0f1ec82c":{
      "scriptId":"u14"},
    "b9121c41030547c0a35a5dd120900d12":{
      "scriptId":"u15"},
    "12cbe6452eeb42efb2f189e4f60d4128":{
      "scriptId":"u16"},
    "75e5896252e34c37a5137c9bf71a9ac8":{
      "scriptId":"u17"},
    "38207f7d856a4eb0bc821f15c49f7bd5":{
      "scriptId":"u18"},
    "7048fceb127e4428a1e96865a416b5f1":{
      "scriptId":"u19"},
    "42947167373e4e53a6278c447f1c6509":{
      "scriptId":"u20"},
    "18bb2920ab444b4b91a006325d6c298e":{
      "scriptId":"u21"},
    "718db051a4f0445daec633c15d4e65a4":{
      "scriptId":"u22"},
    "43aa72c78d65407a9d816c8d13952654":{
      "scriptId":"u23"},
    "81a1742bc4a94ff1915e44de10267543":{
      "scriptId":"u24"},
    "17bb2dc0ba2746829b48dc5e5b79f49d":{
      "scriptId":"u25"},
    "875c65c30fcf4222a28478e4b580d194":{
      "scriptId":"u26"},
    "4bdaf3a37ac64ce390539e49e8b16206":{
      "scriptId":"u27"},
    "f13abec700544bd59d44340361102c2a":{
      "scriptId":"u28"},
    "c7c9d4acc2c34ffd8e541ab5deaf5244":{
      "scriptId":"u29"},
    "84d6dc9faf694e5f9c3eadf10dc77404":{
      "scriptId":"u30"},
    "10b030cb4eb646c18366e6dcc6d1de51":{
      "scriptId":"u31"},
    "ae5e0e1696c54723832627145082dd0f":{
      "scriptId":"u32"},
    "59b6eab8e508496e998912204d7ecdff":{
      "scriptId":"u33"},
    "2fd652a27d12486da195555779da14ef":{
      "scriptId":"u34"},
    "99b4996757b944bfaec45a364b78a2d7":{
      "scriptId":"u35"},
    "b83fb0e072064b058c1609d19c308866":{
      "scriptId":"u36"},
    "7c0fcdefc8774df28e6a01896fc1d948":{
      "scriptId":"u37"},
    "2dad89276cf047f5950e59c421ff6886":{
      "scriptId":"u38"},
    "d5dd5d71e1cf4a42b0b351e2d463ac70":{
      "scriptId":"u39"},
    "0d84f1ca714f45edb8385b9abc77911c":{
      "scriptId":"u40"},
    "d8803394313745ac8db0816d27588f4c":{
      "scriptId":"u41"},
    "90810df82a854d36a0edc6ccae12ec0d":{
      "scriptId":"u42"},
    "1c774beb09a44de1b3eee9a60ff5bac6":{
      "scriptId":"u43"},
    "5dead737bcf94d9da2c53566eff2fdd5":{
      "scriptId":"u44"},
    "46aaae04cc7c49198f7944b5f720a41e":{
      "scriptId":"u45"},
    "97c64bfacee24a8297dc8a51bf133a5e":{
      "scriptId":"u46"},
    "d45bb8132f484ddfa846af15f4f8db70":{
      "scriptId":"u47"},
    "b851d16fb041435fbd7c1d094f28f8c2":{
      "scriptId":"u48"},
    "eb9272332fb44fa483cb4276c8364edd":{
      "scriptId":"u49"},
    "541d91a93ae448f88394e2068e2c34c0":{
      "scriptId":"u50"},
    "a1dbc28cf9ff4c10b0e8e116088af650":{
      "scriptId":"u51"},
    "1105721ff7c44bd18957f33ad212cda6":{
      "scriptId":"u52"},
    "beff460ff52c42abb80088a3d1718258":{
      "scriptId":"u53"},
    "7c5008eb01394fa5a6e52c6b47059039":{
      "scriptId":"u54"},
    "e172b448c8f14c3bb7c726bf5094764e":{
      "scriptId":"u55"},
    "4d7d34e6a58b483b897433ba613408d2":{
      "scriptId":"u56"},
    "8108fc6bae084c40aa4975bbda2d05dc":{
      "scriptId":"u57"},
    "224dcc48fdd148d3befbac3d8466d461":{
      "scriptId":"u58"},
    "4de9ac5b1e1a4008963d57c4723c1c9b":{
      "scriptId":"u59"}}});