$axure.loadCurrentPage({
  "url":"2_2_3_4修改游客信息.html",
  "generationDate":new Date(1510229478284.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"8cf0805253114145878e510acbc95934",
    "type":"Axure:Page",
    "name":"2.2.3.4修改游客信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"01b87cd1586d42939b6f524fb95f09b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95754633dee44bd794d579c338952605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u0.png"}},
{
          "id":"7f3d980c3704499b919b9e8461d3c26d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb31e44dbbe48faaa76add80a897dd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"9dd3a4d7023b4b5e970ecc4abb7feb96",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":126,
              "y":10},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f0307ac996141e7b48addafe0825503",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":126,
                  "y":10},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49bae8225ab340ffac63c73f7e0640df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":360,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f379d613c484674b844dcfd348319e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":360,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u22.png"}},
{
          "id":"8a895658259a438f8064a64f746cfc07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":111},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79a3da74be9c4ed9aa2750d5d98f32fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":111},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a50bcb62f63247ccaf182253c473f127",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":111},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c43129307f7f44bb8258a662d7259138",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":111},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b7adb09e590442ab69f51f8f0f410c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":137},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff06db0e7216402c814ce2fef7d24825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":137},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b0e33edb64245fa9275c35b91c85cb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":159},
            "size":{
              "width":360,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0cd3b87024d436c85c9e4bf85cd9658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":159},
                "size":{
                  "width":360,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u22.png"}},
{
          "id":"8c301a5b79054c8dac6d7218fa71a643",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":170},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca810b66b0604c77a4cdf538e9eae0f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":170},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db9da1cf972b443882894a8ae84f37ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":170},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f36a41d5f62b4592b4a1c6f896e14146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":170},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ad89257babf4ac3b1e274eb2d6c2b73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":196},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23bbad1760b548a8926b052a32c537c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":196},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80ed25490fe54bb0b6b69556e69ff1dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":218},
            "size":{
              "width":360,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cc434a46ef44763a7da29edaf44e8ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":218},
                "size":{
                  "width":360,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u22.png"}},
{
          "id":"ed09bc9a5c844a1bab1050a8852e1775",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":229},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cf6b57dd38d44d6be3e5200ae377006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":229},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebe9054bfd46493c85490fa9a944b473",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":229},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b75913ac6bb436a971fb552c8161f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":229},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6846d3dc446a414e9d4dddb9fc8fe531",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":255},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c52fb23659344411984bd3fca626d54b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":255},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64151a2a17b5476788685eb074f92046",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":277},
            "size":{
              "width":360,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a6fc6b7c41944ce8129413525715eb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":277},
                "size":{
                  "width":360,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u22.png"}},
{
          "id":"6cf58bae6c544e48896dbcab9419c0b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":288},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f1e668919a48828a1f107d021b975d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":288},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e51326246a64979a04e3336784a3622",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":288},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ac8ed52b8cb44a6bad8f5500c031fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":288},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1b37d90ba604d0a9cc8ea71395bcc0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":314},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ae90dc48c654a1cbf6cb8212735dc01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":314},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcff99c9118e4e82b49ab88beea37b58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":318,
              "y":10},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc43a5fe64ec408eb4f8746c84ffe1f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":10},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9b426fdbde14f2784410099adb2373e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":60,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.2.3.1确认订单（农旅）",
                      "target":{
                        "targetType":"page",
                        "url":"2_2_3_1确认订单（农旅）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"59be16c07ada4c3c8b6b979c25eb9743",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":121},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c43357b0ecda485daf36224f8b8bf7e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":121},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bf5bc7e59a824097a728608da05533bf",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":181},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3154e0769c7242b091212d3731ee1b1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":181},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b52fa3f36e6245b8b0822021149825ff",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ec3d813c544965ac4ce823b6c6e8af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a9adb9df8e0847a48f0c8dfdfeb28841",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":299},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37c639e860744b808f6aad74462bc756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":299},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"97f2236e356a43f697b5f7f85d326d34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b4ae9c69ed541fd98cf343eff4e5a63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"ecd04649331b42b4a256f461c76b1664",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":321,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43bcceff88a74fab80a6b34dd3388998",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":321,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.2.3.5 游客信息新增/编辑",
                      "target":{
                        "targetType":"page",
                        "url":"2_2_3_5_游客信息新增_编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_3选择地址/u51.png"}},
{
          "id":"b99f807ac7ef4cd6bcd19b334a365914",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":318,
              "y":139},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce466a819c947e5a1158b1a6e1efa91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":139},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.2.3.5 游客信息新增/编辑",
                      "target":{
                        "targetType":"page",
                        "url":"2_2_3_5_游客信息新增_编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"240953463a13471abd5b028467a3ceff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":318,
              "y":194},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3d607f739ae4a3489f15f1665d8a2d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":194},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.2.3.5 游客信息新增/编辑",
                      "target":{
                        "targetType":"page",
                        "url":"2_2_3_5_游客信息新增_编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4390dd526c4844269df584d5a44df4dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":318,
              "y":253},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0017c477793343ddb85884c3105b8f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":253},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.2.3.5 游客信息新增/编辑",
                      "target":{
                        "targetType":"page",
                        "url":"2_2_3_5_游客信息新增_编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e966d87f59e4e93a1b2e998f00cc4eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":318,
              "y":310},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e0b0c5469ff4ea095f0f1fff4a882ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":310},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.2.3.5 游客信息新增/编辑",
                      "target":{
                        "targetType":"page",
                        "url":"2_2_3_5_游客信息新增_编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12ab2ef2398b4a9d9f9c5a6b42094569",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":289,
              "y":111},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d96c20465a8f49adab1d691a5bc12fb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":289,
                  "y":111},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "01b87cd1586d42939b6f524fb95f09b9":{
      "scriptId":"u0"},
    "95754633dee44bd794d579c338952605":{
      "scriptId":"u1"},
    "7f3d980c3704499b919b9e8461d3c26d":{
      "scriptId":"u2"},
    "feb31e44dbbe48faaa76add80a897dd6":{
      "scriptId":"u3"},
    "9dd3a4d7023b4b5e970ecc4abb7feb96":{
      "scriptId":"u4"},
    "5f0307ac996141e7b48addafe0825503":{
      "scriptId":"u5"},
    "49bae8225ab340ffac63c73f7e0640df":{
      "scriptId":"u6"},
    "3f379d613c484674b844dcfd348319e5":{
      "scriptId":"u7"},
    "8a895658259a438f8064a64f746cfc07":{
      "scriptId":"u8"},
    "79a3da74be9c4ed9aa2750d5d98f32fc":{
      "scriptId":"u9"},
    "a50bcb62f63247ccaf182253c473f127":{
      "scriptId":"u10"},
    "c43129307f7f44bb8258a662d7259138":{
      "scriptId":"u11"},
    "6b7adb09e590442ab69f51f8f0f410c2":{
      "scriptId":"u12"},
    "ff06db0e7216402c814ce2fef7d24825":{
      "scriptId":"u13"},
    "1b0e33edb64245fa9275c35b91c85cb1":{
      "scriptId":"u14"},
    "c0cd3b87024d436c85c9e4bf85cd9658":{
      "scriptId":"u15"},
    "8c301a5b79054c8dac6d7218fa71a643":{
      "scriptId":"u16"},
    "ca810b66b0604c77a4cdf538e9eae0f0":{
      "scriptId":"u17"},
    "db9da1cf972b443882894a8ae84f37ce":{
      "scriptId":"u18"},
    "f36a41d5f62b4592b4a1c6f896e14146":{
      "scriptId":"u19"},
    "2ad89257babf4ac3b1e274eb2d6c2b73":{
      "scriptId":"u20"},
    "23bbad1760b548a8926b052a32c537c5":{
      "scriptId":"u21"},
    "80ed25490fe54bb0b6b69556e69ff1dd":{
      "scriptId":"u22"},
    "5cc434a46ef44763a7da29edaf44e8ad":{
      "scriptId":"u23"},
    "ed09bc9a5c844a1bab1050a8852e1775":{
      "scriptId":"u24"},
    "2cf6b57dd38d44d6be3e5200ae377006":{
      "scriptId":"u25"},
    "ebe9054bfd46493c85490fa9a944b473":{
      "scriptId":"u26"},
    "0b75913ac6bb436a971fb552c8161f00":{
      "scriptId":"u27"},
    "6846d3dc446a414e9d4dddb9fc8fe531":{
      "scriptId":"u28"},
    "c52fb23659344411984bd3fca626d54b":{
      "scriptId":"u29"},
    "64151a2a17b5476788685eb074f92046":{
      "scriptId":"u30"},
    "1a6fc6b7c41944ce8129413525715eb2":{
      "scriptId":"u31"},
    "6cf58bae6c544e48896dbcab9419c0b3":{
      "scriptId":"u32"},
    "65f1e668919a48828a1f107d021b975d":{
      "scriptId":"u33"},
    "2e51326246a64979a04e3336784a3622":{
      "scriptId":"u34"},
    "5ac8ed52b8cb44a6bad8f5500c031fba":{
      "scriptId":"u35"},
    "e1b37d90ba604d0a9cc8ea71395bcc0c":{
      "scriptId":"u36"},
    "7ae90dc48c654a1cbf6cb8212735dc01":{
      "scriptId":"u37"},
    "fcff99c9118e4e82b49ab88beea37b58":{
      "scriptId":"u38"},
    "bc43a5fe64ec408eb4f8746c84ffe1f4":{
      "scriptId":"u39"},
    "a9b426fdbde14f2784410099adb2373e":{
      "scriptId":"u40"},
    "59be16c07ada4c3c8b6b979c25eb9743":{
      "scriptId":"u41"},
    "c43357b0ecda485daf36224f8b8bf7e7":{
      "scriptId":"u42"},
    "bf5bc7e59a824097a728608da05533bf":{
      "scriptId":"u43"},
    "3154e0769c7242b091212d3731ee1b1e":{
      "scriptId":"u44"},
    "b52fa3f36e6245b8b0822021149825ff":{
      "scriptId":"u45"},
    "e9ec3d813c544965ac4ce823b6c6e8af":{
      "scriptId":"u46"},
    "a9adb9df8e0847a48f0c8dfdfeb28841":{
      "scriptId":"u47"},
    "37c639e860744b808f6aad74462bc756":{
      "scriptId":"u48"},
    "97f2236e356a43f697b5f7f85d326d34":{
      "scriptId":"u49"},
    "6b4ae9c69ed541fd98cf343eff4e5a63":{
      "scriptId":"u50"},
    "ecd04649331b42b4a256f461c76b1664":{
      "scriptId":"u51"},
    "43bcceff88a74fab80a6b34dd3388998":{
      "scriptId":"u52"},
    "b99f807ac7ef4cd6bcd19b334a365914":{
      "scriptId":"u53"},
    "6ce466a819c947e5a1158b1a6e1efa91":{
      "scriptId":"u54"},
    "240953463a13471abd5b028467a3ceff":{
      "scriptId":"u55"},
    "f3d607f739ae4a3489f15f1665d8a2d2":{
      "scriptId":"u56"},
    "4390dd526c4844269df584d5a44df4dd":{
      "scriptId":"u57"},
    "0017c477793343ddb85884c3105b8f21":{
      "scriptId":"u58"},
    "0e966d87f59e4e93a1b2e998f00cc4eb":{
      "scriptId":"u59"},
    "9e0b0c5469ff4ea095f0f1fff4a882ad":{
      "scriptId":"u60"},
    "12ab2ef2398b4a9d9f9c5a6b42094569":{
      "scriptId":"u61"},
    "d96c20465a8f49adab1d691a5bc12fb2":{
      "scriptId":"u62"}}});