$axure.loadCurrentPage({
  "url":"1_1_1蔬菜箱详情_1.html",
  "generationDate":new Date(1510229484536.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"01a4e23f2d194b3d944284227c427aca",
    "type":"Axure:Page",
    "name":"1.1.1蔬菜箱详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"acf6d648d8be43bdbfc98fac50ae11f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":360,
              "height":225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95aeada5f1f7447b9bd251f5d11445e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":360,
                  "height":225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_1蔬菜箱详情/u0.jpg"}},
{
          "id":"a52cecb9c1da4a48bf067fe59c6c8f1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":259},
            "size":{
              "width":360,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67927adba7684d80a0bd98d565258318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":259},
                "size":{
                  "width":360,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_1蔬菜箱详情/u2.png"}},
{
          "id":"4b3deebf160c4698a59702be5c4b4eee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":696},
            "size":{
              "width":360,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47bde437e1fb4690811046ed080a7198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":696},
                "size":{
                  "width":360,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_1蔬菜箱详情/u4.png"}},
{
          "id":"f822ef37ddb74c2dac9613697eff03b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1140},
            "size":{
              "width":360,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed98ecc28f1947b4ae6ca1772439a156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1140},
                "size":{
                  "width":360,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_1蔬菜箱详情/u6.png"}},
{
          "id":"d6141dfa40ef4139b0017f0edde28e52",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1350},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ddb5b966a1d34ec6b255bf44cb18469e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c94a79388d594169b46ba4a67438360f",
                  "label":"",
                  "parentDynamicPanel":"d6141dfa40ef4139b0017f0edde28e52",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80da90b8c74c4aeeab39b1987312489a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6141dfa40ef4139b0017f0edde28e52",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 返回",
                              "target":{
                                "targetType":"backUrl",
                                "includeVariables":false},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}}]}]},
{
          "id":"695f5c81161848a2b1998bdcd2c9add5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee6498a275c748559a00a882869bfbfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"5660280881834dd591e3530cd97b477d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf94f7863a09475595bb3a1d14db88bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"08de5fd0645a49ea95183955e65457b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":143.5,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a1e3f23f3c6422198fb11d652b867ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":143.5,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"621c81f218ea41309202404849d9f19c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1590},
            "size":{
              "width":360,
              "height":211}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f231a13ce52483fbfa199fa425d9437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1590},
                "size":{
                  "width":360,
                  "height":211}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_1蔬菜箱详情/u17.jpg"}},
{
          "id":"0aebf72a9d1442a9b5431e6b92b2d11d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1801},
            "size":{
              "width":360,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6df66b8f7d14ed5a941904218c20ace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1801},
                "size":{
                  "width":360,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_1蔬菜箱详情/u19.png"}},
{
          "id":"380260131764472b9ef9ff8a03bf0075",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1866},
            "size":{
              "width":360,
              "height":304}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff4c0c860ff64b9eb0b750a7f8c26f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1866},
                "size":{
                  "width":360,
                  "height":304}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_1蔬菜箱详情/u21.jpg"}},
{
          "id":"ce79fc0f8cb44b0d9c5be211cac882e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":2170},
            "size":{
              "width":360,
              "height":1067}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9678200b075a45d7bcef55b1252e8fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":2170},
                "size":{
                  "width":360,
                  "height":1067}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_1蔬菜箱详情/u23.jpg"}},
{
          "id":"df8f965fe8244490aa2744d98c9c1a51",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":2900},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7425d373f00b4a5990f5777eb3d26e9d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8d73d22962bf4e17ba65925e2ac11ca1",
                  "label":"",
                  "parentDynamicPanel":"df8f965fe8244490aa2744d98c9c1a51",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"27123215771b44e78fe965a000ce685c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"df8f965fe8244490aa2744d98c9c1a51",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 返回",
                              "target":{
                                "targetType":"backUrl",
                                "includeVariables":false},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "acf6d648d8be43bdbfc98fac50ae11f5":{
      "scriptId":"u0"},
    "95aeada5f1f7447b9bd251f5d11445e8":{
      "scriptId":"u1"},
    "a52cecb9c1da4a48bf067fe59c6c8f1c":{
      "scriptId":"u2"},
    "67927adba7684d80a0bd98d565258318":{
      "scriptId":"u3"},
    "4b3deebf160c4698a59702be5c4b4eee":{
      "scriptId":"u4"},
    "47bde437e1fb4690811046ed080a7198":{
      "scriptId":"u5"},
    "f822ef37ddb74c2dac9613697eff03b6":{
      "scriptId":"u6"},
    "ed98ecc28f1947b4ae6ca1772439a156":{
      "scriptId":"u7"},
    "d6141dfa40ef4139b0017f0edde28e52":{
      "scriptId":"u8"},
    "c94a79388d594169b46ba4a67438360f":{
      "scriptId":"u9"},
    "80da90b8c74c4aeeab39b1987312489a":{
      "scriptId":"u10"},
    "695f5c81161848a2b1998bdcd2c9add5":{
      "scriptId":"u11"},
    "ee6498a275c748559a00a882869bfbfe":{
      "scriptId":"u12"},
    "5660280881834dd591e3530cd97b477d":{
      "scriptId":"u13"},
    "bf94f7863a09475595bb3a1d14db88bb":{
      "scriptId":"u14"},
    "08de5fd0645a49ea95183955e65457b2":{
      "scriptId":"u15"},
    "4a1e3f23f3c6422198fb11d652b867ac":{
      "scriptId":"u16"},
    "621c81f218ea41309202404849d9f19c":{
      "scriptId":"u17"},
    "5f231a13ce52483fbfa199fa425d9437":{
      "scriptId":"u18"},
    "0aebf72a9d1442a9b5431e6b92b2d11d":{
      "scriptId":"u19"},
    "d6df66b8f7d14ed5a941904218c20ace":{
      "scriptId":"u20"},
    "380260131764472b9ef9ff8a03bf0075":{
      "scriptId":"u21"},
    "ff4c0c860ff64b9eb0b750a7f8c26f18":{
      "scriptId":"u22"},
    "ce79fc0f8cb44b0d9c5be211cac882e2":{
      "scriptId":"u23"},
    "9678200b075a45d7bcef55b1252e8fad":{
      "scriptId":"u24"},
    "df8f965fe8244490aa2744d98c9c1a51":{
      "scriptId":"u25"},
    "8d73d22962bf4e17ba65925e2ac11ca1":{
      "scriptId":"u26"},
    "27123215771b44e78fe965a000ce685c":{
      "scriptId":"u27"}}});