$axure.loadCurrentPage({
  "url":"6_1_3采购订单详情.html",
  "generationDate":new Date(1510229497373.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"02b9295ba402454694e5aa532bba644e",
    "type":"Axure:Page",
    "name":"6.1.3采购订单详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"454e6d72673740f89bbaa23cd3ceabf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a584db4d65b74e1eab810ab009cd5c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u0.png"}},
{
          "id":"95463b67a8194076af9add9814e29a27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40e64226a996467680082067a246e08a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"a26fa1af76ec4e0191d3aa40c37392aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64bf29acff1541659aba307b32fe370a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"c4448487167542c2a369b072d4da7484",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":145,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ce997990864d4c8ae8afa3bd08c7c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":145,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"467075897b654158bb9bb9763f929e2f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":370},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7c558c15aad94c66ac332815f4ece5e0",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"21a6835a2774464385adde8eac715737",
                  "label":"",
                  "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9387b98e395c4d97817ed01a8a372589",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
                  "id":"545f63f1c29645ceb6fa263892416331",
                  "label":"",
                  "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":12},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e3492d49bfd44ca943fe6a2168ae00d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":12},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eacc6a09161e43b9a068c74272d2b584",
                  "label":"",
                  "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":283,
                      "y":5},
                    "size":{
                      "width":67,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c4bc03fb9104c6dad170512fc70b19c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":283,
                          "y":5},
                        "size":{
                          "width":67,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 6.1.4账单",
                              "target":{
                                "targetType":"page",
                                "url":"6_1_4账单.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/1_9订单详情（农旅卡）/u34.png"}},
{
                  "id":"07997d21e3ea48aca251e1332dd73be3",
                  "label":"",
                  "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":206,
                      "y":5},
                    "size":{
                      "width":67,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4d3545db47f04c21b89e7b70da17071f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":206,
                          "y":5},
                        "size":{
                          "width":67,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 6.1现场特惠卖单",
                              "target":{
                                "targetType":"page",
                                "url":"6_1现场特惠卖单_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/1_9订单详情（农旅卡）/u34.png"}}]}]},
{
          "id":"cda2f1b108fc4b978f532ce1a40920e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":7},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6a22dc5440a405c96c123129e78742b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":7},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_9订单详情（农旅卡）/u36.png"}},
{
          "id":"651f1813b6f24bb69b06078960855039",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":0},
            "size":{
              "width":45,
              "height":41}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 0.0主页",
                      "target":{
                        "targetType":"page",
                        "url":"0_0主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"05c791f6e9bf4466ab859d7c0033599e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":360,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcf6ee3a6c3a41548d393eea007c63eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":360,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_1_1采购支付/u16.png"}},
{
          "id":"75bd52743a6e442c91ac5d47a20ec296",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":7,
              "y":143},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"366197a9022f47b586f8853f0f0e7bdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":7,
                  "y":143},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01b5c1b132c7416ea87b33fd05438729",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":185},
            "size":{
              "width":333,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/6_1_1确认订单（现场）/u18_line.png"}},
{
          "id":"97b3e771c4e84014b72ab2f5b1b97193",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":195},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abbc58f4c53647d386a740009c78f11d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":195},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd4dd11b14a54f4b91c4425383dfce69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":221},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdc8f5f8c9924541b33fb9672460381f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":221},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb51a4d82c84446387616966cb6b8aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":30,
              "y":169},
            "size":{
              "width":289,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"968a7552f87f4f3c8ff145d06d7ddb46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":30,
                  "y":169},
                "size":{
                  "width":289,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80aa0a530b784d758eabf002c08e121f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":247},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c79f0070d0b443fb0118ce5986b22e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":247},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91ac2adcc81543e8a2561c1fe4ce0482",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":273},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9c4f8141fda46578c9bf9fe5460f482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":273},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b8ac583f87a4d85bb45b2c810f2ae9e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":295},
            "size":{
              "width":333,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/6_1_1确认订单（现场）/u18_line.png"}},
{
          "id":"06f942d6d4004637a0f6fac5ffcaae60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":306},
            "size":{
              "width":84,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b4ceb6751a42adabe4098ad2b55a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":306},
                "size":{
                  "width":84,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e14d64871044a8b81730c81868c6394",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":360,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582a7b67e93b49ff96f10e79e91fc7c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":360,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_3_2_订单详情（现场管理）/u8.png"}},
{
          "id":"e9a55fc9e88a4faa86cf513fa987aaec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":7,
              "y":51},
            "size":{
              "width":127,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bb88c226b824a92b068b532edf3ef75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":7,
                  "y":51},
                "size":{
                  "width":127,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b54a50cfd78c43329e03e29427c86d7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":200,
              "y":77},
            "size":{
              "width":122,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f627ed2d8ccf429e8c2aa9d4097710fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":200,
                  "y":77},
                "size":{
                  "width":122,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecfdd2883f674f90b87e387f8b12aa26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":7,
              "y":75},
            "size":{
              "width":183,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa0f18a0b24948889e815adc109cac51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":7,
                  "y":75},
                "size":{
                  "width":183,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1aaa9b54c81f4001880e10ce00cfe2a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":200,
              "y":51},
            "size":{
              "width":183,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2258597deb5e4d8284a8142e27c9746d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":200,
                  "y":51},
                "size":{
                  "width":183,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7c7de2158624674af4f60194687e202",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":99},
            "size":{
              "width":155,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62433f95d75748eb89eccf7ddb6682a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":99},
                "size":{
                  "width":155,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed5d06fd4e314c9195c3a5d8ab34d351",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":101},
            "size":{
              "width":61,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12a519ef726c42fc8d3a54967831ac97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":101},
                "size":{
                  "width":61,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "454e6d72673740f89bbaa23cd3ceabf2":{
      "scriptId":"u0"},
    "a584db4d65b74e1eab810ab009cd5c06":{
      "scriptId":"u1"},
    "95463b67a8194076af9add9814e29a27":{
      "scriptId":"u2"},
    "40e64226a996467680082067a246e08a":{
      "scriptId":"u3"},
    "a26fa1af76ec4e0191d3aa40c37392aa":{
      "scriptId":"u4"},
    "64bf29acff1541659aba307b32fe370a":{
      "scriptId":"u5"},
    "c4448487167542c2a369b072d4da7484":{
      "scriptId":"u6"},
    "85ce997990864d4c8ae8afa3bd08c7c5":{
      "scriptId":"u7"},
    "467075897b654158bb9bb9763f929e2f":{
      "scriptId":"u8"},
    "21a6835a2774464385adde8eac715737":{
      "scriptId":"u9"},
    "9387b98e395c4d97817ed01a8a372589":{
      "scriptId":"u10"},
    "545f63f1c29645ceb6fa263892416331":{
      "scriptId":"u11"},
    "7e3492d49bfd44ca943fe6a2168ae00d":{
      "scriptId":"u12"},
    "eacc6a09161e43b9a068c74272d2b584":{
      "scriptId":"u13"},
    "2c4bc03fb9104c6dad170512fc70b19c":{
      "scriptId":"u14"},
    "07997d21e3ea48aca251e1332dd73be3":{
      "scriptId":"u15"},
    "4d3545db47f04c21b89e7b70da17071f":{
      "scriptId":"u16"},
    "cda2f1b108fc4b978f532ce1a40920e3":{
      "scriptId":"u17"},
    "b6a22dc5440a405c96c123129e78742b":{
      "scriptId":"u18"},
    "651f1813b6f24bb69b06078960855039":{
      "scriptId":"u19"},
    "05c791f6e9bf4466ab859d7c0033599e":{
      "scriptId":"u20"},
    "fcf6ee3a6c3a41548d393eea007c63eb":{
      "scriptId":"u21"},
    "75bd52743a6e442c91ac5d47a20ec296":{
      "scriptId":"u22"},
    "366197a9022f47b586f8853f0f0e7bdb":{
      "scriptId":"u23"},
    "01b5c1b132c7416ea87b33fd05438729":{
      "scriptId":"u24"},
    "97b3e771c4e84014b72ab2f5b1b97193":{
      "scriptId":"u25"},
    "abbc58f4c53647d386a740009c78f11d":{
      "scriptId":"u26"},
    "dd4dd11b14a54f4b91c4425383dfce69":{
      "scriptId":"u27"},
    "bdc8f5f8c9924541b33fb9672460381f":{
      "scriptId":"u28"},
    "fb51a4d82c84446387616966cb6b8aa8":{
      "scriptId":"u29"},
    "968a7552f87f4f3c8ff145d06d7ddb46":{
      "scriptId":"u30"},
    "80aa0a530b784d758eabf002c08e121f":{
      "scriptId":"u31"},
    "4c79f0070d0b443fb0118ce5986b22e5":{
      "scriptId":"u32"},
    "91ac2adcc81543e8a2561c1fe4ce0482":{
      "scriptId":"u33"},
    "f9c4f8141fda46578c9bf9fe5460f482":{
      "scriptId":"u34"},
    "7b8ac583f87a4d85bb45b2c810f2ae9e":{
      "scriptId":"u35"},
    "06f942d6d4004637a0f6fac5ffcaae60":{
      "scriptId":"u36"},
    "b9b4ceb6751a42adabe4098ad2b55a4f":{
      "scriptId":"u37"},
    "5e14d64871044a8b81730c81868c6394":{
      "scriptId":"u38"},
    "582a7b67e93b49ff96f10e79e91fc7c9":{
      "scriptId":"u39"},
    "e9a55fc9e88a4faa86cf513fa987aaec":{
      "scriptId":"u40"},
    "2bb88c226b824a92b068b532edf3ef75":{
      "scriptId":"u41"},
    "b54a50cfd78c43329e03e29427c86d7e":{
      "scriptId":"u42"},
    "f627ed2d8ccf429e8c2aa9d4097710fd":{
      "scriptId":"u43"},
    "ecfdd2883f674f90b87e387f8b12aa26":{
      "scriptId":"u44"},
    "aa0f18a0b24948889e815adc109cac51":{
      "scriptId":"u45"},
    "1aaa9b54c81f4001880e10ce00cfe2a6":{
      "scriptId":"u46"},
    "2258597deb5e4d8284a8142e27c9746d":{
      "scriptId":"u47"},
    "f7c7de2158624674af4f60194687e202":{
      "scriptId":"u48"},
    "62433f95d75748eb89eccf7ddb6682a3":{
      "scriptId":"u49"},
    "ed5d06fd4e314c9195c3a5d8ab34d351":{
      "scriptId":"u50"},
    "12a519ef726c42fc8d3a54967831ac97":{
      "scriptId":"u51"}}});