$axure.loadCurrentPage({
  "url":"我的账户.html",
  "generationDate":new Date(1505905957040.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"49bb714d802c4cbb86766838b4040e28",
    "type":"Axure:Page",
    "name":"我的账户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"77b38570dc7c457c915d21c674a632a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d0925697294466897009e86ba0afe1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_2订单支付页/u0.png"}},
{
          "id":"96e7a017c0b04ef4b30fd73b85b9696d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbd3bda176364bedbf1811a053938eef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u3.png"}},
{
          "id":"685ac2e7593e49fb9a50aa3a3fb08009",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2bd015a39d64fbdb3316ebaa757b774",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u5.png"}},
{
          "id":"f46f807554dc495caaec2163a9592a91",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":145,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae88dc107a9f4b5fb7b4398125a3384b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":145,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"189e3275d5054a588a5c0eb4f912220c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":38},
            "size":{
              "width":360,
              "height":122},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d9a01572d71476889f794621f8627a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":38},
                "size":{
                  "width":360,
                  "height":122},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u8.png"}},
{
          "id":"0042b68e8b114209b79fab8a8f45bd17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":155.5,
              "y":57},
            "size":{
              "width":49,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aec5d838c314c379ec291066185cdda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":155.5,
                  "y":57},
                "size":{
                  "width":49,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06e19dae4b164a7594e3e0a85009c91a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":124,
              "y":110},
            "size":{
              "width":115,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c0bf9fbea74b379b9c211e59a339ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":110},
                "size":{
                  "width":115,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u12.png"}},
{
          "id":"eb881606d6d3434282646ccfabb21779",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":159},
            "size":{
              "width":360,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2ef29919e08454d98595249e7544f96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":159},
                "size":{
                  "width":360,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u14.png"}},
{
          "id":"dd0a5d114dbb46098e1e432ccb0cdc3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":169.5},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96427684db054111ac5e5b9ba7f3def2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":169.5},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u43.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "77b38570dc7c457c915d21c674a632a6":{
      "scriptId":"u0"},
    "2d0925697294466897009e86ba0afe1a":{
      "scriptId":"u1"},
    "96e7a017c0b04ef4b30fd73b85b9696d":{
      "scriptId":"u2"},
    "cbd3bda176364bedbf1811a053938eef":{
      "scriptId":"u3"},
    "685ac2e7593e49fb9a50aa3a3fb08009":{
      "scriptId":"u4"},
    "c2bd015a39d64fbdb3316ebaa757b774":{
      "scriptId":"u5"},
    "f46f807554dc495caaec2163a9592a91":{
      "scriptId":"u6"},
    "ae88dc107a9f4b5fb7b4398125a3384b":{
      "scriptId":"u7"},
    "189e3275d5054a588a5c0eb4f912220c":{
      "scriptId":"u8"},
    "7d9a01572d71476889f794621f8627a5":{
      "scriptId":"u9"},
    "0042b68e8b114209b79fab8a8f45bd17":{
      "scriptId":"u10"},
    "6aec5d838c314c379ec291066185cdda":{
      "scriptId":"u11"},
    "06e19dae4b164a7594e3e0a85009c91a":{
      "scriptId":"u12"},
    "e0c0bf9fbea74b379b9c211e59a339ae":{
      "scriptId":"u13"},
    "eb881606d6d3434282646ccfabb21779":{
      "scriptId":"u14"},
    "a2ef29919e08454d98595249e7544f96":{
      "scriptId":"u15"},
    "dd0a5d114dbb46098e1e432ccb0cdc3c":{
      "scriptId":"u16"},
    "96427684db054111ac5e5b9ba7f3def2":{
      "scriptId":"u17"}}});