$axure.loadCurrentPage({
  "url":"5_2_1优游权益门票.html",
  "generationDate":new Date(1505907472993.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"4c54924b3b0744f8ad6a37da9ce67453",
    "type":"Axure:Page",
    "name":"5.2.1优游权益门票",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"db77f8919c734ee09e7fbfb89255e02f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2d00b6fdef74f70bb2e620a3751ed59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1确认订单/u74.png"}},
{
          "id":"bb7515a65f144987b1064f1bb515b649",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9080ce6ab024a5284d0b201167a9cbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0蔬菜宅配/u331.png"}},
{
          "id":"a3f462388bc34eb0a6bd092c958ebb72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f70b651bd604317b4b02365af66cc79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u5.png"}},
{
          "id":"6597debb8d3047d98133264a098e1e7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":125.5,
              "y":9.5},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2d7a708ee7413ba3bb6573870b904b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":125.5,
                  "y":9.5},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a62e28811fb6464aa2575f99968c0efe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":150,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99ee742d2b294b349862ea935cbb6411",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":150,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/5_2_1优游权益门票/u8.png"}},
{
          "id":"2bbadf925421416cb42e463055ecab9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":50},
            "size":{
              "width":150,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1739d3e1dc7141d18f097fda5737305e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":50},
                "size":{
                  "width":150,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/5_2_1优游权益门票/u8.png"}},
{
          "id":"7fe02eb5578648fb990dc8b71d1d16d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":208,
              "y":85},
            "size":{
              "width":120,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5be4bd4951c4bc19c82c04ce3e5b2a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":208,
                  "y":85},
                "size":{
                  "width":120,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5558459e0d5f4f4a9885b1ac3c426972",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":20,
              "y":120},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"409287ec66b140a9bf0ab56924734ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":120},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0b97e76d4ae44d7af478c274654fa89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":146},
            "size":{
              "width":318,
              "height":84},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a1f183842164b9a904143c5b825915d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":146},
                "size":{
                  "width":318,
                  "height":84},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/5_2_1优游权益门票/u16.png"}},
{
          "id":"77defda4b2a343e49fd372b6a9d2cce7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":156},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b17c10b1124c5b83796d555e2c3ee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":156},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/5_2_1优游权益门票/u18.jpg"}},
{
          "id":"e68eccaa87b14a118fc99984571e01e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":158},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"192e7a9d16d74286be7adc2d631dc7f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":158},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af94b29d07194071aa40a32647efb7f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":100,
              "y":188},
            "size":{
              "width":107,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffb4b521155b41e698cad7ac66fdae74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":100,
                  "y":188},
                "size":{
                  "width":107,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b306036de1a4a559949d916368ca46a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":294,
              "y":202},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d88e15edcdb14dc9bc3369bfca01b6f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":294,
                  "y":202},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce3a822658174b1e8135f758f9f9dd82",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":146},
            "size":{
              "width":318,
              "height":84}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 5.2.1.1订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"5_2_1_1订单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"37fda51287e1433cb5b090c9ccfbbf50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":318,
              "height":84},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a864642bb8944ebb7f408a11ebeede3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":318,
                  "height":84},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/5_2_1优游权益门票/u16.png"}},
{
          "id":"fba1ba57bace43a8b46db22b08a5f853",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":250},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e49b23a414984e009088e1dcdc28b6e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":250},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/5_2_1优游权益门票/u29.png"}},
{
          "id":"253576c96ab246ff89f34230a20bed6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":252},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc5c8e81aabd4f75bdf8011ccb33abaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":252},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a2982fa13f747fd9a0f5ac95b872340",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":100,
              "y":282},
            "size":{
              "width":107,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f77a75eed14413ca7b7dadae2c404fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":100,
                  "y":282},
                "size":{
                  "width":107,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f75a44565f24a7a9a7385cd832ce2da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":294,
              "y":296},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47b90fe6b38544b48d6a66acc6111969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":294,
                  "y":296},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5514006711b496388ad1d2bed226958",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":318,
              "height":84}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 5.2.1.1订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"5_2_1_1订单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "db77f8919c734ee09e7fbfb89255e02f":{
      "scriptId":"u0"},
    "f2d00b6fdef74f70bb2e620a3751ed59":{
      "scriptId":"u1"},
    "bb7515a65f144987b1064f1bb515b649":{
      "scriptId":"u2"},
    "e9080ce6ab024a5284d0b201167a9cbc":{
      "scriptId":"u3"},
    "a3f462388bc34eb0a6bd092c958ebb72":{
      "scriptId":"u4"},
    "3f70b651bd604317b4b02365af66cc79":{
      "scriptId":"u5"},
    "6597debb8d3047d98133264a098e1e7d":{
      "scriptId":"u6"},
    "5f2d7a708ee7413ba3bb6573870b904b":{
      "scriptId":"u7"},
    "a62e28811fb6464aa2575f99968c0efe":{
      "scriptId":"u8"},
    "99ee742d2b294b349862ea935cbb6411":{
      "scriptId":"u9"},
    "2bbadf925421416cb42e463055ecab9e":{
      "scriptId":"u10"},
    "1739d3e1dc7141d18f097fda5737305e":{
      "scriptId":"u11"},
    "7fe02eb5578648fb990dc8b71d1d16d1":{
      "scriptId":"u12"},
    "d5be4bd4951c4bc19c82c04ce3e5b2a2":{
      "scriptId":"u13"},
    "5558459e0d5f4f4a9885b1ac3c426972":{
      "scriptId":"u14"},
    "409287ec66b140a9bf0ab56924734ae9":{
      "scriptId":"u15"},
    "d0b97e76d4ae44d7af478c274654fa89":{
      "scriptId":"u16"},
    "5a1f183842164b9a904143c5b825915d":{
      "scriptId":"u17"},
    "77defda4b2a343e49fd372b6a9d2cce7":{
      "scriptId":"u18"},
    "88b17c10b1124c5b83796d555e2c3ee9":{
      "scriptId":"u19"},
    "e68eccaa87b14a118fc99984571e01e8":{
      "scriptId":"u20"},
    "192e7a9d16d74286be7adc2d631dc7f9":{
      "scriptId":"u21"},
    "af94b29d07194071aa40a32647efb7f6":{
      "scriptId":"u22"},
    "ffb4b521155b41e698cad7ac66fdae74":{
      "scriptId":"u23"},
    "2b306036de1a4a559949d916368ca46a":{
      "scriptId":"u24"},
    "d88e15edcdb14dc9bc3369bfca01b6f9":{
      "scriptId":"u25"},
    "ce3a822658174b1e8135f758f9f9dd82":{
      "scriptId":"u26"},
    "37fda51287e1433cb5b090c9ccfbbf50":{
      "scriptId":"u27"},
    "7a864642bb8944ebb7f408a11ebeede3":{
      "scriptId":"u28"},
    "fba1ba57bace43a8b46db22b08a5f853":{
      "scriptId":"u29"},
    "e49b23a414984e009088e1dcdc28b6e0":{
      "scriptId":"u30"},
    "253576c96ab246ff89f34230a20bed6d":{
      "scriptId":"u31"},
    "fc5c8e81aabd4f75bdf8011ccb33abaa":{
      "scriptId":"u32"},
    "4a2982fa13f747fd9a0f5ac95b872340":{
      "scriptId":"u33"},
    "8f77a75eed14413ca7b7dadae2c404fb":{
      "scriptId":"u34"},
    "2f75a44565f24a7a9a7385cd832ce2da":{
      "scriptId":"u35"},
    "47b90fe6b38544b48d6a66acc6111969":{
      "scriptId":"u36"},
    "f5514006711b496388ad1d2bed226958":{
      "scriptId":"u37"}}});