$axure.loadCurrentPage({
  "url":"定时配送.html",
  "generationDate":new Date(1505293718112.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"75ec2c7bc2ac4aefba6e6ea7d77d9961",
    "type":"Axure:Page",
    "name":"定时配送",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"69522d4f37c545baa5ab1d367f651974",
          "label":"配送设置面板",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fa2b227c6784b85a4b21c7f7f231842",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单支付页/u0.png"}},
{
          "id":"2391244f1f394a6ca32cb5309caf33dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3862ea5fc97341b8ab1d542cc0a13748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/top_u46.png"}},
{
          "id":"40dc83185821431c9a3b37807c09caa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":145,
              "y":8},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d7a1e45e22d4f9d929ae3d192ce8e23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":145,
                  "y":8},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b55c4cec4e824be38300ec5e503dd805",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":86},
            "size":{
              "width":360,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77cc75612d9242f799c42bf6167c1ab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":86},
                "size":{
                  "width":360,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u2.png"}},
{
          "id":"e0ab63f369064a3793181486f98a993d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":17,
              "y":68},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d351c393b40441bb926e85fe49bb5f13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":17,
                  "y":68},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6445225a9e0341ebaeadbd47b9d7f083",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":98},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4489858023484b1bbe0361d1448e7d11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":98},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b12eac5f72c48f585dbc18b2aafb846",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":86},
            "size":{
              "width":36,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"209e11e5c4254301b3130df72477bb56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":86},
                "size":{
                  "width":36,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜宅配/u5.png"}},
{
          "id":"2735f93f895243108cc85079610768ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":162},
            "size":{
              "width":360,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d77c0e86dd8a4319aae3becc8275d54a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":162},
                "size":{
                  "width":360,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u2.png"}},
{
          "id":"d4f9b0f9ac43439e8d8ddb44004032f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":17,
              "y":144},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df67550324a1438ca541b3bc1fb648ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":17,
                  "y":144},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6aeb7c20f34b490eb603d9799e8b3ce2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":174},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0a2138c7c604c3a891fff9c98d7eb9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":174},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01413c23ad8b4972b1bea5183e7e4c25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":164},
            "size":{
              "width":36,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff02a44d4bcc457f8daa06268683ba88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":164},
                "size":{
                  "width":36,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜宅配/u5.png"}},
{
          "id":"38473f7c025c42958424c2a2223adb2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83d77037c9df419fbf900ef0904ce927",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u107.png"}},
{
          "id":"15a0a45d71d74d66ad09a46d24b4507e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":238},
            "size":{
              "width":360,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf25e05dba8041f188abbc22e104d012",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":238},
                "size":{
                  "width":360,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u2.png"}},
{
          "id":"50a1f42ba4784c9f8c65084128cc1bc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":17,
              "y":220},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"283f33217c0f498d871b9e88bf95971c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":17,
                  "y":220},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b25545be82e41048f58697a79b78737",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":250},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"738a07cb2e5140eebee622ea85d63e38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":250},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d01b144b39c45939a6eadb4a8db1206",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":240},
            "size":{
              "width":36,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea03c7205e64f4886d749b65c4c8eaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":240},
                "size":{
                  "width":36,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜宅配/u5.png"}},
{
          "id":"465c68d9be364090899b4ee0ea656012",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":313},
            "size":{
              "width":360,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5412ae80daa453a9ebe937e2fa11cc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":313},
                "size":{
                  "width":360,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u2.png"}},
{
          "id":"56eb12907fc544a7a30ad0521e957ac0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":17,
              "y":295},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84ff1b4d6e874f35bc9796a0bb4eea25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":17,
                  "y":295},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58cefbcdd9d14434a257ac3277b76842",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":325},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a172b24ce324e20912ccb00e7e63a7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":325},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51c89d24cde14693aff7b321a29f0cb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":315},
            "size":{
              "width":36,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09bec33ba22340e4af450a74e71567f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":315},
                "size":{
                  "width":36,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜宅配/u5.png"}},
{
          "id":"5b56db548dcb45e8a8dd7e7fdaab1f12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":360,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cd0b5bb1b434594b5bc1c0fdb59cd6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":380},
                "size":{
                  "width":360,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定时配送/u40.png"}},
{
          "id":"432c7badccd2452488aee61322e98587",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":403},
            "size":{
              "width":323,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定时配送/u42_line.png"}},
{
          "id":"6aa91a280758415dbbb80e69085fc413",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":387},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29664d1cc1dc4b0b9d641a4d8bb9c155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":387},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad64d8d5e37e4514b81828b028639eb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":413},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b6f9e76b564ef4b8b7fccdae3b3437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":413},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24ea8acf6d814f728f98c35048cc6544",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":439},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e1894318cce4b52b909e42b9137681e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":439},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25c79c010a414af29c35af0b10fb09eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":413},
            "size":{
              "width":45,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48ba306dc74148fe8f6d92cff8d6bab5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":413},
                "size":{
                  "width":45,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"510ad33600a6432ebe0e29cea6c0a44a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":439},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7675a5bd3d2948f5b623dcad9e6b1792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":439},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38ce2c78f59c4e63b8d4d413e825e64a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":455},
            "size":{
              "width":323,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定时配送/u42_line.png"}},
{
          "id":"ea068b3c96af46e4988cb1f51e8e8e68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":473},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd8187c646d471387da6920b81cd0f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":473},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36f239cd574a4ea2b5099d2dc2efe3d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":286,
              "y":465},
            "size":{
              "width":54,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95406c91ee5c48539def7361bbc6cd73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":286,
                  "y":465},
                "size":{
                  "width":54,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":360,
              "height":50}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"467296247e744101ad9a98fb842daaa1",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d601fd5d81ca41ad9fa5455186dab207",
                  "label":"",
                  "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "size":{
                      "width":360,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea4dcbf1602d4dd1b8986d94393f86ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "size":{
                          "width":360,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品详情/u40.png"}},
{
                  "id":"f10cb96905384beaad5d8e4ac33a8edd",
                  "label":"",
                  "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":11,
                      "y":15},
                    "size":{
                      "width":79,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce15c513ba4c4610a867a172aedd03e0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":11,
                          "y":15},
                        "size":{
                          "width":79,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f5f30bc240d943f9bd6a25d2454d31fd",
                  "label":"",
                  "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b82629eff3bf464dacf20e564452544d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":0},
                        "size":{
                          "width":140,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/确认订单_4/u13.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "69522d4f37c545baa5ab1d367f651974":{
      "scriptId":"u0"},
    "4fa2b227c6784b85a4b21c7f7f231842":{
      "scriptId":"u1"},
    "2391244f1f394a6ca32cb5309caf33dc":{
      "scriptId":"u2"},
    "3862ea5fc97341b8ab1d542cc0a13748":{
      "scriptId":"u3"},
    "40dc83185821431c9a3b37807c09caa5":{
      "scriptId":"u4"},
    "0d7a1e45e22d4f9d929ae3d192ce8e23":{
      "scriptId":"u5"},
    "b55c4cec4e824be38300ec5e503dd805":{
      "scriptId":"u6"},
    "77cc75612d9242f799c42bf6167c1ab6":{
      "scriptId":"u7"},
    "e0ab63f369064a3793181486f98a993d":{
      "scriptId":"u8"},
    "d351c393b40441bb926e85fe49bb5f13":{
      "scriptId":"u9"},
    "6445225a9e0341ebaeadbd47b9d7f083":{
      "scriptId":"u10"},
    "4489858023484b1bbe0361d1448e7d11":{
      "scriptId":"u11"},
    "2b12eac5f72c48f585dbc18b2aafb846":{
      "scriptId":"u12"},
    "209e11e5c4254301b3130df72477bb56":{
      "scriptId":"u13"},
    "2735f93f895243108cc85079610768ff":{
      "scriptId":"u14"},
    "d77c0e86dd8a4319aae3becc8275d54a":{
      "scriptId":"u15"},
    "d4f9b0f9ac43439e8d8ddb44004032f9":{
      "scriptId":"u16"},
    "df67550324a1438ca541b3bc1fb648ca":{
      "scriptId":"u17"},
    "6aeb7c20f34b490eb603d9799e8b3ce2":{
      "scriptId":"u18"},
    "a0a2138c7c604c3a891fff9c98d7eb9c":{
      "scriptId":"u19"},
    "01413c23ad8b4972b1bea5183e7e4c25":{
      "scriptId":"u20"},
    "ff02a44d4bcc457f8daa06268683ba88":{
      "scriptId":"u21"},
    "38473f7c025c42958424c2a2223adb2a":{
      "scriptId":"u22"},
    "83d77037c9df419fbf900ef0904ce927":{
      "scriptId":"u23"},
    "15a0a45d71d74d66ad09a46d24b4507e":{
      "scriptId":"u24"},
    "bf25e05dba8041f188abbc22e104d012":{
      "scriptId":"u25"},
    "50a1f42ba4784c9f8c65084128cc1bc7":{
      "scriptId":"u26"},
    "283f33217c0f498d871b9e88bf95971c":{
      "scriptId":"u27"},
    "3b25545be82e41048f58697a79b78737":{
      "scriptId":"u28"},
    "738a07cb2e5140eebee622ea85d63e38":{
      "scriptId":"u29"},
    "4d01b144b39c45939a6eadb4a8db1206":{
      "scriptId":"u30"},
    "fea03c7205e64f4886d749b65c4c8eaf":{
      "scriptId":"u31"},
    "465c68d9be364090899b4ee0ea656012":{
      "scriptId":"u32"},
    "d5412ae80daa453a9ebe937e2fa11cc7":{
      "scriptId":"u33"},
    "56eb12907fc544a7a30ad0521e957ac0":{
      "scriptId":"u34"},
    "84ff1b4d6e874f35bc9796a0bb4eea25":{
      "scriptId":"u35"},
    "58cefbcdd9d14434a257ac3277b76842":{
      "scriptId":"u36"},
    "1a172b24ce324e20912ccb00e7e63a7d":{
      "scriptId":"u37"},
    "51c89d24cde14693aff7b321a29f0cb9":{
      "scriptId":"u38"},
    "09bec33ba22340e4af450a74e71567f3":{
      "scriptId":"u39"},
    "5b56db548dcb45e8a8dd7e7fdaab1f12":{
      "scriptId":"u40"},
    "9cd0b5bb1b434594b5bc1c0fdb59cd6b":{
      "scriptId":"u41"},
    "432c7badccd2452488aee61322e98587":{
      "scriptId":"u42"},
    "6aa91a280758415dbbb80e69085fc413":{
      "scriptId":"u43"},
    "29664d1cc1dc4b0b9d641a4d8bb9c155":{
      "scriptId":"u44"},
    "ad64d8d5e37e4514b81828b028639eb9":{
      "scriptId":"u45"},
    "41b6f9e76b564ef4b8b7fccdae3b3437":{
      "scriptId":"u46"},
    "24ea8acf6d814f728f98c35048cc6544":{
      "scriptId":"u47"},
    "6e1894318cce4b52b909e42b9137681e":{
      "scriptId":"u48"},
    "25c79c010a414af29c35af0b10fb09eb":{
      "scriptId":"u49"},
    "48ba306dc74148fe8f6d92cff8d6bab5":{
      "scriptId":"u50"},
    "510ad33600a6432ebe0e29cea6c0a44a":{
      "scriptId":"u51"},
    "7675a5bd3d2948f5b623dcad9e6b1792":{
      "scriptId":"u52"},
    "38ce2c78f59c4e63b8d4d413e825e64a":{
      "scriptId":"u53"},
    "ea068b3c96af46e4988cb1f51e8e8e68":{
      "scriptId":"u54"},
    "4bd8187c646d471387da6920b81cd0f3":{
      "scriptId":"u55"},
    "36f239cd574a4ea2b5099d2dc2efe3d3":{
      "scriptId":"u56"},
    "95406c91ee5c48539def7361bbc6cd73":{
      "scriptId":"u57"},
    "0a3cc1b1f0e346c5a0f2769a58cf56d0":{
      "scriptId":"u58"},
    "d601fd5d81ca41ad9fa5455186dab207":{
      "scriptId":"u59"},
    "ea4dcbf1602d4dd1b8986d94393f86ed":{
      "scriptId":"u60"},
    "f10cb96905384beaad5d8e4ac33a8edd":{
      "scriptId":"u61"},
    "ce15c513ba4c4610a867a172aedd03e0":{
      "scriptId":"u62"},
    "f5f30bc240d943f9bd6a25d2454d31fd":{
      "scriptId":"u63"},
    "b82629eff3bf464dacf20e564452544d":{
      "scriptId":"u64"}}});