$axure.loadCurrentPage({
  "url":"7_7商品详情.html",
  "generationDate":new Date(1510229483152.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"c06394a53bdc4345a0a7d44d99d0bdb7",
    "type":"Axure:Page",
    "name":"7.7商品详情",
    "notes":{
      "默认":"<p><span>1107更新：</span></p><p><span>1.底部悬浮操作栏中，购物车文字改为：加入购物车（10）。括号中的数字为购物车中的商品总数量</span></p><p><span>&nbsp;</span></p><p><span>1108更新：</span></p><p><span>1.去掉右上角符号</span></p><p><span>2.底部悬浮操作栏，把立即购买按钮改成加入购物车按钮；去掉重量标签</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"46b2ef1c9492489bab8340d0605e8ac1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":361},
            "size":{
              "width":360,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cc5b39987e04cf7a00bebe21ac986ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":361},
                "size":{
                  "width":360,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7_2限时特惠详情页/u2.png"}},
{
          "id":"37dc69d67e394d7c9aa70a0f2fe15ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":371},
            "size":{
              "width":151,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1670a4bac38947d9bf5be62fff080ce4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":371},
                "size":{
                  "width":151,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c11080a23e114023885c163a683f5d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":399},
            "size":{
              "width":360,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c01e1ded2d144fd2a2af605846d0045c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":399},
                "size":{
                  "width":360,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7_7商品详情/u4.png"}},
{
          "id":"5988d78ad6474af4adb8d691d62ea497",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":408},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"942fdeec085f4845884e8ef5f4a3892d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":408},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2dee2424cf74d868f60634cc343e728",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d506803b586640f9b7f54280f8f9a1e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"ac45b92f791b4adbb52042a50d25cfc4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ada90fac3cb74e89b9e2c1b983273738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"5f390aa89e4442d89b609ac3c1b89e76",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":151,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4fc3f15e1cf46478579cf55de74ea48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":151,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d38fcd7d323f4a108e45116661230bb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":41},
            "size":{
              "width":307,
              "height":320}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4813478d2ef64fc4a71f63f9a0e54b5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":41},
                "size":{
                  "width":307,
                  "height":320}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7_3农场店铺页/u114.jpg"}},
{
          "id":"0e7f4f9caefb487885a980ee6b688931",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":162,
              "y":408},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c4060afc2341c482964b7fb0299a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":162,
                  "y":408},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8741c7a45c16465f80c7accba7b02d82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":54,
              "y":408},
            "size":{
              "width":33,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a4ea9f681ec41faa6dc8814d98f1d4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":54,
                  "y":408},
                "size":{
                  "width":33,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ffa4396195b40c6bba23c8053ec1543",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":206,
              "y":408},
            "size":{
              "width":25,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e21cee70b544c8f836171cc0b12365f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":206,
                  "y":408},
                "size":{
                  "width":25,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76fd9a2a282c4312a85239829f40ddbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":470},
            "size":{
              "width":360,
              "height":2088}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8171c18a0bb943f983208d2bb1aff805",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":470},
                "size":{
                  "width":360,
                  "height":2088}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7_7商品详情/u22.png"}},
{
          "id":"450fa25d7b6449e1923e4e00704547db",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7bd62b167a16441da6fc8d2c77438ae0",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e4c82b18f55148318fa3e319d7948176",
                  "label":"",
                  "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "size":{
                      "width":360,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1637cf09be0f4f228e0b56ba9963538d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "size":{
                          "width":360,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（权益农旅）/u67.png"}},
{
                  "id":"bcb02cc1b40a4725a47806f7dc8de8e1",
                  "label":"",
                  "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":240,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c34281454aba4adb9fd796aa64285a37",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":240,
                          "y":0},
                        "size":{
                          "width":120,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 7.5确认订单(优品)",
                              "target":{
                                "targetType":"page",
                                "url":"7_5确认订单_优品__1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/7_2限时特惠详情页/u54.png"}},
{
                  "id":"0eac82c1f7774484b6dc70c95355ad41",
                  "label":"",
                  "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":16,
                      "y":16},
                    "size":{
                      "width":54,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d42fcc44ecd4bd5b2f50959400b095a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":16,
                          "y":16},
                        "size":{
                          "width":54,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6a024c6129b4493d94908ca2b8e63744",
                  "label":"购物车",
                  "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39ef32a444384a2bbc533004bc15d1d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 加入购物车提示",
                              "objectsToFades":[{
                                  "objectPath":["608367b176fe46519223526b80484713"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 加入购物车提示 淡入淡出 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["608367b176fe46519223526b80484713"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/7_7商品详情/购物车_u31.png"}}]}]},
{
          "id":"9b7707437101418eae12e96b22ce0704",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":441},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52374bead5c24dccb505267e3ab0de1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":441},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a67ca18711e3407f9503593471900687",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":54,
              "y":434},
            "size":{
              "width":47,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fe12f1669e14514aa76e8e4a46639f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":434},
                "size":{
                  "width":47,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fced02a6ce6f4865ba87b27b25297510",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":163,
              "y":446},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"572431248bde4a21bee2277b8e943030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":446},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3368709422534a2485dd22ded26c4837",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":207,
              "y":437.5},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba092f50adf841658ad191fe3d3cad2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":207,
                  "y":437.5},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页（极简）/u16.png"}},
{
          "id":"52de37f493234222a9beb1f337c3139b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":276,
              "y":437.5},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91d66695faf342ca83da1049732e7b0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":276,
                  "y":437.5},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页（极简）/u16.png"}},
{
          "id":"7475f4ae2ddd421a906f79bb0c6ffff6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":237,
              "y":437.5},
            "size":{
              "width":39,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"608367b176fe46519223526b80484713",
          "label":"加入购物车提示",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":109,
              "y":287},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 加入购物车提示 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["608367b176fe46519223526b80484713"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":109,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5c3c005357114539929018a9979ae215",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f3ef7b2630e6454d8bcee6e70d974fff",
                  "label":"",
                  "parentDynamicPanel":"608367b176fe46519223526b80484713",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0.5",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":140,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d8884fb0b324d3eb549e783da7205ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"608367b176fe46519223526b80484713",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.5",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":140,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/7_7商品详情/u45.png"}},
{
                  "id":"95962a8d91d542d2be52b18857a6c784",
                  "label":"",
                  "parentDynamicPanel":"608367b176fe46519223526b80484713",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":10},
                    "size":{
                      "width":50,
                      "height":50},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ad1f29a2fc54722bc63623017549b71",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"608367b176fe46519223526b80484713",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":45,
                          "y":10},
                        "size":{
                          "width":50,
                          "height":50},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/1_3支付成功（农旅卡购卡）/u10.png"}},
{
                  "id":"0869979fa2c940fd9967a59459150865",
                  "label":"",
                  "parentDynamicPanel":"608367b176fe46519223526b80484713",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":24,
                      "y":70},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93c209c984cc4cac9dbce3cf68f99550",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"608367b176fe46519223526b80484713",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":24,
                          "y":70},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"38acd35da4084e1dafaa587343aef41f",
          "label":"购物车入口",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":720},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 7.4优品购物车",
                      "target":{
                        "targetType":"page",
                        "url":"7_4优品购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":300,
          "fixedVertical":"bottom",
          "fixedMarginVertical":80,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d168dc0f5b324e12bb383839ea8225d8",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f9c208bd36d74200bc393644facd7cb6",
                  "label":"",
                  "parentDynamicPanel":"38acd35da4084e1dafaa587343aef41f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":40,
                      "height":40},
                    "cornerRadiusTopLeft":"50"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de935d73d85e414bab04b5343fe0521f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38acd35da4084e1dafaa587343aef41f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":40,
                          "height":40},
                        "cornerRadiusTopLeft":"50"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/7_3农场店铺页/u119.png"}},
{
                  "id":"6146c28c5d4948acb0b3957ba7256128",
                  "label":"",
                  "parentDynamicPanel":"38acd35da4084e1dafaa587343aef41f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":8},
                    "size":{
                      "width":24,
                      "height":23},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0bfc1620cf37478bb8634343f725456a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38acd35da4084e1dafaa587343aef41f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":8},
                        "size":{
                          "width":24,
                          "height":23},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/7_3农场店铺页/u121.png"}},
{
                  "id":"caecac3a73a74f9fa08411ecd4da154e",
                  "label":"",
                  "parentDynamicPanel":"38acd35da4084e1dafaa587343aef41f",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
}},
{
                  "id":"44a95e07403f42d58937990374d390df",
                  "label":"",
                  "parentDynamicPanel":"38acd35da4084e1dafaa587343aef41f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":25,
                      "y":8},
                    "size":{
                      "width":10,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18267bae3cae413bb09f9f338f044abf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"38acd35da4084e1dafaa587343aef41f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":25,
                          "y":8},
                        "size":{
                          "width":10,
                          "height":10},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/7_3农场店铺页/u124.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "46b2ef1c9492489bab8340d0605e8ac1":{
      "scriptId":"u0"},
    "8cc5b39987e04cf7a00bebe21ac986ae":{
      "scriptId":"u1"},
    "37dc69d67e394d7c9aa70a0f2fe15ff7":{
      "scriptId":"u2"},
    "1670a4bac38947d9bf5be62fff080ce4":{
      "scriptId":"u3"},
    "c11080a23e114023885c163a683f5d38":{
      "scriptId":"u4"},
    "c01e1ded2d144fd2a2af605846d0045c":{
      "scriptId":"u5"},
    "5988d78ad6474af4adb8d691d62ea497":{
      "scriptId":"u6"},
    "942fdeec085f4845884e8ef5f4a3892d":{
      "scriptId":"u7"},
    "c2dee2424cf74d868f60634cc343e728":{
      "scriptId":"u8"},
    "d506803b586640f9b7f54280f8f9a1e1":{
      "scriptId":"u9"},
    "ac45b92f791b4adbb52042a50d25cfc4":{
      "scriptId":"u10"},
    "ada90fac3cb74e89b9e2c1b983273738":{
      "scriptId":"u11"},
    "5f390aa89e4442d89b609ac3c1b89e76":{
      "scriptId":"u12"},
    "a4fc3f15e1cf46478579cf55de74ea48":{
      "scriptId":"u13"},
    "d38fcd7d323f4a108e45116661230bb5":{
      "scriptId":"u14"},
    "4813478d2ef64fc4a71f63f9a0e54b5b":{
      "scriptId":"u15"},
    "0e7f4f9caefb487885a980ee6b688931":{
      "scriptId":"u16"},
    "85c4060afc2341c482964b7fb0299a94":{
      "scriptId":"u17"},
    "8741c7a45c16465f80c7accba7b02d82":{
      "scriptId":"u18"},
    "8a4ea9f681ec41faa6dc8814d98f1d4a":{
      "scriptId":"u19"},
    "6ffa4396195b40c6bba23c8053ec1543":{
      "scriptId":"u20"},
    "2e21cee70b544c8f836171cc0b12365f":{
      "scriptId":"u21"},
    "76fd9a2a282c4312a85239829f40ddbe":{
      "scriptId":"u22"},
    "8171c18a0bb943f983208d2bb1aff805":{
      "scriptId":"u23"},
    "450fa25d7b6449e1923e4e00704547db":{
      "scriptId":"u24"},
    "e4c82b18f55148318fa3e319d7948176":{
      "scriptId":"u25"},
    "1637cf09be0f4f228e0b56ba9963538d":{
      "scriptId":"u26"},
    "bcb02cc1b40a4725a47806f7dc8de8e1":{
      "scriptId":"u27"},
    "c34281454aba4adb9fd796aa64285a37":{
      "scriptId":"u28"},
    "0eac82c1f7774484b6dc70c95355ad41":{
      "scriptId":"u29"},
    "5d42fcc44ecd4bd5b2f50959400b095a":{
      "scriptId":"u30"},
    "6a024c6129b4493d94908ca2b8e63744":{
      "scriptId":"u31"},
    "39ef32a444384a2bbc533004bc15d1d8":{
      "scriptId":"u32"},
    "9b7707437101418eae12e96b22ce0704":{
      "scriptId":"u33"},
    "52374bead5c24dccb505267e3ab0de1a":{
      "scriptId":"u34"},
    "a67ca18711e3407f9503593471900687":{
      "scriptId":"u35"},
    "5fe12f1669e14514aa76e8e4a46639f1":{
      "scriptId":"u36"},
    "fced02a6ce6f4865ba87b27b25297510":{
      "scriptId":"u37"},
    "572431248bde4a21bee2277b8e943030":{
      "scriptId":"u38"},
    "3368709422534a2485dd22ded26c4837":{
      "scriptId":"u39"},
    "ba092f50adf841658ad191fe3d3cad2d":{
      "scriptId":"u40"},
    "52de37f493234222a9beb1f337c3139b":{
      "scriptId":"u41"},
    "91d66695faf342ca83da1049732e7b0c":{
      "scriptId":"u42"},
    "7475f4ae2ddd421a906f79bb0c6ffff6":{
      "scriptId":"u43"},
    "608367b176fe46519223526b80484713":{
      "scriptId":"u44"},
    "f3ef7b2630e6454d8bcee6e70d974fff":{
      "scriptId":"u45"},
    "1d8884fb0b324d3eb549e783da7205ce":{
      "scriptId":"u46"},
    "95962a8d91d542d2be52b18857a6c784":{
      "scriptId":"u47"},
    "2ad1f29a2fc54722bc63623017549b71":{
      "scriptId":"u48"},
    "0869979fa2c940fd9967a59459150865":{
      "scriptId":"u49"},
    "93c209c984cc4cac9dbce3cf68f99550":{
      "scriptId":"u50"},
    "38acd35da4084e1dafaa587343aef41f":{
      "scriptId":"u51"},
    "f9c208bd36d74200bc393644facd7cb6":{
      "scriptId":"u52"},
    "de935d73d85e414bab04b5343fe0521f":{
      "scriptId":"u53"},
    "6146c28c5d4948acb0b3957ba7256128":{
      "scriptId":"u54"},
    "0bfc1620cf37478bb8634343f725456a":{
      "scriptId":"u55"},
    "caecac3a73a74f9fa08411ecd4da154e":{
      "scriptId":"u56"},
    "44a95e07403f42d58937990374d390df":{
      "scriptId":"u57"},
    "18267bae3cae413bb09f9f338f044abf":{
      "scriptId":"u58"}}});