$axure.loadCurrentPage({
  "url":"7_7商品详情_1.html",
  "generationDate":new Date(1510229500404.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"0bcb36a32b29440689253fe4df8f6e40",
    "type":"Axure:Page",
    "name":"7.7商品详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"46b2ef1c9492489bab8340d0605e8ac1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":361},
            "size":{
              "width":360,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cc5b39987e04cf7a00bebe21ac986ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":361},
                "size":{
                  "width":360,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7_2限时特惠详情页/u2.png"}},
{
          "id":"37dc69d67e394d7c9aa70a0f2fe15ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":371},
            "size":{
              "width":151,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1670a4bac38947d9bf5be62fff080ce4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":371},
                "size":{
                  "width":151,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c11080a23e114023885c163a683f5d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":399},
            "size":{
              "width":360,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c01e1ded2d144fd2a2af605846d0045c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":399},
                "size":{
                  "width":360,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7_7商品详情/u4.png"}},
{
          "id":"5988d78ad6474af4adb8d691d62ea497",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":408},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"942fdeec085f4845884e8ef5f4a3892d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":408},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fc2f13e48eb42ffa5567a5bd725bd2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":162,
              "y":442},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"398aac55199f41feb24372d91822a8fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":162,
                  "y":442},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d11fb8d432f347d7b4e4e8f727ad51e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":206,
              "y":434},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae4da80c86ce4774bd037acee2588196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":206,
                  "y":434},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页（极简）/u16.png"}},
{
          "id":"1cb0c75650c34777937a5cc0c100a0b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":275,
              "y":434},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c54d138c0b7d49438f8c1bb776e05177",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":275,
                  "y":434},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页（极简）/u16.png"}},
{
          "id":"141fd32af15e426c9ada96e9c2a14b4a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":236,
              "y":434},
            "size":{
              "width":39,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"c2dee2424cf74d868f60634cc343e728",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d506803b586640f9b7f54280f8f9a1e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"ac45b92f791b4adbb52042a50d25cfc4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ada90fac3cb74e89b9e2c1b983273738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"5f390aa89e4442d89b609ac3c1b89e76",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":151,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4fc3f15e1cf46478579cf55de74ea48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":151,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d678607f4984acab14002b61b9a6211",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":7},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0904d33cbc24be5a2c4fb95b76362e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":7},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/4_2_1线路详情/u135.png"}},
{
          "id":"3442dcf864574d40b3f4a09debee2259",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":17},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f22fca1328e74518bd5e51b67b0050aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":17},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/4_2_1线路详情/u135.png"}},
{
          "id":"9d7890b6cde1427881b7e4ee839a7ad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":27},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5565dd60137b444483a12d454961aea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":27},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/4_2_1线路详情/u135.png"}},
{
          "id":"d38fcd7d323f4a108e45116661230bb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":41},
            "size":{
              "width":307,
              "height":320}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4813478d2ef64fc4a71f63f9a0e54b5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":41},
                "size":{
                  "width":307,
                  "height":320}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7_3农场店铺页/u114.jpg"}},
{
          "id":"0e7f4f9caefb487885a980ee6b688931",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":162,
              "y":408},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c4060afc2341c482964b7fb0299a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":162,
                  "y":408},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8741c7a45c16465f80c7accba7b02d82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":54,
              "y":408},
            "size":{
              "width":33,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a4ea9f681ec41faa6dc8814d98f1d4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":54,
                  "y":408},
                "size":{
                  "width":33,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ffa4396195b40c6bba23c8053ec1543",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":206,
              "y":408},
            "size":{
              "width":25,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e21cee70b544c8f836171cc0b12365f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":206,
                  "y":408},
                "size":{
                  "width":25,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76fd9a2a282c4312a85239829f40ddbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":470},
            "size":{
              "width":360,
              "height":2088}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8171c18a0bb943f983208d2bb1aff805",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":470},
                "size":{
                  "width":360,
                  "height":2088}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7_7商品详情/u22.png"}},
{
          "id":"450fa25d7b6449e1923e4e00704547db",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7bd62b167a16441da6fc8d2c77438ae0",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e4c82b18f55148318fa3e319d7948176",
                  "label":"",
                  "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "size":{
                      "width":360,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1637cf09be0f4f228e0b56ba9963538d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "size":{
                          "width":360,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（权益农旅）/u67.png"}},
{
                  "id":"bcb02cc1b40a4725a47806f7dc8de8e1",
                  "label":"",
                  "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":240,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c34281454aba4adb9fd796aa64285a37",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":240,
                          "y":0},
                        "size":{
                          "width":120,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 7.5确认订单(优品)",
                              "target":{
                                "targetType":"page",
                                "url":"7_5确认订单_优品__2.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/7_2限时特惠详情页/u54.png"}},
{
                  "id":"0eac82c1f7774484b6dc70c95355ad41",
                  "label":"",
                  "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":16,
                      "y":8},
                    "size":{
                      "width":54,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d42fcc44ecd4bd5b2f50959400b095a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":16,
                          "y":8},
                        "size":{
                          "width":54,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4a0a5333d6284daf88d142e7af4a708e",
                  "label":"",
                  "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "location":{
                      "x":15,
                      "y":28},
                    "size":{
                      "width":51,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a355409f672465489a920ec50e64da9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "location":{
                          "x":15,
                          "y":28},
                        "size":{
                          "width":51,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6a024c6129b4493d94908ca2b8e63744",
                  "label":"",
                  "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39ef32a444384a2bbc533004bc15d1d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"450fa25d7b6449e1923e4e00704547db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 7.4优品购物车",
                              "target":{
                                "targetType":"page",
                                "url":"7_4优品购物车_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/7_7商品详情/购物车_u31.png"}}]}]},
{
          "id":"9b7707437101418eae12e96b22ce0704",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":441},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52374bead5c24dccb505267e3ab0de1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":441},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a67ca18711e3407f9503593471900687",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":54,
              "y":434},
            "size":{
              "width":47,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fe12f1669e14514aa76e8e4a46639f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":434},
                "size":{
                  "width":47,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "46b2ef1c9492489bab8340d0605e8ac1":{
      "scriptId":"u0"},
    "8cc5b39987e04cf7a00bebe21ac986ae":{
      "scriptId":"u1"},
    "37dc69d67e394d7c9aa70a0f2fe15ff7":{
      "scriptId":"u2"},
    "1670a4bac38947d9bf5be62fff080ce4":{
      "scriptId":"u3"},
    "c11080a23e114023885c163a683f5d38":{
      "scriptId":"u4"},
    "c01e1ded2d144fd2a2af605846d0045c":{
      "scriptId":"u5"},
    "5988d78ad6474af4adb8d691d62ea497":{
      "scriptId":"u6"},
    "942fdeec085f4845884e8ef5f4a3892d":{
      "scriptId":"u7"},
    "3fc2f13e48eb42ffa5567a5bd725bd2c":{
      "scriptId":"u8"},
    "398aac55199f41feb24372d91822a8fc":{
      "scriptId":"u9"},
    "d11fb8d432f347d7b4e4e8f727ad51e1":{
      "scriptId":"u10"},
    "ae4da80c86ce4774bd037acee2588196":{
      "scriptId":"u11"},
    "1cb0c75650c34777937a5cc0c100a0b1":{
      "scriptId":"u12"},
    "c54d138c0b7d49438f8c1bb776e05177":{
      "scriptId":"u13"},
    "141fd32af15e426c9ada96e9c2a14b4a":{
      "scriptId":"u14"},
    "c2dee2424cf74d868f60634cc343e728":{
      "scriptId":"u15"},
    "d506803b586640f9b7f54280f8f9a1e1":{
      "scriptId":"u16"},
    "ac45b92f791b4adbb52042a50d25cfc4":{
      "scriptId":"u17"},
    "ada90fac3cb74e89b9e2c1b983273738":{
      "scriptId":"u18"},
    "5f390aa89e4442d89b609ac3c1b89e76":{
      "scriptId":"u19"},
    "a4fc3f15e1cf46478579cf55de74ea48":{
      "scriptId":"u20"},
    "6d678607f4984acab14002b61b9a6211":{
      "scriptId":"u21"},
    "d0904d33cbc24be5a2c4fb95b76362e2":{
      "scriptId":"u22"},
    "3442dcf864574d40b3f4a09debee2259":{
      "scriptId":"u23"},
    "f22fca1328e74518bd5e51b67b0050aa":{
      "scriptId":"u24"},
    "9d7890b6cde1427881b7e4ee839a7ad0":{
      "scriptId":"u25"},
    "5565dd60137b444483a12d454961aea4":{
      "scriptId":"u26"},
    "d38fcd7d323f4a108e45116661230bb5":{
      "scriptId":"u27"},
    "4813478d2ef64fc4a71f63f9a0e54b5b":{
      "scriptId":"u28"},
    "0e7f4f9caefb487885a980ee6b688931":{
      "scriptId":"u29"},
    "85c4060afc2341c482964b7fb0299a94":{
      "scriptId":"u30"},
    "8741c7a45c16465f80c7accba7b02d82":{
      "scriptId":"u31"},
    "8a4ea9f681ec41faa6dc8814d98f1d4a":{
      "scriptId":"u32"},
    "6ffa4396195b40c6bba23c8053ec1543":{
      "scriptId":"u33"},
    "2e21cee70b544c8f836171cc0b12365f":{
      "scriptId":"u34"},
    "76fd9a2a282c4312a85239829f40ddbe":{
      "scriptId":"u35"},
    "8171c18a0bb943f983208d2bb1aff805":{
      "scriptId":"u36"},
    "450fa25d7b6449e1923e4e00704547db":{
      "scriptId":"u37"},
    "e4c82b18f55148318fa3e319d7948176":{
      "scriptId":"u38"},
    "1637cf09be0f4f228e0b56ba9963538d":{
      "scriptId":"u39"},
    "bcb02cc1b40a4725a47806f7dc8de8e1":{
      "scriptId":"u40"},
    "c34281454aba4adb9fd796aa64285a37":{
      "scriptId":"u41"},
    "0eac82c1f7774484b6dc70c95355ad41":{
      "scriptId":"u42"},
    "5d42fcc44ecd4bd5b2f50959400b095a":{
      "scriptId":"u43"},
    "4a0a5333d6284daf88d142e7af4a708e":{
      "scriptId":"u44"},
    "7a355409f672465489a920ec50e64da9":{
      "scriptId":"u45"},
    "6a024c6129b4493d94908ca2b8e63744":{
      "scriptId":"u46"},
    "39ef32a444384a2bbc533004bc15d1d8":{
      "scriptId":"u47"},
    "9b7707437101418eae12e96b22ce0704":{
      "scriptId":"u48"},
    "52374bead5c24dccb505267e3ab0de1a":{
      "scriptId":"u49"},
    "a67ca18711e3407f9503593471900687":{
      "scriptId":"u50"},
    "5fe12f1669e14514aa76e8e4a46639f1":{
      "scriptId":"u51"}}});