$axure.loadCurrentPage({
  "url":"确认订单.html",
  "generationDate":new Date(1505201934223.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"6be12571dab049489ed034530409a423",
    "type":"Axure:Page",
    "name":"确认订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"51c8fa84a4664c7dab516ee1a5ba4ce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":684}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f78ca961e44c21a74bb491998af120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":684}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u0.png"}},
{
          "id":"7cd79df75a1a40d0be2f5e9fd844911f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e9cc9557a0418d8bfdd6edff9777a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部分类/u2.png"}},
{
          "id":"c66da8410f0b40a1a25da9e299c2adb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a6503992e17402c9cd7575aa2dc1bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u107.png"}},
{
          "id":"85ffd25ae39541e4bf3f1dcd44a6454f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":144,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0033f8d31bd458ab113e6ac9d9bf168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":144,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac27bf609e6c49109b39f25f52aafa5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":360,
              "height":63},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9127cb8cdb2346d1ad2bf54c55e7f7ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":360,
                  "height":63},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u8.png"}},
{
          "id":"4aeca6d64fd7408f8e72bbb00bdf465c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":82},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c61c63a46a5e46c98dbc782712e1ef1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":82},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbb11fd840b549b28c06405e71f66580",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":46},
            "size":{
              "width":341,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b54c2115fc416dbf804a18c2c0854d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":46},
                "size":{
                  "width":341,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be67e09733664d7c962f5c633010c4d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":306,
              "y":82},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f9b1d619e54351831686069d9dc9ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":82},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecfdf277e1644ae4a842a0cdaeb89f2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":396},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aed3dea91689474a9b1ae3b6e625d620",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":396},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u16.png"}},
{
          "id":"cc1cbb52f6f94b7c922c76ae4ed8189c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":408},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b0f3bfe0c844e0783ed09b8e1652fdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":408},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5ed77a231e64834a05742879dfb2c16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":400},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"817b41bb0fb047928c5c9b5c37105e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":400},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页3/u213.png"}},
{
          "id":"f461aff4721d4ef2b098fbbf103be9bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":408},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"688febe8593540bdae4f45f1812a4676",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":408},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab6cd29e814049e8b7dd339bcaec7d74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":435},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6836e48614f46d38eebb0e82e272de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":435},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u16.png"}},
{
          "id":"1214ccd204bb43538bee5ecca61e530e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":447},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c5cf7bb7c774e4c9eec25d6f336e98a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":447},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89b3c5677c804ff9ba8abd40682bdbca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":439},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d75790f50b884c2c8587dad7211f7ab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":439},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页3/u213.png"}},
{
          "id":"9e869899fe5a4870a380e4d7ca31d66e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":447},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"229d75b030d14cdcb016b92d646cf13f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":447},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe3cdc18a654250a24217fb3029114a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":358},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e51d3cf9601e44d3956b56b6197c0794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":358},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u16.png"}},
{
          "id":"656be12cd2ce4c1d9e31a76b72811f24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":370},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df811ff5dfa4014aab27ce35aeb4847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":370},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f88f1d323c34caabb680275873140f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":370},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"602c9f18089040d6a5da45684225b484",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":370},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc3d4d8c569c45a1b45c40aa670b5991",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":192},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51d513f27d1449fa971cc24e39b7a4dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":192},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u16.png"}},
{
          "id":"3ae5972ad43e47cb8d9aa83cf072e384",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":204},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"447291b3d4774591adb02a2209b1d6ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":204},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db2de170a9ec4da1849717cbcd3d3f1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":204},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0101ea14c4494cd991b40d17c09f6f8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":204},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7d0458733e948b3bf995fb349327850",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8cc561a4f2047f693a2ca5bf922f235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u16.png"}},
{
          "id":"6cee59c9e5904125a3d4fb2de8e81330",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":244},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9ee2ae755854c9aa771d20c594763bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":244},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"618f3c633ca7421c8596909186af1748",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":244},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb892af0cb504df29079cee60e8b1cdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":244},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3815f56cdfd2471ca5630bed45d36e5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":269},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"626b3ffd684e4fcabd42227a7247ecee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":269},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u16.png"}},
{
          "id":"92dd97c8cbe24cd9bc26ba3bcf88aecc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":281},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5618bad80af4c819ca991832914f6d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":281},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82bcf64aef81469084d0d6a63a582e52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":300,
              "y":281},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a229505daf40473caf5e78d1a0bf4ebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":281},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f511b034c9984c48a88c95f5bcd78969",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":79,
              "y":281},
            "size":{
              "width":62,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b51f3603424121b0bb82c93d49b62d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":281},
                "size":{
                  "width":62,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72d0d6d74b2a4b4fbe212c665e8668ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":307},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"197a661afa6a464789ada8868ae690a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":307},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u16.png"}},
{
          "id":"e56087fc5a284d7ab53c95fe02d2a225",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":319},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4407fa94055498baf6a1c2116e5454c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":319},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ea6053485d54b09afaa4395755a262b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":306,
              "y":319},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e419c0b0022346428cf4c4ad098b01ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":319},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26fa105772874941b6a90352f7650c1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":112},
            "size":{
              "width":360,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc7805fb8b224e729779ea61c2b2d1c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":112},
                "size":{
                  "width":360,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u64.png"}},
{
          "id":"bf0561dca2da46ed817cc126e37c8408",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":120},
            "size":{
              "width":279,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c5e8aac30a648ebb43eb6a2657dbc49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":120},
                "size":{
                  "width":279,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82e21abe92184f1ea329261d34ade156",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":72,
              "y":157},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23e8fb0153564931bfc2da244bc99b29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":72,
                  "y":157},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7032d3d31f8f4073ab3c287d5c93cbef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":329,
              "y":158},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"520d8cb08c7145c4950ef544d0dd0328",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":329,
                  "y":158},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf98121536c64fb2be55549084e1e4db",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":540},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"77df7c62eca9490da617bcd3e6c501fd",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0a5397b6b3ff42348b9b510a8df04ef4",
                  "label":"",
                  "parentDynamicPanel":"cf98121536c64fb2be55549084e1e4db",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d9975b47fa74935a3702ba01bb10428",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cf98121536c64fb2be55549084e1e4db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/确认订单/u73.png"}},
{
                  "id":"ab1c6a826ca44974bd46eb535054b24b",
                  "label":"",
                  "parentDynamicPanel":"cf98121536c64fb2be55549084e1e4db",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":160,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"955147d2f7644cdcbad886a2dc34eec8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cf98121536c64fb2be55549084e1e4db",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":160,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 订单提交成功",
                              "target":{
                                "targetType":"page",
                                "url":"订单提交成功_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/确认订单/u75.png"}}]}]},
{
          "id":"22dca0f4cd1b4125bf1a9583f6195f9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":120},
            "size":{
              "width":54,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a050d6382cbe443ab2057f0da5932f84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":120},
                "size":{
                  "width":54,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u200.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "51c8fa84a4664c7dab516ee1a5ba4ce6":{
      "scriptId":"u0"},
    "02f78ca961e44c21a74bb491998af120":{
      "scriptId":"u1"},
    "7cd79df75a1a40d0be2f5e9fd844911f":{
      "scriptId":"u2"},
    "22e9cc9557a0418d8bfdd6edff9777a6":{
      "scriptId":"u3"},
    "c66da8410f0b40a1a25da9e299c2adb7":{
      "scriptId":"u4"},
    "0a6503992e17402c9cd7575aa2dc1bdf":{
      "scriptId":"u5"},
    "85ffd25ae39541e4bf3f1dcd44a6454f":{
      "scriptId":"u6"},
    "f0033f8d31bd458ab113e6ac9d9bf168":{
      "scriptId":"u7"},
    "ac27bf609e6c49109b39f25f52aafa5b":{
      "scriptId":"u8"},
    "9127cb8cdb2346d1ad2bf54c55e7f7ea":{
      "scriptId":"u9"},
    "4aeca6d64fd7408f8e72bbb00bdf465c":{
      "scriptId":"u10"},
    "c61c63a46a5e46c98dbc782712e1ef1a":{
      "scriptId":"u11"},
    "fbb11fd840b549b28c06405e71f66580":{
      "scriptId":"u12"},
    "a7b54c2115fc416dbf804a18c2c0854d":{
      "scriptId":"u13"},
    "be67e09733664d7c962f5c633010c4d4":{
      "scriptId":"u14"},
    "f1f9b1d619e54351831686069d9dc9ab":{
      "scriptId":"u15"},
    "ecfdf277e1644ae4a842a0cdaeb89f2f":{
      "scriptId":"u16"},
    "aed3dea91689474a9b1ae3b6e625d620":{
      "scriptId":"u17"},
    "cc1cbb52f6f94b7c922c76ae4ed8189c":{
      "scriptId":"u18"},
    "9b0f3bfe0c844e0783ed09b8e1652fdf":{
      "scriptId":"u19"},
    "a5ed77a231e64834a05742879dfb2c16":{
      "scriptId":"u20"},
    "817b41bb0fb047928c5c9b5c37105e77":{
      "scriptId":"u21"},
    "f461aff4721d4ef2b098fbbf103be9bb":{
      "scriptId":"u22"},
    "688febe8593540bdae4f45f1812a4676":{
      "scriptId":"u23"},
    "ab6cd29e814049e8b7dd339bcaec7d74":{
      "scriptId":"u24"},
    "b6836e48614f46d38eebb0e82e272de9":{
      "scriptId":"u25"},
    "1214ccd204bb43538bee5ecca61e530e":{
      "scriptId":"u26"},
    "6c5cf7bb7c774e4c9eec25d6f336e98a":{
      "scriptId":"u27"},
    "89b3c5677c804ff9ba8abd40682bdbca":{
      "scriptId":"u28"},
    "d75790f50b884c2c8587dad7211f7ab2":{
      "scriptId":"u29"},
    "9e869899fe5a4870a380e4d7ca31d66e":{
      "scriptId":"u30"},
    "229d75b030d14cdcb016b92d646cf13f":{
      "scriptId":"u31"},
    "abe3cdc18a654250a24217fb3029114a":{
      "scriptId":"u32"},
    "e51d3cf9601e44d3956b56b6197c0794":{
      "scriptId":"u33"},
    "656be12cd2ce4c1d9e31a76b72811f24":{
      "scriptId":"u34"},
    "7df811ff5dfa4014aab27ce35aeb4847":{
      "scriptId":"u35"},
    "7f88f1d323c34caabb680275873140f9":{
      "scriptId":"u36"},
    "602c9f18089040d6a5da45684225b484":{
      "scriptId":"u37"},
    "bc3d4d8c569c45a1b45c40aa670b5991":{
      "scriptId":"u38"},
    "51d513f27d1449fa971cc24e39b7a4dc":{
      "scriptId":"u39"},
    "3ae5972ad43e47cb8d9aa83cf072e384":{
      "scriptId":"u40"},
    "447291b3d4774591adb02a2209b1d6ef":{
      "scriptId":"u41"},
    "db2de170a9ec4da1849717cbcd3d3f1b":{
      "scriptId":"u42"},
    "0101ea14c4494cd991b40d17c09f6f8d":{
      "scriptId":"u43"},
    "e7d0458733e948b3bf995fb349327850":{
      "scriptId":"u44"},
    "b8cc561a4f2047f693a2ca5bf922f235":{
      "scriptId":"u45"},
    "6cee59c9e5904125a3d4fb2de8e81330":{
      "scriptId":"u46"},
    "b9ee2ae755854c9aa771d20c594763bf":{
      "scriptId":"u47"},
    "618f3c633ca7421c8596909186af1748":{
      "scriptId":"u48"},
    "fb892af0cb504df29079cee60e8b1cdd":{
      "scriptId":"u49"},
    "3815f56cdfd2471ca5630bed45d36e5e":{
      "scriptId":"u50"},
    "626b3ffd684e4fcabd42227a7247ecee":{
      "scriptId":"u51"},
    "92dd97c8cbe24cd9bc26ba3bcf88aecc":{
      "scriptId":"u52"},
    "e5618bad80af4c819ca991832914f6d2":{
      "scriptId":"u53"},
    "82bcf64aef81469084d0d6a63a582e52":{
      "scriptId":"u54"},
    "a229505daf40473caf5e78d1a0bf4ebd":{
      "scriptId":"u55"},
    "f511b034c9984c48a88c95f5bcd78969":{
      "scriptId":"u56"},
    "76b51f3603424121b0bb82c93d49b62d":{
      "scriptId":"u57"},
    "72d0d6d74b2a4b4fbe212c665e8668ea":{
      "scriptId":"u58"},
    "197a661afa6a464789ada8868ae690a3":{
      "scriptId":"u59"},
    "e56087fc5a284d7ab53c95fe02d2a225":{
      "scriptId":"u60"},
    "c4407fa94055498baf6a1c2116e5454c":{
      "scriptId":"u61"},
    "1ea6053485d54b09afaa4395755a262b":{
      "scriptId":"u62"},
    "e419c0b0022346428cf4c4ad098b01ff":{
      "scriptId":"u63"},
    "26fa105772874941b6a90352f7650c1e":{
      "scriptId":"u64"},
    "bc7805fb8b224e729779ea61c2b2d1c3":{
      "scriptId":"u65"},
    "bf0561dca2da46ed817cc126e37c8408":{
      "scriptId":"u66"},
    "4c5e8aac30a648ebb43eb6a2657dbc49":{
      "scriptId":"u67"},
    "82e21abe92184f1ea329261d34ade156":{
      "scriptId":"u68"},
    "23e8fb0153564931bfc2da244bc99b29":{
      "scriptId":"u69"},
    "7032d3d31f8f4073ab3c287d5c93cbef":{
      "scriptId":"u70"},
    "520d8cb08c7145c4950ef544d0dd0328":{
      "scriptId":"u71"},
    "cf98121536c64fb2be55549084e1e4db":{
      "scriptId":"u72"},
    "0a5397b6b3ff42348b9b510a8df04ef4":{
      "scriptId":"u73"},
    "7d9975b47fa74935a3702ba01bb10428":{
      "scriptId":"u74"},
    "ab1c6a826ca44974bd46eb535054b24b":{
      "scriptId":"u75"},
    "955147d2f7644cdcbad886a2dc34eec8":{
      "scriptId":"u76"},
    "22dca0f4cd1b4125bf1a9583f6195f9e":{
      "scriptId":"u77"},
    "a050d6382cbe443ab2057f0da5932f84":{
      "scriptId":"u78"}}});