$axure.loadCurrentPage({
  "url":"蔬菜箱详情.html",
  "generationDate":new Date(1505201767387.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"86f8280279dc4449a0912e0b5edb6ccc",
    "type":"Axure:Page",
    "name":"蔬菜箱详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"acf6d648d8be43bdbfc98fac50ae11f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95aeada5f1f7447b9bd251f5d11445e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜箱详情/u0.jpg"}},
{
          "id":"a52cecb9c1da4a48bf067fe59c6c8f1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":219},
            "size":{
              "width":360,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67927adba7684d80a0bd98d565258318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":219},
                "size":{
                  "width":360,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜箱详情/u2.png"}},
{
          "id":"4b3deebf160c4698a59702be5c4b4eee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":656},
            "size":{
              "width":360,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47bde437e1fb4690811046ed080a7198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":656},
                "size":{
                  "width":360,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜箱详情/u4.png"}},
{
          "id":"f822ef37ddb74c2dac9613697eff03b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1100},
            "size":{
              "width":360,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed98ecc28f1947b4ae6ca1772439a156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1100},
                "size":{
                  "width":360,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜箱详情/u6.png"}},
{
          "id":"d6141dfa40ef4139b0017f0edde28e52",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1310},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ddb5b966a1d34ec6b255bf44cb18469e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c94a79388d594169b46ba4a67438360f",
                  "label":"",
                  "parentDynamicPanel":"d6141dfa40ef4139b0017f0edde28e52",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80da90b8c74c4aeeab39b1987312489a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6141dfa40ef4139b0017f0edde28e52",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 返回",
                              "target":{
                                "targetType":"backUrl",
                                "includeVariables":false},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页2/top_u46.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "acf6d648d8be43bdbfc98fac50ae11f5":{
      "scriptId":"u0"},
    "95aeada5f1f7447b9bd251f5d11445e8":{
      "scriptId":"u1"},
    "a52cecb9c1da4a48bf067fe59c6c8f1c":{
      "scriptId":"u2"},
    "67927adba7684d80a0bd98d565258318":{
      "scriptId":"u3"},
    "4b3deebf160c4698a59702be5c4b4eee":{
      "scriptId":"u4"},
    "47bde437e1fb4690811046ed080a7198":{
      "scriptId":"u5"},
    "f822ef37ddb74c2dac9613697eff03b6":{
      "scriptId":"u6"},
    "ed98ecc28f1947b4ae6ca1772439a156":{
      "scriptId":"u7"},
    "d6141dfa40ef4139b0017f0edde28e52":{
      "scriptId":"u8"},
    "c94a79388d594169b46ba4a67438360f":{
      "scriptId":"u9"},
    "80da90b8c74c4aeeab39b1987312489a":{
      "scriptId":"u10"}}});