$axure.loadCurrentPage({
  "url":"蔬菜宅配_1.html",
  "generationDate":new Date(1505790833337.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"9f527a182f21478fbc13e4e5c8cf4595",
    "type":"Axure:Page",
    "name":"蔬菜宅配",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"51c8fa84a4664c7dab516ee1a5ba4ce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f78ca961e44c21a74bb491998af120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u79.png"}},
{
          "id":"7cd79df75a1a40d0be2f5e9fd844911f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e9cc9557a0418d8bfdd6edff9777a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜宅配/u331.png"}},
{
          "id":"c66da8410f0b40a1a25da9e299c2adb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a6503992e17402c9cd7575aa2dc1bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u103.png"}},
{
          "id":"85ffd25ae39541e4bf3f1dcd44a6454f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":143.5,
              "y":9.5},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0033f8d31bd458ab113e6ac9d9bf168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":143.5,
                  "y":9.5},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab5e2bd1ec514d13aa547ad6050ae965",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":697}},
          "adaptiveStyles":{
},
          "masterId":"a652b6c4ffdd4c70aeca0ab75b8386af"},
{
          "id":"39b7e9ca631f41ecaddbfe28e169dc48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":124},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8573a3987ac45339760fc7f05838123",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":124},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81efd492c2ef4b6c94fab6e50fbdf07b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":120,
              "y":170},
            "size":{
              "width":120,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e55a1eeba5949ada439358c06898548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":120,
                  "y":170},
                "size":{
                  "width":120,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择配送农场",
                      "target":{
                        "targetType":"page",
                        "url":"选择配送农场.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/蔬菜宅配_1/u39.png"}},
{
          "id":"c79c923292444f6da526893c5b8c55ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":60},
            "size":{
              "width":150,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a1c1ab75296406fa7c8d615947d43b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":60},
                "size":{
                  "width":150,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农场列表",
                      "target":{
                        "targetType":"page",
                        "url":"农场列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/蔬菜宅配_1/u41.png"}},
{
          "id":"7a4d8b90d2254a1c8da28414ac4941f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":60},
            "size":{
              "width":149,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ece0d9558584a9991f2ffc32ac1fc38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":60},
                "size":{
                  "width":149,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蔬菜宅配服务说明",
                      "target":{
                        "targetType":"page",
                        "url":"蔬菜宅配服务说明.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/蔬菜宅配_1/u43.png"}}]}},
  "masters":{
    "a652b6c4ffdd4c70aeca0ab75b8386af":{
      "packageId":"a652b6c4ffdd4c70aeca0ab75b8386af",
      "type":"Axure:Master",
      "name":"底部菜单0831",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d3980e768e434d6e8006717cfc1027d7",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":360,
                "height":63}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":0,
            "fixedVertical":"bottom",
            "fixedMarginVertical":0,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"33e17ce2012b4cbda3b4e022b57a30db",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"23869cb13512415b8b7971a663608747",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":23},
                      "size":{
                        "width":360,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3217ebd80ccd40c586ae39ff3ebb1543",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":23},
                          "size":{
                            "width":360,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页2/u65.png"}},
{
                    "id":"d004dced895a4eacb5efe917cca36edf",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":29,
                        "y":47},
                      "size":{
                        "width":21,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c8814745f745428db1ec799978487b14",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":29,
                            "y":47},
                          "size":{
                            "width":21,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"410ed3b8921c4b049c59109bbeab49e3",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":92,
                        "y":47},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a651b47d1e6e452cad7dfe30c2a0ae7c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":92,
                            "y":47},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"910efa73a76d4b0d9db84006f75ec976",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":299,
                        "y":47},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a42ded06f7a7420f807e1369cb460d27",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":299,
                            "y":47},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"6d5a344f556a43e6a407001e342fbfea",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":29,
                        "y":25},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0b939d02785c48368653a620956655b4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":29,
                            "y":25},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页2/u73.png"}},
{
                    "id":"fcf6bc000ad54b73a898b7612b0fd1be",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":310,
                        "y":27},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e8182f657e0a44b2a22072f4fe191a65",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":310,
                            "y":27},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页2/u75.png"}},
{
                    "id":"469056e6db7b48ea8beb0cde764fda32",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":229,
                        "y":47},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cd991483bf843d1ae7045e6e98ebf9b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":229,
                            "y":47},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"78876019e8d742938da830e4d8d4574a",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":240,
                        "y":27},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"29d462b7bb7a493b87ec072faf2f5d57",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":240,
                            "y":27},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页2/u79.png"}},
{
                    "id":"e54b788ac95740f0a17b53707d224d1e",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":150,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":60},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"60"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0322dabe132f4082bf7d358e28e63678",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":150,
                            "y":0},
                          "size":{
                            "width":60,
                            "height":60},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"60"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页2/u81.png"}},
{
                    "id":"e0c8b35ab6c640e4bfa3685c98588a2d",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":102,
                        "y":27},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"645a1aecdf08437f99fc444dc99f3e10",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":102,
                            "y":27},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页2/u83.png"}},
{
                    "id":"c6e97157c788455f9783097231226f7e",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":290,
                        "y":23},
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 个人中心主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人中心主页.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"696eadac344b40088748cf59bc9aaa9b",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":10,
                        "y":23},
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 主页2",
                                "target":{
                                  "targetType":"page",
                                  "url":"主页2.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"78c5dfdba7834f048ec91fe3d691915d",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"11px",
                      "fontWeight":"700",
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1},
                      "location":{
                        "x":162,
                        "y":8},
                      "size":{
                        "width":36,
                        "height":42}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a4c5ad2e9ab441438619cc38629775f8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"11px",
                          "fontWeight":"700",
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFF0000,
                            "opacity":1},
                          "location":{
                            "x":162,
                            "y":8},
                          "size":{
                            "width":36,
                            "height":42}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"2d4f7c0004734a37855bb4385356382b",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":87,
                        "y":23},
                      "size":{
                        "width":50,
                        "height":37}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 蔬菜宅配",
                                "target":{
                                  "targetType":"page",
                                  "url":"蔬菜宅配.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"e89d265e971e4db3a287a12f25c2f503",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":225,
                        "y":23},
                      "size":{
                        "width":50,
                        "height":37}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 农场列表",
                                "target":{
                                  "targetType":"page",
                                  "url":"农场列表.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"8de9a287ce1540abbcb6ec1b3c3a6254",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":150,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":63}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 会员充值",
                                "target":{
                                  "targetType":"page",
                                  "url":"会员充值.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}]}]}}},
  "objectPaths":{
    "51c8fa84a4664c7dab516ee1a5ba4ce6":{
      "scriptId":"u0"},
    "02f78ca961e44c21a74bb491998af120":{
      "scriptId":"u1"},
    "7cd79df75a1a40d0be2f5e9fd844911f":{
      "scriptId":"u2"},
    "22e9cc9557a0418d8bfdd6edff9777a6":{
      "scriptId":"u3"},
    "c66da8410f0b40a1a25da9e299c2adb7":{
      "scriptId":"u4"},
    "0a6503992e17402c9cd7575aa2dc1bdf":{
      "scriptId":"u5"},
    "85ffd25ae39541e4bf3f1dcd44a6454f":{
      "scriptId":"u6"},
    "f0033f8d31bd458ab113e6ac9d9bf168":{
      "scriptId":"u7"},
    "ab5e2bd1ec514d13aa547ad6050ae965":{
      "scriptId":"u8",
      "d3980e768e434d6e8006717cfc1027d7":{
        "scriptId":"u9"},
      "23869cb13512415b8b7971a663608747":{
        "scriptId":"u10"},
      "3217ebd80ccd40c586ae39ff3ebb1543":{
        "scriptId":"u11"},
      "d004dced895a4eacb5efe917cca36edf":{
        "scriptId":"u12"},
      "c8814745f745428db1ec799978487b14":{
        "scriptId":"u13"},
      "410ed3b8921c4b049c59109bbeab49e3":{
        "scriptId":"u14"},
      "a651b47d1e6e452cad7dfe30c2a0ae7c":{
        "scriptId":"u15"},
      "910efa73a76d4b0d9db84006f75ec976":{
        "scriptId":"u16"},
      "a42ded06f7a7420f807e1369cb460d27":{
        "scriptId":"u17"},
      "6d5a344f556a43e6a407001e342fbfea":{
        "scriptId":"u18"},
      "0b939d02785c48368653a620956655b4":{
        "scriptId":"u19"},
      "fcf6bc000ad54b73a898b7612b0fd1be":{
        "scriptId":"u20"},
      "e8182f657e0a44b2a22072f4fe191a65":{
        "scriptId":"u21"},
      "469056e6db7b48ea8beb0cde764fda32":{
        "scriptId":"u22"},
      "5cd991483bf843d1ae7045e6e98ebf9b":{
        "scriptId":"u23"},
      "78876019e8d742938da830e4d8d4574a":{
        "scriptId":"u24"},
      "29d462b7bb7a493b87ec072faf2f5d57":{
        "scriptId":"u25"},
      "e54b788ac95740f0a17b53707d224d1e":{
        "scriptId":"u26"},
      "0322dabe132f4082bf7d358e28e63678":{
        "scriptId":"u27"},
      "e0c8b35ab6c640e4bfa3685c98588a2d":{
        "scriptId":"u28"},
      "645a1aecdf08437f99fc444dc99f3e10":{
        "scriptId":"u29"},
      "c6e97157c788455f9783097231226f7e":{
        "scriptId":"u30"},
      "696eadac344b40088748cf59bc9aaa9b":{
        "scriptId":"u31"},
      "78c5dfdba7834f048ec91fe3d691915d":{
        "scriptId":"u32"},
      "a4c5ad2e9ab441438619cc38629775f8":{
        "scriptId":"u33"},
      "2d4f7c0004734a37855bb4385356382b":{
        "scriptId":"u34"},
      "e89d265e971e4db3a287a12f25c2f503":{
        "scriptId":"u35"},
      "8de9a287ce1540abbcb6ec1b3c3a6254":{
        "scriptId":"u36"}},
    "39b7e9ca631f41ecaddbfe28e169dc48":{
      "scriptId":"u37"},
    "f8573a3987ac45339760fc7f05838123":{
      "scriptId":"u38"},
    "81efd492c2ef4b6c94fab6e50fbdf07b":{
      "scriptId":"u39"},
    "1e55a1eeba5949ada439358c06898548":{
      "scriptId":"u40"},
    "c79c923292444f6da526893c5b8c55ea":{
      "scriptId":"u41"},
    "4a1c1ab75296406fa7c8d615947d43b5":{
      "scriptId":"u42"},
    "7a4d8b90d2254a1c8da28414ac4941f1":{
      "scriptId":"u43"},
    "9ece0d9558584a9991f2ffc32ac1fc38":{
      "scriptId":"u44"}}});