$axure.loadCurrentPage({
  "url":"5_2_2_1确认订单_宅配_.html",
  "generationDate":new Date(1505907473172.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"7a2606f3ea814b69ad671efa9e50828b",
    "type":"Axure:Page",
    "name":"5.2.2.1确认订单(宅配)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"51c8fa84a4664c7dab516ee1a5ba4ce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":684}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f78ca961e44c21a74bb491998af120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":684}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1确认订单/u0.png"}},
{
          "id":"7cd79df75a1a40d0be2f5e9fd844911f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e9cc9557a0418d8bfdd6edff9777a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0蔬菜宅配/u331.png"}},
{
          "id":"c66da8410f0b40a1a25da9e299c2adb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a6503992e17402c9cd7575aa2dc1bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u5.png"}},
{
          "id":"85ffd25ae39541e4bf3f1dcd44a6454f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":144,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0033f8d31bd458ab113e6ac9d9bf168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":144,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63d47bbdc03a41ff899fac785f7be3e2",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":540},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"30fa3e4ca19c4fa496708e55d8266e94",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bf6c593b51f24ea9be800bb3bc4491a1",
                  "label":"",
                  "parentDynamicPanel":"63d47bbdc03a41ff899fac785f7be3e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35219eff80814b72bfa5fd8867a0a5f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"63d47bbdc03a41ff899fac785f7be3e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/1_0蔬菜宅配/u293.png"}},
{
                  "id":"cca854aec8824de1ba1b6bd01f931ee9",
                  "label":"",
                  "parentDynamicPanel":"63d47bbdc03a41ff899fac785f7be3e2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":160,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11092aeb777147aaa1161984f2cb52a3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"63d47bbdc03a41ff899fac785f7be3e2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":160,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 5.2.2.2订单提交成功",
                              "target":{
                                "targetType":"page",
                                "url":"5_2_2_2订单提交成功.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/1_0蔬菜宅配/u301.png"}}]}]},
{
          "id":"ac27bf609e6c49109b39f25f52aafa5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":360,
              "height":63},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9127cb8cdb2346d1ad2bf54c55e7f7ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":360,
                  "height":63},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1确认订单/u8.png"}},
{
          "id":"4aeca6d64fd7408f8e72bbb00bdf465c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":82},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c61c63a46a5e46c98dbc782712e1ef1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":82},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbb11fd840b549b28c06405e71f66580",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":46},
            "size":{
              "width":341,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b54c2115fc416dbf804a18c2c0854d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":46},
                "size":{
                  "width":341,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be67e09733664d7c962f5c633010c4d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":306,
              "y":82},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f9b1d619e54351831686069d9dc9ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":82},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81ea905392c542479d28b1e1b6c38b8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":112},
            "size":{
              "width":360,
              "height":108},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc4037e9e3684b6e85dec7391da3d9d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":112},
                "size":{
                  "width":360,
                  "height":108},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/5_2_2_1确认订单_宅配_/u21.png"}},
{
          "id":"dc8c83afa62641b7a4b2f5209c5bc21a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":112},
            "size":{
              "width":360,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d8b7c5e1d134473bef86f637742a14a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":112},
                "size":{
                  "width":360,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1确认订单/u18.png"}},
{
          "id":"445fba072e54450eb601036068ed1500",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":118},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"514d21c91f4740ca817432d28481a61d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":118},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25e3a665db444e0ca52760a1bb34830b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":149},
            "size":{
              "width":326,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bacd5d7ec6474d45aa7b865a3bc45d36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":149},
                "size":{
                  "width":326,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85ae1d1768e741cbbc8b77873978dfb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":256},
            "size":{
              "width":360,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a77b20bda6744c4b4ed056e0f4cb631",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":256},
                "size":{
                  "width":360,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/5_2_2_1确认订单_宅配_/u29.png"}},
{
          "id":"7f8f7e7a3aae47edb8e277b590acc84d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":266},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5defd192eda54ceba2ba64dae5db6ef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":266},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_1选择指定农场/u38.jpg"}},
{
          "id":"5cb7aff6ebac441da3d27d7c07249882",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":266},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f97f040e1cf646db81a8d4497f354040",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":266},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_1选择指定农场/u40.jpg"}},
{
          "id":"1764d762fd584bc78a6bbab6f92f30f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":279},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddfcca2b89414fd69c2e3cd13a293f50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":279},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0蔬菜宅配/u5.png"}},
{
          "id":"f63f8a2fe4144f26a882e82d22cbac28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":283},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b1b54748e854c93b0ba5152b9c26281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":283},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab6cd29e814049e8b7dd339bcaec7d74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":414},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6836e48614f46d38eebb0e82e272de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":414},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1确认订单/u24.png"}},
{
          "id":"1214ccd204bb43538bee5ecca61e530e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":426},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c5cf7bb7c774e4c9eec25d6f336e98a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":426},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89b3c5677c804ff9ba8abd40682bdbca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":418},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d75790f50b884c2c8587dad7211f7ab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":418},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0蔬菜宅配/u5.png"}},
{
          "id":"9e869899fe5a4870a380e4d7ca31d66e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":426},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"229d75b030d14cdcb016b92d646cf13f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":426},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe3cdc18a654250a24217fb3029114a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":375},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e51d3cf9601e44d3956b56b6197c0794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":375},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1确认订单/u24.png"}},
{
          "id":"656be12cd2ce4c1d9e31a76b72811f24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":387},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df811ff5dfa4014aab27ce35aeb4847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":387},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f88f1d323c34caabb680275873140f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":387},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"602c9f18089040d6a5da45684225b484",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":387},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecc0cc248fb54bea9c2ed725949aa748",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":360,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e22b8117d9084ccdb74b12e8dc4953c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":360,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1确认订单/u18.png"}},
{
          "id":"4988e77ab7354f698af43264ca42884b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":236},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ea29e4e3c1f44a0b95170df68450872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":236},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a2d789df72d4eccb3ffe6dba7892812",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":325},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"063e03cef12343cabb6d612363e4a4b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":325},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u3.png"}},
{
          "id":"e5d954891f3a40bc891190edfdefa714",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":337},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d506cd55fed4e019ca8f66f58d2097d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":337},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb128cb1bfd342e38fc1d63d37f62b96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":333},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24c262b249904da392b536de6fdd7c16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":333},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0蔬菜宅配/u5.png"}},
{
          "id":"f065ab007fda45d59b2d1629551f283e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":337},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"271e3bbaccf5437897bad6019dc6c739",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":337},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "51c8fa84a4664c7dab516ee1a5ba4ce6":{
      "scriptId":"u0"},
    "02f78ca961e44c21a74bb491998af120":{
      "scriptId":"u1"},
    "7cd79df75a1a40d0be2f5e9fd844911f":{
      "scriptId":"u2"},
    "22e9cc9557a0418d8bfdd6edff9777a6":{
      "scriptId":"u3"},
    "c66da8410f0b40a1a25da9e299c2adb7":{
      "scriptId":"u4"},
    "0a6503992e17402c9cd7575aa2dc1bdf":{
      "scriptId":"u5"},
    "85ffd25ae39541e4bf3f1dcd44a6454f":{
      "scriptId":"u6"},
    "f0033f8d31bd458ab113e6ac9d9bf168":{
      "scriptId":"u7"},
    "63d47bbdc03a41ff899fac785f7be3e2":{
      "scriptId":"u8"},
    "bf6c593b51f24ea9be800bb3bc4491a1":{
      "scriptId":"u9"},
    "35219eff80814b72bfa5fd8867a0a5f9":{
      "scriptId":"u10"},
    "cca854aec8824de1ba1b6bd01f931ee9":{
      "scriptId":"u11"},
    "11092aeb777147aaa1161984f2cb52a3":{
      "scriptId":"u12"},
    "ac27bf609e6c49109b39f25f52aafa5b":{
      "scriptId":"u13"},
    "9127cb8cdb2346d1ad2bf54c55e7f7ea":{
      "scriptId":"u14"},
    "4aeca6d64fd7408f8e72bbb00bdf465c":{
      "scriptId":"u15"},
    "c61c63a46a5e46c98dbc782712e1ef1a":{
      "scriptId":"u16"},
    "fbb11fd840b549b28c06405e71f66580":{
      "scriptId":"u17"},
    "a7b54c2115fc416dbf804a18c2c0854d":{
      "scriptId":"u18"},
    "be67e09733664d7c962f5c633010c4d4":{
      "scriptId":"u19"},
    "f1f9b1d619e54351831686069d9dc9ab":{
      "scriptId":"u20"},
    "81ea905392c542479d28b1e1b6c38b8c":{
      "scriptId":"u21"},
    "cc4037e9e3684b6e85dec7391da3d9d9":{
      "scriptId":"u22"},
    "dc8c83afa62641b7a4b2f5209c5bc21a":{
      "scriptId":"u23"},
    "1d8b7c5e1d134473bef86f637742a14a":{
      "scriptId":"u24"},
    "445fba072e54450eb601036068ed1500":{
      "scriptId":"u25"},
    "514d21c91f4740ca817432d28481a61d":{
      "scriptId":"u26"},
    "25e3a665db444e0ca52760a1bb34830b":{
      "scriptId":"u27"},
    "bacd5d7ec6474d45aa7b865a3bc45d36":{
      "scriptId":"u28"},
    "85ae1d1768e741cbbc8b77873978dfb5":{
      "scriptId":"u29"},
    "2a77b20bda6744c4b4ed056e0f4cb631":{
      "scriptId":"u30"},
    "7f8f7e7a3aae47edb8e277b590acc84d":{
      "scriptId":"u31"},
    "5defd192eda54ceba2ba64dae5db6ef3":{
      "scriptId":"u32"},
    "5cb7aff6ebac441da3d27d7c07249882":{
      "scriptId":"u33"},
    "f97f040e1cf646db81a8d4497f354040":{
      "scriptId":"u34"},
    "1764d762fd584bc78a6bbab6f92f30f2":{
      "scriptId":"u35"},
    "ddfcca2b89414fd69c2e3cd13a293f50":{
      "scriptId":"u36"},
    "f63f8a2fe4144f26a882e82d22cbac28":{
      "scriptId":"u37"},
    "4b1b54748e854c93b0ba5152b9c26281":{
      "scriptId":"u38"},
    "ab6cd29e814049e8b7dd339bcaec7d74":{
      "scriptId":"u39"},
    "b6836e48614f46d38eebb0e82e272de9":{
      "scriptId":"u40"},
    "1214ccd204bb43538bee5ecca61e530e":{
      "scriptId":"u41"},
    "6c5cf7bb7c774e4c9eec25d6f336e98a":{
      "scriptId":"u42"},
    "89b3c5677c804ff9ba8abd40682bdbca":{
      "scriptId":"u43"},
    "d75790f50b884c2c8587dad7211f7ab2":{
      "scriptId":"u44"},
    "9e869899fe5a4870a380e4d7ca31d66e":{
      "scriptId":"u45"},
    "229d75b030d14cdcb016b92d646cf13f":{
      "scriptId":"u46"},
    "abe3cdc18a654250a24217fb3029114a":{
      "scriptId":"u47"},
    "e51d3cf9601e44d3956b56b6197c0794":{
      "scriptId":"u48"},
    "656be12cd2ce4c1d9e31a76b72811f24":{
      "scriptId":"u49"},
    "7df811ff5dfa4014aab27ce35aeb4847":{
      "scriptId":"u50"},
    "7f88f1d323c34caabb680275873140f9":{
      "scriptId":"u51"},
    "602c9f18089040d6a5da45684225b484":{
      "scriptId":"u52"},
    "ecc0cc248fb54bea9c2ed725949aa748":{
      "scriptId":"u53"},
    "e22b8117d9084ccdb74b12e8dc4953c9":{
      "scriptId":"u54"},
    "4988e77ab7354f698af43264ca42884b":{
      "scriptId":"u55"},
    "3ea29e4e3c1f44a0b95170df68450872":{
      "scriptId":"u56"},
    "2a2d789df72d4eccb3ffe6dba7892812":{
      "scriptId":"u57"},
    "063e03cef12343cabb6d612363e4a4b2":{
      "scriptId":"u58"},
    "e5d954891f3a40bc891190edfdefa714":{
      "scriptId":"u59"},
    "1d506cd55fed4e019ca8f66f58d2097d":{
      "scriptId":"u60"},
    "fb128cb1bfd342e38fc1d63d37f62b96":{
      "scriptId":"u61"},
    "24c262b249904da392b536de6fdd7c16":{
      "scriptId":"u62"},
    "f065ab007fda45d59b2d1629551f283e":{
      "scriptId":"u63"},
    "271e3bbaccf5437897bad6019dc6c739":{
      "scriptId":"u64"}}});