$axure.loadCurrentPage({
  "url":"订单列表.html",
  "generationDate":new Date(1505201796298.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"680cd2f73e39425d84cfa21b771d0d5d",
    "type":"Axure:Page",
    "name":"订单列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5478764aab9f4a20a74fb71300fd8493",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f744e371c2924ceebbbbd9e0c3ba3cd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单支付页/u0.png"}},
{
          "id":"4b4656b338e140c4aa62f7b4a67b0b20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49fbdad49e164288b0aabe2619bbde84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/top_u46.png"}},
{
          "id":"4a528dd320764523b31951041a737b03",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27305b67b1a14a0f9013bcf3289f9ca1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u107.png"}},
{
          "id":"c1edc8dbfc3b4c0685a75b40198906d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":145,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26fdb50b082642c290ccdc3bd44b38f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":145,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eb8b21536fe4e16bca31ea0e9d48d9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":340,
              "y":7},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e3a90f716f45e7adcbf0a804f8ea5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":340,
                  "y":7},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u23.png"}},
{
          "id":"fd52a68d6a274608b097c117535bbead",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":340,
              "y":17},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12ff929f9de4617872a8660f2d80f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":340,
                  "y":17},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u23.png"}},
{
          "id":"c1510f8dea5740acab80fe6a40f0c8f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":340,
              "y":27},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ce483e121444d79aa5cb35aa44fde0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":340,
                  "y":27},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u23.png"}},
{
          "id":"15bfd199c91542e9a3e3ab16166e20c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":89,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd1e66d5f534e09ad62deceae74d329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":89,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单列表/u14.png"}},
{
          "id":"75b8df78017e4c3abff54d59c5b84318",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":39},
            "size":{
              "width":91,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33bc03700dd64c0da470d71cb8f7a4aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":39},
                "size":{
                  "width":91,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单列表/u16.png"}},
{
          "id":"8340ac1988d246f1a31661bed00d4df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":39},
            "size":{
              "width":91,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d88bdce7d142c9b0bd5db4d37f9796",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":39},
                "size":{
                  "width":91,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单列表/u16.png"}},
{
          "id":"7ebb5d6311f94ca989ab361f37e5fbd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":269,
              "y":39},
            "size":{
              "width":91,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09c3ba5fd2de4d729feb94833779f02f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":269,
                  "y":39},
                "size":{
                  "width":91,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单列表/u16.png"}},
{
          "id":"4b762f2fb53340fa85281b62cdf54d61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":78},
            "size":{
              "width":360,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34602f0f8c6a45ea902ab7ae7e19d9c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":78},
                "size":{
                  "width":360,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农旅订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"农旅订单详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单列表/u22.png"}},
{
          "id":"8ca1ec5d1f13462585acc4898fecb7f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":148},
            "size":{
              "width":360,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71db849858f540de8621dc8f4593b6f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":148},
                "size":{
                  "width":360,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅卡权益详情/u40.png"}},
{
          "id":"e43de9cdf99c497497f976fbdf6ad381",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":89},
            "size":{
              "width":48,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cecd1dca0db94cd5bede9d310c5cc7f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":89},
                "size":{
                  "width":48,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u262.jpg"}},
{
          "id":"6e8e49a49319474288d45282a702cd1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":89},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a98f4ed3a384e3b96a814365ae94d4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":89},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35da7b8fd04c4d918ddbccdd4199d883",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":123},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db8167fc6e9f42a4bcac0abcae4fc2e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":123},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff1899f3ef1f4cdaaaeb909d8d6d7cf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":316,
              "y":125},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3937ffbd1bd542cc855cf28a67d77898",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":316,
                  "y":125},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1edfa94e7edf4a478169080a72f3003f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":151},
            "size":{
              "width":67,
              "height":25},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c29307826414df58bade74c4b019773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":151},
                "size":{
                  "width":67,
                  "height":25},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单列表/u34.png"}},
{
          "id":"98f075e43bbe434ebaf9d7100aa74647",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":151},
            "size":{
              "width":67,
              "height":25},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"016f43b2f937464b81f5a1bc595e680a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":151},
                "size":{
                  "width":67,
                  "height":25},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农旅订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"农旅订单详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单列表/u34.png"}},
{
          "id":"ca2093fe146340d29a79409a7cefcd30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":189},
            "size":{
              "width":360,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82395bae0d7043598dcdfb0717e0bb92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":189},
                "size":{
                  "width":360,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蔬果订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"蔬果订单详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单列表/u22.png"}},
{
          "id":"5c52e2bbeffe4bdeb80f0f5cb93e1759",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":259},
            "size":{
              "width":360,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a94bbb7881048398276d0f195846f89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":259},
                "size":{
                  "width":360,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅卡权益详情/u40.png"}},
{
          "id":"ad7ac70b27a64adc8f8cfce0b43b4b9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":200},
            "size":{
              "width":48,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9622b5df84f846558878b48bcd405bc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":200},
                "size":{
                  "width":48,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u166.png"}},
{
          "id":"5cfe18c6b25c40389ec2f4e159397ac1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":200},
            "size":{
              "width":231,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4dd187e90ea4fd1ab81df103ae7ba7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":200},
                "size":{
                  "width":231,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9ebcb004cf84805a5feb55a38075d0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":234},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53dc1a2f25874f0a981a1cbc5f4882eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":234},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0827db464cff4ced962b6f785234d360",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":316,
              "y":236},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f499503cd7940c291eed1184d35173c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":316,
                  "y":236},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec3cc55eb9e44b529fcc087686769cf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":262},
            "size":{
              "width":67,
              "height":25},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bac06e7d5184eb39ce58304a01b018d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":262},
                "size":{
                  "width":67,
                  "height":25},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单列表/u34.png"}},
{
          "id":"32ca4569dd50430cb0bb1dc8a4692ef2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":262},
            "size":{
              "width":67,
              "height":25},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26e931c9729d45cf854f4a0e3c1435d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":262},
                "size":{
                  "width":67,
                  "height":25},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蔬果订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"蔬果订单详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单列表/u34.png"}},
{
          "id":"2104f669c8ad4c8a9ea03a0f4cfd88f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":300},
            "size":{
              "width":360,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"630808adbbfc4791982e4f0fc38cf153",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":360,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蔬果订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"蔬果订单详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单列表/u22.png"}},
{
          "id":"671cab38f5e9473b9986e0c628b55d50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":370},
            "size":{
              "width":360,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ec2109d45c48648fd5e5c223633509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":370},
                "size":{
                  "width":360,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅卡权益详情/u40.png"}},
{
          "id":"c39a5aa48b664b5e846f68aa93d052ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":311},
            "size":{
              "width":48,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d3a49df19ba49fd8ac65ec439695751",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":311},
                "size":{
                  "width":48,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u166.png"}},
{
          "id":"c22c421f8bbe4f85a16a9f3c189c4c0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":311},
            "size":{
              "width":231,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c273416438b44d46968c95f8fa9bfdb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":311},
                "size":{
                  "width":231,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf20835d282f43f1bb0a307c6fa994f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":345},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02efd2d40ed445a684e72362fa28e021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":345},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a46ca8fe2474a4894c311ee24c69475",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":316,
              "y":347},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffaf1def158a453a845ba3ab42d77e25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":316,
                  "y":347},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd55e5577f14438fb9b240822bb2b4c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":373},
            "size":{
              "width":67,
              "height":25},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef748a314d2846bb8bbc5ba1594e4114",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":373},
                "size":{
                  "width":67,
                  "height":25},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单列表/u34.png"}},
{
          "id":"872020b2a45c48cd9e418d47717ac0ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":373},
            "size":{
              "width":67,
              "height":25},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"938a36e35bbf481bbecba6616bd172cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":373},
                "size":{
                  "width":67,
                  "height":25},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蔬果订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"蔬果订单详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单列表/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5478764aab9f4a20a74fb71300fd8493":{
      "scriptId":"u0"},
    "f744e371c2924ceebbbbd9e0c3ba3cd0":{
      "scriptId":"u1"},
    "4b4656b338e140c4aa62f7b4a67b0b20":{
      "scriptId":"u2"},
    "49fbdad49e164288b0aabe2619bbde84":{
      "scriptId":"u3"},
    "4a528dd320764523b31951041a737b03":{
      "scriptId":"u4"},
    "27305b67b1a14a0f9013bcf3289f9ca1":{
      "scriptId":"u5"},
    "c1edc8dbfc3b4c0685a75b40198906d1":{
      "scriptId":"u6"},
    "26fdb50b082642c290ccdc3bd44b38f5":{
      "scriptId":"u7"},
    "5eb8b21536fe4e16bca31ea0e9d48d9f":{
      "scriptId":"u8"},
    "59e3a90f716f45e7adcbf0a804f8ea5a":{
      "scriptId":"u9"},
    "fd52a68d6a274608b097c117535bbead":{
      "scriptId":"u10"},
    "e12ff929f9de4617872a8660f2d80f74":{
      "scriptId":"u11"},
    "c1510f8dea5740acab80fe6a40f0c8f0":{
      "scriptId":"u12"},
    "0ce483e121444d79aa5cb35aa44fde0b":{
      "scriptId":"u13"},
    "15bfd199c91542e9a3e3ab16166e20c2":{
      "scriptId":"u14"},
    "acd1e66d5f534e09ad62deceae74d329":{
      "scriptId":"u15"},
    "75b8df78017e4c3abff54d59c5b84318":{
      "scriptId":"u16"},
    "33bc03700dd64c0da470d71cb8f7a4aa":{
      "scriptId":"u17"},
    "8340ac1988d246f1a31661bed00d4df3":{
      "scriptId":"u18"},
    "a6d88bdce7d142c9b0bd5db4d37f9796":{
      "scriptId":"u19"},
    "7ebb5d6311f94ca989ab361f37e5fbd3":{
      "scriptId":"u20"},
    "09c3ba5fd2de4d729feb94833779f02f":{
      "scriptId":"u21"},
    "4b762f2fb53340fa85281b62cdf54d61":{
      "scriptId":"u22"},
    "34602f0f8c6a45ea902ab7ae7e19d9c5":{
      "scriptId":"u23"},
    "8ca1ec5d1f13462585acc4898fecb7f8":{
      "scriptId":"u24"},
    "71db849858f540de8621dc8f4593b6f8":{
      "scriptId":"u25"},
    "e43de9cdf99c497497f976fbdf6ad381":{
      "scriptId":"u26"},
    "cecd1dca0db94cd5bede9d310c5cc7f4":{
      "scriptId":"u27"},
    "6e8e49a49319474288d45282a702cd1d":{
      "scriptId":"u28"},
    "6a98f4ed3a384e3b96a814365ae94d4d":{
      "scriptId":"u29"},
    "35da7b8fd04c4d918ddbccdd4199d883":{
      "scriptId":"u30"},
    "db8167fc6e9f42a4bcac0abcae4fc2e2":{
      "scriptId":"u31"},
    "ff1899f3ef1f4cdaaaeb909d8d6d7cf1":{
      "scriptId":"u32"},
    "3937ffbd1bd542cc855cf28a67d77898":{
      "scriptId":"u33"},
    "1edfa94e7edf4a478169080a72f3003f":{
      "scriptId":"u34"},
    "1c29307826414df58bade74c4b019773":{
      "scriptId":"u35"},
    "98f075e43bbe434ebaf9d7100aa74647":{
      "scriptId":"u36"},
    "016f43b2f937464b81f5a1bc595e680a":{
      "scriptId":"u37"},
    "ca2093fe146340d29a79409a7cefcd30":{
      "scriptId":"u38"},
    "82395bae0d7043598dcdfb0717e0bb92":{
      "scriptId":"u39"},
    "5c52e2bbeffe4bdeb80f0f5cb93e1759":{
      "scriptId":"u40"},
    "2a94bbb7881048398276d0f195846f89":{
      "scriptId":"u41"},
    "ad7ac70b27a64adc8f8cfce0b43b4b9b":{
      "scriptId":"u42"},
    "9622b5df84f846558878b48bcd405bc5":{
      "scriptId":"u43"},
    "5cfe18c6b25c40389ec2f4e159397ac1":{
      "scriptId":"u44"},
    "f4dd187e90ea4fd1ab81df103ae7ba7d":{
      "scriptId":"u45"},
    "d9ebcb004cf84805a5feb55a38075d0c":{
      "scriptId":"u46"},
    "53dc1a2f25874f0a981a1cbc5f4882eb":{
      "scriptId":"u47"},
    "0827db464cff4ced962b6f785234d360":{
      "scriptId":"u48"},
    "1f499503cd7940c291eed1184d35173c":{
      "scriptId":"u49"},
    "ec3cc55eb9e44b529fcc087686769cf4":{
      "scriptId":"u50"},
    "6bac06e7d5184eb39ce58304a01b018d":{
      "scriptId":"u51"},
    "32ca4569dd50430cb0bb1dc8a4692ef2":{
      "scriptId":"u52"},
    "26e931c9729d45cf854f4a0e3c1435d3":{
      "scriptId":"u53"},
    "2104f669c8ad4c8a9ea03a0f4cfd88f2":{
      "scriptId":"u54"},
    "630808adbbfc4791982e4f0fc38cf153":{
      "scriptId":"u55"},
    "671cab38f5e9473b9986e0c628b55d50":{
      "scriptId":"u56"},
    "d1ec2109d45c48648fd5e5c223633509":{
      "scriptId":"u57"},
    "c39a5aa48b664b5e846f68aa93d052ef":{
      "scriptId":"u58"},
    "0d3a49df19ba49fd8ac65ec439695751":{
      "scriptId":"u59"},
    "c22c421f8bbe4f85a16a9f3c189c4c0f":{
      "scriptId":"u60"},
    "c273416438b44d46968c95f8fa9bfdb6":{
      "scriptId":"u61"},
    "bf20835d282f43f1bb0a307c6fa994f4":{
      "scriptId":"u62"},
    "02efd2d40ed445a684e72362fa28e021":{
      "scriptId":"u63"},
    "6a46ca8fe2474a4894c311ee24c69475":{
      "scriptId":"u64"},
    "ffaf1def158a453a845ba3ab42d77e25":{
      "scriptId":"u65"},
    "dd55e5577f14438fb9b240822bb2b4c0":{
      "scriptId":"u66"},
    "ef748a314d2846bb8bbc5ba1594e4114":{
      "scriptId":"u67"},
    "872020b2a45c48cd9e418d47717ac0ce":{
      "scriptId":"u68"},
    "938a36e35bbf481bbecba6616bd172cc":{
      "scriptId":"u69"}}});