$axure.loadCurrentPage({
  "url":"10_3会员管理.html",
  "generationDate":new Date(1510229501644.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"fa9860123bcd41ab8b9225ea33741d84",
    "type":"Axure:Page",
    "name":"10.3会员管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"93fc559d8180414982faf72d42539023",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "size":{
              "width":360,
              "height":680},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF1F1F1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c246cf616b4d4e33ac6e673b32258833",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "size":{
                  "width":360,
                  "height":680},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10_3会员管理/u0.png"}},
{
          "id":"ba1050bd091849359880aa2c73bb4441",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8bdde23b19c408b97308ca9ea977be4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10_1待发货/u2.png"}},
{
          "id":"b9cff1aa06f64d3cbea810dc79706469",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":7.5},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"476d5928cdc343dfae4334c0fcaded7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":7.5},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/10_1待发货/u4.png"}},
{
          "id":"5b5cfe99197147e0b670e7698380e85e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":148,
              "y":11},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df7304c95e2e454199b389fdf1238a85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":11},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"458410995a5e4bd9af16d76821d76a08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":85},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"497702f6be6445d7ba151eeafc94c3e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":85},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"b4d546f8d08b4b66a841d1efdd7f8223",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":93},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62f3c6a88fbe45a498c418a38bd65518",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":93},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3db9321b066a4c87ad44220bdd657f7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":113},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0323b69be8ca43c89933cdf9db360de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":113},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96c0af2e2d5d4914a557b2c0abb62705",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":135},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56d649e1268f456f9203febd9bd6e440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":135},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"8482483d0eb04f1386eb8f900b287366",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":143},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d494b23165d94ad08aa6322510024ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":143},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ab98734896b45cda0f487a893e3e7ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":163},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b9b0abe5f84925be71b555a4675273",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":163},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bfcba48d0ac4133ac637b6dcaebbeeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":185},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65e828406cfa4199a58d4ed37f933852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":185},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"4ca4c44c3b284dd59fd561b185d40432",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":193},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63f08789af6b49bfaf71556103eaa0ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":193},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5410f3559dd4735ad735ef35c6373fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":213},
            "size":{
              "width":189,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a35994de6a6a4fba920050dccb5a8f59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":213},
                "size":{
                  "width":189,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80d254a97d594f0e9da02c016f154561",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":235},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c15c707705dd44c2834d98dee5adc44c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":235},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"8257d4f2185747ecb7285fbecfc1525f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":243},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5040156a5a2b4daa8d340e8af82ce440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":243},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c392aa9ab244239981505b05d89af28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":263},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e829576830a449adbae98c9722f64799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":263},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f422022916374a529eeeb9d84bfc9c20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":285},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffddb0a7e9ba4a5f85c24bf2f8ca71f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":285},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"b8002d80260c4e388a42172bcfaf8a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":293},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54d21b0717d64abaa651f0db19817da5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":293},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6800c88e0cf4ea0a3be234b6f363703",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":313},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2a3c14fa062466f88c3d89d6110ad73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":313},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00981db82db8498182c2ba7e51104c96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":335},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30adcd6eed854d38b54f2d5db2b0f687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":335},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"35d34be09a854e4bb7365ffcbc610a6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":343},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85b42b8f6e3e4827b791c9a159bf225e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":343},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e18ab269f134802b10e44078b7ea1e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":363},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28702370693348b7bc8667752307e9e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":363},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c599fc61c9c4ca89cdbd1135ac744a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":385},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0204bb8fb13340638ec7311d96dfc900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":385},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"ba166624ae3242379efdc5b8f3ffc7b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":393},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18738f38ad3f4cfda79f3cf346afa79a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":393},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1d72305a5f44fb0b1fd19380858b041",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":413},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd2fc0f98ef840b682ebd969da02ce2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":413},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b3ed22960bd420fa23c921a15d25425",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":30,
              "y":50},
            "size":{
              "width":249,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abc2f5fada09457094d334a5de1b7fce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":50},
                "size":{
                  "width":249,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10_3会员管理/u50.png"}},
{
          "id":"07e6086cade14ec780f12287e656cd18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":62,
              "y":56},
            "size":{
              "width":111,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ee671f249074a99ab9a112adb7a9a04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":62,
                  "y":56},
                "size":{
                  "width":111,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcb8f278a9c54bea9be51dfb8ad505d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":53},
            "size":{
              "width":18,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc00129bb3e64e04bbb2437ce153b3a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":53},
                "size":{
                  "width":18,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_3_1_订单列表（现场管理）/u71.png"}},
{
          "id":"fcacb6998c094f229cd8f37dcfa63fe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF33CCFF},
            "location":{
              "x":289,
              "y":50},
            "size":{
              "width":51,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44655c695f48448ca0e5bf7057d09b02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CCFF},
                "location":{
                  "x":289,
                  "y":50},
                "size":{
                  "width":51,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10_3会员管理/u56.png"}},
{
          "id":"78d11779ac054367849f3f53a4ecbb97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":435},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1d5286d51ed4dfba4c469d281a0e5f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":435},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"b35c9522630543b3a74f090d9fd4a9cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":443},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a73fbd7ab0984feeb4ed27156f4168b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":443},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e73a9b169034ae392c3cf27b2d53a79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":463},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7db87467ec754576a2ff4e81b084446d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":463},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"640aa648409048a7a39d40b1cb51b120",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":485},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a51aef75e014dbbb8c7e8d31117cf66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":485},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"206cc6d2eb0b4d5982738c4ab9be2341",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":493},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c87d5cbbd7f147218a8d39387a9920b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":493},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73b9443464674960b7a34de0d80a6154",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":513},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f9bb0b3459746d2b86124d9174f4d68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":513},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d70309158d0466ba6c959e79cf828ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":535},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee42b34d5c534c65ac6fef796ea36b4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":535},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"105ea75445434567b7d62ea23c005bc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":543},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6720c273e5841128f506eae083576b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":543},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b207493929e4b73b73ee725929826da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":563},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4e624268f78428081a9045ccf4ae0dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":563},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ee1f230d0a74d23baaceae4cf9717d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":585},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c7b30b33b146b8b6069f5211614201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":585},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u9.png"}},
{
          "id":"7ed630c1a4cb4701a4862a93f642b95a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":593},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07ef1a38dfac4df495bd205d3f9ff155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":593},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bd6ee8a485e4b5d95a417e5692b60a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":10,
              "y":613},
            "size":{
              "width":195,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d5b7d383f1947729633dd05bc096f41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":10,
                  "y":613},
                "size":{
                  "width":195,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5f755ea17a147d79ff80091578e97a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":140,
              "y":651},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53f3c7a690d440f5af8c33724544ac43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":651},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "93fc559d8180414982faf72d42539023":{
      "scriptId":"u0"},
    "c246cf616b4d4e33ac6e673b32258833":{
      "scriptId":"u1"},
    "ba1050bd091849359880aa2c73bb4441":{
      "scriptId":"u2"},
    "f8bdde23b19c408b97308ca9ea977be4":{
      "scriptId":"u3"},
    "b9cff1aa06f64d3cbea810dc79706469":{
      "scriptId":"u4"},
    "476d5928cdc343dfae4334c0fcaded7c":{
      "scriptId":"u5"},
    "5b5cfe99197147e0b670e7698380e85e":{
      "scriptId":"u6"},
    "df7304c95e2e454199b389fdf1238a85":{
      "scriptId":"u7"},
    "458410995a5e4bd9af16d76821d76a08":{
      "scriptId":"u8"},
    "497702f6be6445d7ba151eeafc94c3e6":{
      "scriptId":"u9"},
    "b4d546f8d08b4b66a841d1efdd7f8223":{
      "scriptId":"u10"},
    "62f3c6a88fbe45a498c418a38bd65518":{
      "scriptId":"u11"},
    "3db9321b066a4c87ad44220bdd657f7b":{
      "scriptId":"u12"},
    "0323b69be8ca43c89933cdf9db360de9":{
      "scriptId":"u13"},
    "96c0af2e2d5d4914a557b2c0abb62705":{
      "scriptId":"u14"},
    "56d649e1268f456f9203febd9bd6e440":{
      "scriptId":"u15"},
    "8482483d0eb04f1386eb8f900b287366":{
      "scriptId":"u16"},
    "d494b23165d94ad08aa6322510024ae1":{
      "scriptId":"u17"},
    "2ab98734896b45cda0f487a893e3e7ec":{
      "scriptId":"u18"},
    "b9b9b0abe5f84925be71b555a4675273":{
      "scriptId":"u19"},
    "1bfcba48d0ac4133ac637b6dcaebbeeb":{
      "scriptId":"u20"},
    "65e828406cfa4199a58d4ed37f933852":{
      "scriptId":"u21"},
    "4ca4c44c3b284dd59fd561b185d40432":{
      "scriptId":"u22"},
    "63f08789af6b49bfaf71556103eaa0ff":{
      "scriptId":"u23"},
    "e5410f3559dd4735ad735ef35c6373fa":{
      "scriptId":"u24"},
    "a35994de6a6a4fba920050dccb5a8f59":{
      "scriptId":"u25"},
    "80d254a97d594f0e9da02c016f154561":{
      "scriptId":"u26"},
    "c15c707705dd44c2834d98dee5adc44c":{
      "scriptId":"u27"},
    "8257d4f2185747ecb7285fbecfc1525f":{
      "scriptId":"u28"},
    "5040156a5a2b4daa8d340e8af82ce440":{
      "scriptId":"u29"},
    "3c392aa9ab244239981505b05d89af28":{
      "scriptId":"u30"},
    "e829576830a449adbae98c9722f64799":{
      "scriptId":"u31"},
    "f422022916374a529eeeb9d84bfc9c20":{
      "scriptId":"u32"},
    "ffddb0a7e9ba4a5f85c24bf2f8ca71f0":{
      "scriptId":"u33"},
    "b8002d80260c4e388a42172bcfaf8a9f":{
      "scriptId":"u34"},
    "54d21b0717d64abaa651f0db19817da5":{
      "scriptId":"u35"},
    "a6800c88e0cf4ea0a3be234b6f363703":{
      "scriptId":"u36"},
    "c2a3c14fa062466f88c3d89d6110ad73":{
      "scriptId":"u37"},
    "00981db82db8498182c2ba7e51104c96":{
      "scriptId":"u38"},
    "30adcd6eed854d38b54f2d5db2b0f687":{
      "scriptId":"u39"},
    "35d34be09a854e4bb7365ffcbc610a6b":{
      "scriptId":"u40"},
    "85b42b8f6e3e4827b791c9a159bf225e":{
      "scriptId":"u41"},
    "8e18ab269f134802b10e44078b7ea1e9":{
      "scriptId":"u42"},
    "28702370693348b7bc8667752307e9e0":{
      "scriptId":"u43"},
    "0c599fc61c9c4ca89cdbd1135ac744a5":{
      "scriptId":"u44"},
    "0204bb8fb13340638ec7311d96dfc900":{
      "scriptId":"u45"},
    "ba166624ae3242379efdc5b8f3ffc7b6":{
      "scriptId":"u46"},
    "18738f38ad3f4cfda79f3cf346afa79a":{
      "scriptId":"u47"},
    "b1d72305a5f44fb0b1fd19380858b041":{
      "scriptId":"u48"},
    "dd2fc0f98ef840b682ebd969da02ce2c":{
      "scriptId":"u49"},
    "2b3ed22960bd420fa23c921a15d25425":{
      "scriptId":"u50"},
    "abc2f5fada09457094d334a5de1b7fce":{
      "scriptId":"u51"},
    "07e6086cade14ec780f12287e656cd18":{
      "scriptId":"u52"},
    "3ee671f249074a99ab9a112adb7a9a04":{
      "scriptId":"u53"},
    "fcb8f278a9c54bea9be51dfb8ad505d6":{
      "scriptId":"u54"},
    "fc00129bb3e64e04bbb2437ce153b3a1":{
      "scriptId":"u55"},
    "fcacb6998c094f229cd8f37dcfa63fe6":{
      "scriptId":"u56"},
    "44655c695f48448ca0e5bf7057d09b02":{
      "scriptId":"u57"},
    "78d11779ac054367849f3f53a4ecbb97":{
      "scriptId":"u58"},
    "d1d5286d51ed4dfba4c469d281a0e5f0":{
      "scriptId":"u59"},
    "b35c9522630543b3a74f090d9fd4a9cf":{
      "scriptId":"u60"},
    "a73fbd7ab0984feeb4ed27156f4168b4":{
      "scriptId":"u61"},
    "6e73a9b169034ae392c3cf27b2d53a79":{
      "scriptId":"u62"},
    "7db87467ec754576a2ff4e81b084446d":{
      "scriptId":"u63"},
    "640aa648409048a7a39d40b1cb51b120":{
      "scriptId":"u64"},
    "3a51aef75e014dbbb8c7e8d31117cf66":{
      "scriptId":"u65"},
    "206cc6d2eb0b4d5982738c4ab9be2341":{
      "scriptId":"u66"},
    "c87d5cbbd7f147218a8d39387a9920b7":{
      "scriptId":"u67"},
    "73b9443464674960b7a34de0d80a6154":{
      "scriptId":"u68"},
    "4f9bb0b3459746d2b86124d9174f4d68":{
      "scriptId":"u69"},
    "9d70309158d0466ba6c959e79cf828ef":{
      "scriptId":"u70"},
    "ee42b34d5c534c65ac6fef796ea36b4e":{
      "scriptId":"u71"},
    "105ea75445434567b7d62ea23c005bc7":{
      "scriptId":"u72"},
    "a6720c273e5841128f506eae083576b4":{
      "scriptId":"u73"},
    "5b207493929e4b73b73ee725929826da":{
      "scriptId":"u74"},
    "a4e624268f78428081a9045ccf4ae0dc":{
      "scriptId":"u75"},
    "7ee1f230d0a74d23baaceae4cf9717d3":{
      "scriptId":"u76"},
    "32c7b30b33b146b8b6069f5211614201":{
      "scriptId":"u77"},
    "7ed630c1a4cb4701a4862a93f642b95a":{
      "scriptId":"u78"},
    "07ef1a38dfac4df495bd205d3f9ff155":{
      "scriptId":"u79"},
    "1bd6ee8a485e4b5d95a417e5692b60a9":{
      "scriptId":"u80"},
    "2d5b7d383f1947729633dd05bc096f41":{
      "scriptId":"u81"},
    "b5f755ea17a147d79ff80091578e97a4":{
      "scriptId":"u82"},
    "53f3c7a690d440f5af8c33724544ac43":{
      "scriptId":"u83"}}});