$axure.loadCurrentPage({
  "url":"1_7合作农场列表_1.html",
  "generationDate":new Date(1510229485688.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"66e2a68d58f04b9e82943c510557b416",
    "type":"Axure:Page",
    "name":"1.7合作农场列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7c12933d0bc24405a612b2201ed1f9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "size":{
              "width":360,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF1F1F1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b90dc06fd824d4798dead72e9e72137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "size":{
                  "width":360,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_7合作农场列表/u0.png"}},
{
          "id":"0ef91a4cdc224eaba9cfe12217693195",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":360,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc16575a55da4f6cb7d57da467815499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":360,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_2农场体验游详情/农耕游栏首_u16.png"}},
{
          "id":"dd55564beecf473b8178d42989910512",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":9,
              "y":46},
            "size":{
              "width":45,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7943030f2614cb6b12f6e5f0c39624d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":9,
                  "y":46},
                "size":{
                  "width":45,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac9ed8e142b84f8e9f3bbc7020576180",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":310,
              "y":46},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"655a11ee3c2b4e74a10602d09f2b5ecd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":46},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6eae458423394eb68721497ac4c55d84",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":40},
            "size":{
              "width":70,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 排序",
                      "objectsToFades":[{
                          "objectPath":["b4c027ffe14149eba7701dc7ae81a538"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"947c443719a242d18e6175bd05437383",
          "label":"top",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbb3bd178c4840e7b687e3cc2bf5aeac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"8a26748c07d84c978e77d1a6796ec710",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddf229ecd0b04f15afcfe458b6ea5005",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"2962fb429fe7492e97f2f69e666a43dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":69},
            "size":{
              "width":360,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31a8be9aa3b0436c8a2e93fbe3615df7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":69},
                "size":{
                  "width":360,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 4.1.1农场主页",
                      "target":{
                        "targetType":"page",
                        "url":"4_1_1农场主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/1_7合作农场列表/u13.png"}},
{
          "id":"a8b74e3b5e5443f6b8cb379f91bf56a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":80},
            "size":{
              "width":64,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d709e70599347d4b09878402fc1c31a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":80},
                "size":{
                  "width":64,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1选择指定农场/u36.jpg"}},
{
          "id":"94397e89a2ea4e63be8113c95175746d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":80},
            "size":{
              "width":277,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f353eb47591e4ad1be9d4802195332de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":80},
                "size":{
                  "width":277,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02d99dee21c44246a992d399ec9a591c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":98,
              "y":121},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5109dc365e6248d99ca86abe12895ebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":98,
                  "y":121},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29beb4f2934e4fa9ba3d45b2bc0dcb99",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":118},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f4c783dedd45998c60bbc17229da6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":118},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u22.png"}},
{
          "id":"8164aef97ff641f0ae7a7e3b65417127",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":141},
            "size":{
              "width":360,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2611f7fd13424dd1a57a09a52241b9cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":141},
                "size":{
                  "width":360,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 4.1.1农场主页",
                      "target":{
                        "targetType":"page",
                        "url":"4_1_1农场主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/1_7合作农场列表/u13.png"}},
{
          "id":"c56451ac208b46e184a80c1ea8b9e81a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":152},
            "size":{
              "width":64,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d69cb5f0a233469c8a6283d6d3509177",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":152},
                "size":{
                  "width":64,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_7合作农场列表/u25.JPG"}},
{
          "id":"ef9b75e91503445e8e9422559eda51a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":152},
            "size":{
              "width":277,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"908b77ca6be6441a825b5e2c467ff86d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":152},
                "size":{
                  "width":277,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84bb49fa53b44f5f9162612d2e517494",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":213},
            "size":{
              "width":360,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f01838ab81a4c1396b52b3d41a044f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":213},
                "size":{
                  "width":360,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_7合作农场列表/u13.png"}},
{
          "id":"197c9685c43448578df9544f823a5371",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":224},
            "size":{
              "width":64,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e629842ff0c4a4f893cde2172820af8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":224},
                "size":{
                  "width":64,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_7合作农场列表/u31.jpg"}},
{
          "id":"2a21b8e52b1442749b7dee016a469f0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":224},
            "size":{
              "width":277,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5319938770d2490eb570d0370d1babdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":224},
                "size":{
                  "width":277,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24a6abccc0d64da59064865220625dda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":285},
            "size":{
              "width":360,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12d0a9d53f7e4c61a7039baeb852761f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":285},
                "size":{
                  "width":360,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_7合作农场列表/u13.png"}},
{
          "id":"5b1ace2f26bf40239bc9c19305b30b0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":296},
            "size":{
              "width":64,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c4d35d8f0f1441f9c734b56a20243ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":296},
                "size":{
                  "width":64,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_7合作农场列表/u37.jpg"}},
{
          "id":"3f7489f5378d4314a03b14ee151ad72e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":296},
            "size":{
              "width":277,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"829d9a2b5ac9449a9418fdcd435577c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":296},
                "size":{
                  "width":277,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"440e38e827e7448ab62c48745f7a0c4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":357},
            "size":{
              "width":360,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aea0af938764e55a8f52d97bc14e05f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":357},
                "size":{
                  "width":360,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_7合作农场列表/u13.png"}},
{
          "id":"cff96f4e7dfc4c1c87aba349c0194ee2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":368},
            "size":{
              "width":64,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"709a752bc0aa4c869be81b06d6f2fe24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":368},
                "size":{
                  "width":64,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_7合作农场列表/u43.jpg"}},
{
          "id":"db5a1fb5130f4b7cb500c0343cdcc69f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":368},
            "size":{
              "width":277,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9443eea60e3425da1dbd51564015492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":368},
                "size":{
                  "width":277,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c3274f667d74012a0d695789885d254",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":83,
              "y":102},
            "size":{
              "width":130,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41558dd8cccb4074b00e928a1da10831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":83,
                  "y":102},
                "size":{
                  "width":130,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e25ab7f0a0f486f8a2f19a2b1615134",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":102,
              "y":190},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54dcb015977544768ba7f57335ca706f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":102,
                  "y":190},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e0bcc0f5e0c471e88bfaf4a247c4379",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":187},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2186c6ed973a40be965ce73a113c2345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":187},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u22.png"}},
{
          "id":"6174fe093d6244cdb61af73733e0e10f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":87,
              "y":171},
            "size":{
              "width":130,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e246c198634e39848ab6fbfa4fb2db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":87,
                  "y":171},
                "size":{
                  "width":130,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77a1eedba63443eca79d7d0d811a0ea6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":101,
              "y":261},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80bde6c3393548a58105e8a89ac2e705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":101,
                  "y":261},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00b63801550c4de98bb2c7b308c85474",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":258},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3c4e8a13b36401dba02dac99114446e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":258},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u22.png"}},
{
          "id":"fbda3903df9744cc9d1edbf60a27e804",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":86,
              "y":242},
            "size":{
              "width":123,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27e054d46254f289b216234151c1da1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":86,
                  "y":242},
                "size":{
                  "width":123,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56a32cf70b7f4b0da43037d0ce45181a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":101,
              "y":332},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50035969ccfb49d1a7796f87628e52ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":101,
                  "y":332},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49424cd1e05b42208da55280eb01e0f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":329},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dedf8469d6634a0386a3a01e02a2ae4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":329},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u22.png"}},
{
          "id":"c46984e462644fed895d0ea6dc92bfd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":86,
              "y":313},
            "size":{
              "width":121,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"596193a34d79404a9fb6d25e4e16676a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":86,
                  "y":313},
                "size":{
                  "width":121,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64ae13dfef5b47d29e7b2f85558b5ad2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":102,
              "y":403},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ccd7a1fa767438c857d9f25bc5d2d21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":102,
                  "y":403},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63b65b1e46a642c1841e406c3800903c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":400},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bddd08d43e343549dd9f35fd117474c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":400},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u22.png"}},
{
          "id":"1cb41b52a87d43e781061dd5d59e83f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":87,
              "y":384},
            "size":{
              "width":130,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e05eff28bcc84948b182203fa3b327d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":87,
                  "y":384},
                "size":{
                  "width":130,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f76978927f434856b8d753bbb72e616d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":144,
              "y":80},
            "size":{
              "width":40,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61987344513e45db8f4edbd8ab15d0ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":80},
                "size":{
                  "width":40,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_3农场主页/u369.png"}},
{
          "id":"54cf630e48af40279dfeb1be0a818c98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":144,
              "y":150},
            "size":{
              "width":40,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2740c812718475595967d9343718ba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":150},
                "size":{
                  "width":40,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_3农场主页/u369.png"}},
{
          "id":"8672625efa904444ade75f3f95f658d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":170,
              "y":366},
            "size":{
              "width":40,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16affac423a14aea83ae8c6edee60b7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":366},
                "size":{
                  "width":40,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_3农场主页/u369.png"}},
{
          "id":"e71d2502f57c49d18a07e065382e0169",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":69},
            "size":{
              "width":360,
              "height":73}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 1.1.3农场主页",
                      "target":{
                        "targetType":"page",
                        "url":"1_1_3农场主页_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"753e86c7f0b045dc953fffe7ee61173e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":141},
            "size":{
              "width":360,
              "height":73}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 1.1.3农场主页",
                      "target":{
                        "targetType":"page",
                        "url":"1_1_3农场主页_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b4c027ffe14149eba7701dc7ae81a538",
          "label":"排序",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":69},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"190e7a5488de43d9bc395a50e845eae2",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"087fcbfd14c64d80977763f82ff28cd8",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":271},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a75e01b049c4ca2bf873659f284f5a8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":271},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/1_7合作农场列表_1/u82.png"}},
{
                  "id":"82b69800d0c943028008d4904da83ab2",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1182c00b1cee4df4ab9a48137cb95fe7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
                  "id":"e68e1ff607ce44538491e5738be5cc0b",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":12},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"61fa031631264b3686405c4ca336f215",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":12},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3a529eed57f049c2a02a1210cd37fa63",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eeed97bcc0e14ae7963e9f24081c9683",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":39},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
                  "id":"d4ed9e6046cd42b096da56e956b02867",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":50},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa2db0ab3ba8403aa4965de1af4c8237",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":50},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5607308cf7c749e085e624e378217b37",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":78},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"908069bc6113441fad970137ff423ea6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":78},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
                  "id":"811a8ce68d4c45949c083fe9cba8d146",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":88},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"46b8cdae3b6f47a7af23e2b0b65cc4a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":88},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"06c26c12e72547619243d347ecc8918a",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":116},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe41def8f1f84739af2c9a6b1978bc04",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":116},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
                  "id":"86096665333d4bd3b6b9d51a49ad98cc",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":128},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"967f97b3ad2d478db27309f0f067446e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":128},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f082b07407cf4a8c9ed215f9ab742b8d",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":154},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"17a1ce44ebdd49fdb85bccab8e817bf4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":154},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
                  "id":"7625b54528ac4e36a6ef2f4b7ed51f72",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":166},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"866993e6b68347b095dbc4f4fba487cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":166},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d3560c257e6549e68a8a27264b52894d",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f34f841c2c194ff0b6435b963b3f9c17",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":192},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
                  "id":"f74c82aded964b3292931abbcde193f7",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":206},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd8dd34e12a5485ba01edfa427972cb5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":206},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"451617c7dd304c309bb04fbd1bd73945",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":232},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"449fd3f5c8f049a79d17692d5eeae3f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":232},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
                  "id":"c76b418897cb4261b32e18601f7693f0",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":244},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f120f90a58844a1bb6da4c1c508c4f30",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":244},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7c0224dee9a1447582dd65a055957dd7",
                  "label":"",
                  "parentDynamicPanel":"b4c027ffe14149eba7701dc7ae81a538",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":271}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 排序",
                              "objectsToFades":[{
                                  "objectPath":["b4c027ffe14149eba7701dc7ae81a538"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"d28a311a412f406c97cb240e623052b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":109.5,
              "y":9.5},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"459bad917fad4959a6d7ae3f2c88af1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":109.5,
                  "y":9.5},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7c12933d0bc24405a612b2201ed1f9d0":{
      "scriptId":"u0"},
    "9b90dc06fd824d4798dead72e9e72137":{
      "scriptId":"u1"},
    "0ef91a4cdc224eaba9cfe12217693195":{
      "scriptId":"u2"},
    "dc16575a55da4f6cb7d57da467815499":{
      "scriptId":"u3"},
    "dd55564beecf473b8178d42989910512":{
      "scriptId":"u4"},
    "d7943030f2614cb6b12f6e5f0c39624d":{
      "scriptId":"u5"},
    "ac9ed8e142b84f8e9f3bbc7020576180":{
      "scriptId":"u6"},
    "655a11ee3c2b4e74a10602d09f2b5ecd":{
      "scriptId":"u7"},
    "6eae458423394eb68721497ac4c55d84":{
      "scriptId":"u8"},
    "947c443719a242d18e6175bd05437383":{
      "scriptId":"u9"},
    "fbb3bd178c4840e7b687e3cc2bf5aeac":{
      "scriptId":"u10"},
    "8a26748c07d84c978e77d1a6796ec710":{
      "scriptId":"u11"},
    "ddf229ecd0b04f15afcfe458b6ea5005":{
      "scriptId":"u12"},
    "2962fb429fe7492e97f2f69e666a43dc":{
      "scriptId":"u13"},
    "31a8be9aa3b0436c8a2e93fbe3615df7":{
      "scriptId":"u14"},
    "a8b74e3b5e5443f6b8cb379f91bf56a1":{
      "scriptId":"u15"},
    "4d709e70599347d4b09878402fc1c31a":{
      "scriptId":"u16"},
    "94397e89a2ea4e63be8113c95175746d":{
      "scriptId":"u17"},
    "f353eb47591e4ad1be9d4802195332de":{
      "scriptId":"u18"},
    "02d99dee21c44246a992d399ec9a591c":{
      "scriptId":"u19"},
    "5109dc365e6248d99ca86abe12895ebc":{
      "scriptId":"u20"},
    "29beb4f2934e4fa9ba3d45b2bc0dcb99":{
      "scriptId":"u21"},
    "f7f4c783dedd45998c60bbc17229da6d":{
      "scriptId":"u22"},
    "8164aef97ff641f0ae7a7e3b65417127":{
      "scriptId":"u23"},
    "2611f7fd13424dd1a57a09a52241b9cc":{
      "scriptId":"u24"},
    "c56451ac208b46e184a80c1ea8b9e81a":{
      "scriptId":"u25"},
    "d69cb5f0a233469c8a6283d6d3509177":{
      "scriptId":"u26"},
    "ef9b75e91503445e8e9422559eda51a5":{
      "scriptId":"u27"},
    "908b77ca6be6441a825b5e2c467ff86d":{
      "scriptId":"u28"},
    "84bb49fa53b44f5f9162612d2e517494":{
      "scriptId":"u29"},
    "0f01838ab81a4c1396b52b3d41a044f7":{
      "scriptId":"u30"},
    "197c9685c43448578df9544f823a5371":{
      "scriptId":"u31"},
    "7e629842ff0c4a4f893cde2172820af8":{
      "scriptId":"u32"},
    "2a21b8e52b1442749b7dee016a469f0e":{
      "scriptId":"u33"},
    "5319938770d2490eb570d0370d1babdc":{
      "scriptId":"u34"},
    "24a6abccc0d64da59064865220625dda":{
      "scriptId":"u35"},
    "12d0a9d53f7e4c61a7039baeb852761f":{
      "scriptId":"u36"},
    "5b1ace2f26bf40239bc9c19305b30b0a":{
      "scriptId":"u37"},
    "8c4d35d8f0f1441f9c734b56a20243ee":{
      "scriptId":"u38"},
    "3f7489f5378d4314a03b14ee151ad72e":{
      "scriptId":"u39"},
    "829d9a2b5ac9449a9418fdcd435577c5":{
      "scriptId":"u40"},
    "440e38e827e7448ab62c48745f7a0c4f":{
      "scriptId":"u41"},
    "0aea0af938764e55a8f52d97bc14e05f":{
      "scriptId":"u42"},
    "cff96f4e7dfc4c1c87aba349c0194ee2":{
      "scriptId":"u43"},
    "709a752bc0aa4c869be81b06d6f2fe24":{
      "scriptId":"u44"},
    "db5a1fb5130f4b7cb500c0343cdcc69f":{
      "scriptId":"u45"},
    "f9443eea60e3425da1dbd51564015492":{
      "scriptId":"u46"},
    "2c3274f667d74012a0d695789885d254":{
      "scriptId":"u47"},
    "41558dd8cccb4074b00e928a1da10831":{
      "scriptId":"u48"},
    "6e25ab7f0a0f486f8a2f19a2b1615134":{
      "scriptId":"u49"},
    "54dcb015977544768ba7f57335ca706f":{
      "scriptId":"u50"},
    "5e0bcc0f5e0c471e88bfaf4a247c4379":{
      "scriptId":"u51"},
    "2186c6ed973a40be965ce73a113c2345":{
      "scriptId":"u52"},
    "6174fe093d6244cdb61af73733e0e10f":{
      "scriptId":"u53"},
    "67e246c198634e39848ab6fbfa4fb2db":{
      "scriptId":"u54"},
    "77a1eedba63443eca79d7d0d811a0ea6":{
      "scriptId":"u55"},
    "80bde6c3393548a58105e8a89ac2e705":{
      "scriptId":"u56"},
    "00b63801550c4de98bb2c7b308c85474":{
      "scriptId":"u57"},
    "b3c4e8a13b36401dba02dac99114446e":{
      "scriptId":"u58"},
    "fbda3903df9744cc9d1edbf60a27e804":{
      "scriptId":"u59"},
    "f27e054d46254f289b216234151c1da1":{
      "scriptId":"u60"},
    "56a32cf70b7f4b0da43037d0ce45181a":{
      "scriptId":"u61"},
    "50035969ccfb49d1a7796f87628e52ea":{
      "scriptId":"u62"},
    "49424cd1e05b42208da55280eb01e0f7":{
      "scriptId":"u63"},
    "dedf8469d6634a0386a3a01e02a2ae4c":{
      "scriptId":"u64"},
    "c46984e462644fed895d0ea6dc92bfd5":{
      "scriptId":"u65"},
    "596193a34d79404a9fb6d25e4e16676a":{
      "scriptId":"u66"},
    "64ae13dfef5b47d29e7b2f85558b5ad2":{
      "scriptId":"u67"},
    "0ccd7a1fa767438c857d9f25bc5d2d21":{
      "scriptId":"u68"},
    "63b65b1e46a642c1841e406c3800903c":{
      "scriptId":"u69"},
    "3bddd08d43e343549dd9f35fd117474c":{
      "scriptId":"u70"},
    "1cb41b52a87d43e781061dd5d59e83f5":{
      "scriptId":"u71"},
    "e05eff28bcc84948b182203fa3b327d2":{
      "scriptId":"u72"},
    "f76978927f434856b8d753bbb72e616d":{
      "scriptId":"u73"},
    "61987344513e45db8f4edbd8ab15d0ff":{
      "scriptId":"u74"},
    "54cf630e48af40279dfeb1be0a818c98":{
      "scriptId":"u75"},
    "a2740c812718475595967d9343718ba8":{
      "scriptId":"u76"},
    "8672625efa904444ade75f3f95f658d7":{
      "scriptId":"u77"},
    "16affac423a14aea83ae8c6edee60b7d":{
      "scriptId":"u78"},
    "e71d2502f57c49d18a07e065382e0169":{
      "scriptId":"u79"},
    "753e86c7f0b045dc953fffe7ee61173e":{
      "scriptId":"u80"},
    "b4c027ffe14149eba7701dc7ae81a538":{
      "scriptId":"u81"},
    "087fcbfd14c64d80977763f82ff28cd8":{
      "scriptId":"u82"},
    "5a75e01b049c4ca2bf873659f284f5a8":{
      "scriptId":"u83"},
    "82b69800d0c943028008d4904da83ab2":{
      "scriptId":"u84"},
    "1182c00b1cee4df4ab9a48137cb95fe7":{
      "scriptId":"u85"},
    "e68e1ff607ce44538491e5738be5cc0b":{
      "scriptId":"u86"},
    "61fa031631264b3686405c4ca336f215":{
      "scriptId":"u87"},
    "3a529eed57f049c2a02a1210cd37fa63":{
      "scriptId":"u88"},
    "eeed97bcc0e14ae7963e9f24081c9683":{
      "scriptId":"u89"},
    "d4ed9e6046cd42b096da56e956b02867":{
      "scriptId":"u90"},
    "aa2db0ab3ba8403aa4965de1af4c8237":{
      "scriptId":"u91"},
    "5607308cf7c749e085e624e378217b37":{
      "scriptId":"u92"},
    "908069bc6113441fad970137ff423ea6":{
      "scriptId":"u93"},
    "811a8ce68d4c45949c083fe9cba8d146":{
      "scriptId":"u94"},
    "46b8cdae3b6f47a7af23e2b0b65cc4a5":{
      "scriptId":"u95"},
    "06c26c12e72547619243d347ecc8918a":{
      "scriptId":"u96"},
    "fe41def8f1f84739af2c9a6b1978bc04":{
      "scriptId":"u97"},
    "86096665333d4bd3b6b9d51a49ad98cc":{
      "scriptId":"u98"},
    "967f97b3ad2d478db27309f0f067446e":{
      "scriptId":"u99"},
    "f082b07407cf4a8c9ed215f9ab742b8d":{
      "scriptId":"u100"},
    "17a1ce44ebdd49fdb85bccab8e817bf4":{
      "scriptId":"u101"},
    "7625b54528ac4e36a6ef2f4b7ed51f72":{
      "scriptId":"u102"},
    "866993e6b68347b095dbc4f4fba487cd":{
      "scriptId":"u103"},
    "d3560c257e6549e68a8a27264b52894d":{
      "scriptId":"u104"},
    "f34f841c2c194ff0b6435b963b3f9c17":{
      "scriptId":"u105"},
    "f74c82aded964b3292931abbcde193f7":{
      "scriptId":"u106"},
    "dd8dd34e12a5485ba01edfa427972cb5":{
      "scriptId":"u107"},
    "451617c7dd304c309bb04fbd1bd73945":{
      "scriptId":"u108"},
    "449fd3f5c8f049a79d17692d5eeae3f5":{
      "scriptId":"u109"},
    "c76b418897cb4261b32e18601f7693f0":{
      "scriptId":"u110"},
    "f120f90a58844a1bb6da4c1c508c4f30":{
      "scriptId":"u111"},
    "7c0224dee9a1447582dd65a055957dd7":{
      "scriptId":"u112"},
    "d28a311a412f406c97cb240e623052b0":{
      "scriptId":"u113"},
    "459bad917fad4959a6d7ae3f2c88af1d":{
      "scriptId":"u114"}}});