$axure.loadCurrentPage({
  "url":"3_2会员保障_1.html",
  "generationDate":new Date(1510229489571.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"a56d04347f284fa29d6d645928c5fa48",
    "type":"Axure:Page",
    "name":"3.2会员保障",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3bc8cf66128d42b9a6a1e7a7d7f4d7f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddfeb3f6f55c427ab5e704979e85dcf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_2会员保障/u0.png"}},
{
          "id":"2e67d07ee1af43ffb5c18e2df476d745",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c12065d86ad849a2bb838de929da844b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
          "id":"e799989fe0b4400cbcfe23cd55d23bd5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cd6b0f9d3044df997490416092a64f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"fa66b8ee73174277a1325ee150d67e1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":144,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c554bf1ba6c74f9fa696181e94ad4cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":144,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"210314dd73d5492488462e6a9797f86e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":620},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5b4f011e26044b16a79be62886de5d55",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"996a2696b0d44356b4c4be5aedbe123e",
                  "label":"",
                  "parentDynamicPanel":"210314dd73d5492488462e6a9797f86e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b8fd8d8ce184815af9fe4aa9b82a18c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"210314dd73d5492488462e6a9797f86e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 3.0会员充值",
                              "target":{
                                "targetType":"page",
                                "url":"3_0会员充值_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}}]}]},
{
          "id":"c0b5dd23a2304b05adbaf878c59dc420",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":360,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09b5f73ef4d43bc9392287e0ed7cb34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":360,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_2会员保障/u11.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3bc8cf66128d42b9a6a1e7a7d7f4d7f6":{
      "scriptId":"u0"},
    "ddfeb3f6f55c427ab5e704979e85dcf8":{
      "scriptId":"u1"},
    "2e67d07ee1af43ffb5c18e2df476d745":{
      "scriptId":"u2"},
    "c12065d86ad849a2bb838de929da844b":{
      "scriptId":"u3"},
    "e799989fe0b4400cbcfe23cd55d23bd5":{
      "scriptId":"u4"},
    "8cd6b0f9d3044df997490416092a64f3":{
      "scriptId":"u5"},
    "fa66b8ee73174277a1325ee150d67e1b":{
      "scriptId":"u6"},
    "c554bf1ba6c74f9fa696181e94ad4cf8":{
      "scriptId":"u7"},
    "210314dd73d5492488462e6a9797f86e":{
      "scriptId":"u8"},
    "996a2696b0d44356b4c4be5aedbe123e":{
      "scriptId":"u9"},
    "8b8fd8d8ce184815af9fe4aa9b82a18c":{
      "scriptId":"u10"},
    "c0b5dd23a2304b05adbaf878c59dc420":{
      "scriptId":"u11"},
    "d09b5f73ef4d43bc9392287e0ed7cb34":{
      "scriptId":"u12"}}});