$axure.loadCurrentPage({
  "url":"小轮播.html",
  "generationDate":new Date(1505293723112.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"202c3c5ac9fd4da6bd1c561758315aac",
    "type":"Axure:Page",
    "name":"小轮播",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5b22112a07c9431e853d410e476e6a60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":790}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4f12348a5a4755ad2d3ab165236d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":790}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u0.png"}},
{
          "id":"c9352d30998f480399d9a1df1af63aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e16382e59d4ec2af48f96a78601490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/top_u46.png"}},
{
          "id":"872640187cde461995c12c3310c50370",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f264fdd782a640e8a051e29c9e1b4538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u107.png"}},
{
          "id":"5d461c2f6d804383a230526066d1af49",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":133,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f07622d5d71432b9a6ed0a168a2cbaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":133,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7b118934fe14d9ab5239efbce7d0154",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":7},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9fe1291e9a1400b8c33ba0fe50605e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":7},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u23.png"}},
{
          "id":"1095b6aaa09a4e79b08c8cb1c8292c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":17},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc96eba7b7e6441bae995261472d00ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":17},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u23.png"}},
{
          "id":"c46432eebce64b69a48af648b4a0350e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":27},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ba490fe420e48898793bda2c8daa956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":27},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u23.png"}},
{
          "id":"851e42ba5cfc4b229c75b3321f254661",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":750},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"8e08f5f866964bc5b09ab7656e4d0c36",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"59b867ddcf7849638ec7ceb9e85c22c1",
                  "label":"",
                  "parentDynamicPanel":"851e42ba5cfc4b229c75b3321f254661",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "masterId":"9c8d789cd9ea4344a50ed483251cd481"}]}]},
{
          "id":"3bb474fe2331494f98676f533bf96f8b",
          "label":"套餐轮播",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":360,
              "height":100}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 拖到面板 x 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["367a21ae084047a795f4e26d2cd3d10e"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"92e316ad0e79440784c1994f21daf4aa",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ac7348986c3a40bd97780498025052a3",
                  "label":"",
                  "parentDynamicPanel":"3bb474fe2331494f98676f533bf96f8b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f2ac270c740456d94b0c4681f68e3d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3bb474fe2331494f98676f533bf96f8b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/蔬果订单详情/u14.png"}},
{
                  "id":"367a21ae084047a795f4e26d2cd3d10e",
                  "label":"拖到面板",
                  "parentDynamicPanel":"3bb474fe2331494f98676f533bf96f8b",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1070,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"c46af14c35b74b4fb3542e6afc75f941",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"5c158335eaae49bd9a7d7f37013f902a",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":120,
                              "y":10},
                            "size":{
                              "width":100,
                              "height":80},
                            "cornerRadiusTopLeft":"5"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"db577534b4364e9b8a4ef0088442c700",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":120,
                                  "y":10},
                                "size":{
                                  "width":100,
                                  "height":80},
                                "cornerRadiusTopLeft":"5"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/小轮播/u42.png"}},
{
                          "id":"9954c7e3ef864486b95bea4234fc4e8c",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "location":{
                              "x":130,
                              "y":16},
                            "size":{
                              "width":62,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"65d8f26b3c30480e83c9ccf034d4ee3f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "location":{
                                  "x":130,
                                  "y":16},
                                "size":{
                                  "width":62,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"e4012f67a7fe483993aa2dd28c867af1",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":240,
                              "y":10},
                            "size":{
                              "width":100,
                              "height":80},
                            "cornerRadiusTopLeft":"5"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"163d19486efb47a3be29a2ec622b77a9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":240,
                                  "y":10},
                                "size":{
                                  "width":100,
                                  "height":80},
                                "cornerRadiusTopLeft":"5"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/小轮播/u42.png"}},
{
                          "id":"4d283a529ae54ab8b9d193ec6d3f5d2e",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "location":{
                              "x":250,
                              "y":16},
                            "size":{
                              "width":61,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"59c183a0babc4ebcb28af6a2f5946ba3",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "location":{
                                  "x":250,
                                  "y":16},
                                "size":{
                                  "width":61,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"460bf0e19c6d4999ac3110da6f4b229d",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":360,
                              "y":10},
                            "size":{
                              "width":100,
                              "height":80},
                            "cornerRadiusTopLeft":"5"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"72f7bf06556f4d0488e92d9f91f37318",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":360,
                                  "y":10},
                                "size":{
                                  "width":100,
                                  "height":80},
                                "cornerRadiusTopLeft":"5"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/小轮播/u42.png"}},
{
                          "id":"ecd7751e186d4b1e929460077ed57534",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "location":{
                              "x":370,
                              "y":16},
                            "size":{
                              "width":62,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"288aac31dffd415f8a74fcad0f6bf3fd",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "location":{
                                  "x":370,
                                  "y":16},
                                "size":{
                                  "width":62,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"129f81d868f743b38333f55463279208",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":480,
                              "y":10},
                            "size":{
                              "width":100,
                              "height":80},
                            "cornerRadiusTopLeft":"5"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1e2ade77bcf2437ea4dc5cd98fd9b9c9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":480,
                                  "y":10},
                                "size":{
                                  "width":100,
                                  "height":80},
                                "cornerRadiusTopLeft":"5"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/小轮播/u42.png"}},
{
                          "id":"878a06323964404196e0e84fd99f70d4",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "location":{
                              "x":490,
                              "y":16},
                            "size":{
                              "width":61,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f3c018f5fa0e4ea2b041cf2992dbdf9d",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "location":{
                                  "x":490,
                                  "y":16},
                                "size":{
                                  "width":61,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"91d80e60fcec49e68085b7e950194ccd",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":600,
                              "y":10},
                            "size":{
                              "width":100,
                              "height":80},
                            "cornerRadiusTopLeft":"5"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"65dc7a8ee9f14bae9ff8dde5194a96f4",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":600,
                                  "y":10},
                                "size":{
                                  "width":100,
                                  "height":80},
                                "cornerRadiusTopLeft":"5"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/小轮播/u42.png"}},
{
                          "id":"aa30a3a811194394be070aebcb542a51",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "location":{
                              "x":610,
                              "y":16},
                            "size":{
                              "width":75,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"11ec7b626414426bb45354589a12e65d",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "location":{
                                  "x":610,
                                  "y":16},
                                "size":{
                                  "width":75,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"3175b50ec10c48508adca51cbb73ac4c",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"11px",
                            "location":{
                              "x":130,
                              "y":45},
                            "size":{
                              "width":80,
                              "height":35}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"e9a9e5a909944aed9c523fe28e17458f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"11px",
                                "location":{
                                  "x":130,
                                  "y":45},
                                "size":{
                                  "width":80,
                                  "height":35}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"5a3301a3c97748f683227093429597ed",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"11px",
                            "location":{
                              "x":250,
                              "y":45},
                            "size":{
                              "width":80,
                              "height":35}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7b5448252284477eae729c6443c69edd",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"11px",
                                "location":{
                                  "x":250,
                                  "y":45},
                                "size":{
                                  "width":80,
                                  "height":35}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"6e2407b1270440738edc35acfd9f7ed6",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"11px",
                            "location":{
                              "x":370,
                              "y":45},
                            "size":{
                              "width":80,
                              "height":35}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"dbcefdcfcc8c437890c1d555d393835c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"11px",
                                "location":{
                                  "x":370,
                                  "y":45},
                                "size":{
                                  "width":80,
                                  "height":35}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"f4a26c66b7c841aca5622c25fc70029a",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"11px",
                            "location":{
                              "x":490,
                              "y":45},
                            "size":{
                              "width":80,
                              "height":35}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d5aed520f7884ff09c79299ae336ae00",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"11px",
                                "location":{
                                  "x":490,
                                  "y":45},
                                "size":{
                                  "width":80,
                                  "height":35}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"62055a507d3f45eab0406040ad1e08b9",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"11px",
                            "location":{
                              "x":610,
                              "y":45},
                            "size":{
                              "width":80,
                              "height":35}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"16f84fa4e4bf409c981649bf7d956d15",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"11px",
                                "location":{
                                  "x":610,
                                  "y":45},
                                "size":{
                                  "width":80,
                                  "height":35}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"72ed3d8a20c04c368287fff68dea84a1",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":720,
                              "y":10},
                            "size":{
                              "width":100,
                              "height":80},
                            "cornerRadiusTopLeft":"5"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"742acaf17431428481104f3acafa3421",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":720,
                                  "y":10},
                                "size":{
                                  "width":100,
                                  "height":80},
                                "cornerRadiusTopLeft":"5"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/小轮播/u42.png"}},
{
                          "id":"04e4ff3aa29a47ef8482dc52c847eaf7",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "location":{
                              "x":730,
                              "y":16},
                            "size":{
                              "width":74,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"e13abde771324f28b2a92b92b308e90c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "location":{
                                  "x":730,
                                  "y":16},
                                "size":{
                                  "width":74,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"9579e84498ba4ffd83df6a099f0ec48c",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"11px",
                            "location":{
                              "x":730,
                              "y":45},
                            "size":{
                              "width":80,
                              "height":35}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0ccb02a7b7c440dab2a83aebcff1bde4",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"11px",
                                "location":{
                                  "x":730,
                                  "y":45},
                                "size":{
                                  "width":80,
                                  "height":35}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"b5f313bcb06a43dc87048e57f050323c",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":840,
                              "y":10},
                            "size":{
                              "width":100,
                              "height":80},
                            "cornerRadiusTopLeft":"5"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"2816fd5db0314e1f85e02d55b50960eb",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":840,
                                  "y":10},
                                "size":{
                                  "width":100,
                                  "height":80},
                                "cornerRadiusTopLeft":"5"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/小轮播/u42.png"}},
{
                          "id":"c59dab51f02142738e702334a136b618",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "location":{
                              "x":850,
                              "y":16},
                            "size":{
                              "width":62,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0dfdb593d55541a697f6a21cf65e593c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "location":{
                                  "x":850,
                                  "y":16},
                                "size":{
                                  "width":62,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"236c06e499cf4d349b02ee6d1aaeb136",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"11px",
                            "location":{
                              "x":850,
                              "y":45},
                            "size":{
                              "width":80,
                              "height":35}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1dc682f9ee6643a38b39359e6f5231a1",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"11px",
                                "location":{
                                  "x":850,
                                  "y":45},
                                "size":{
                                  "width":80,
                                  "height":35}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"d391add23f714e3bbda81dd7fb65ac2a",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":960,
                              "y":10},
                            "size":{
                              "width":100,
                              "height":80},
                            "cornerRadiusTopLeft":"5"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f79f00db25ca49eda0183cb7e89374d9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":960,
                                  "y":10},
                                "size":{
                                  "width":100,
                                  "height":80},
                                "cornerRadiusTopLeft":"5"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/小轮播/u42.png"}},
{
                          "id":"691bae1617c6465098ddfe01aac8eee6",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "location":{
                              "x":970,
                              "y":16},
                            "size":{
                              "width":61,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5617080c471a4badaa2b28ffc9df23f4",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "location":{
                                  "x":970,
                                  "y":16},
                                "size":{
                                  "width":61,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"594ea7ba20484d23a51fd10d1c383216",
                          "label":"",
                          "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"11px",
                            "location":{
                              "x":970,
                              "y":45},
                            "size":{
                              "width":80,
                              "height":35}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"77bb686ae0d64f4d8483c50340d74a92",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"367a21ae084047a795f4e26d2cd3d10e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"11px",
                                "location":{
                                  "x":970,
                                  "y":45},
                                "size":{
                                  "width":80,
                                  "height":35}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]}]}]}]}},
  "masters":{
    "9c8d789cd9ea4344a50ed483251cd481":{
      "packageId":"9c8d789cd9ea4344a50ed483251cd481",
      "type":"Axure:Master",
      "name":"底部菜单_1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"87500d8b8b844c309601540b4619d68c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":360,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"08515cc118c040c3999f325ab93566f2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":360,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页2/top_u46.png"}},
{
            "id":"506791ca29ed45d4a2ce7c6554b086f0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":44,
                "y":24},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2095c2f0c9424993952f697a18668ec6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":44,
                    "y":24},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/农场列表_1/u89.png"}},
{
            "id":"3df70097703244faa1527a5a494c8c42",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":210,
                "y":24},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f7f494690f7647dba3345b464317963a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":210,
                    "y":24},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/农场列表_1/u89.png"}},
{
            "id":"042cb23104d742f2ae2b63e077e1712d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":121,
                "y":25},
              "size":{
                "width":41,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a93b06fed9a846fcbebd845a157d74d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":121,
                    "y":25},
                  "size":{
                    "width":41,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/农场列表_1/u93.png"}},
{
            "id":"7059bc5e155a401bac0768cc3d613ce5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":281,
                "y":24},
              "size":{
                "width":41,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7a87c87752f49fba0d0cb8e99c88f4a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":281,
                    "y":24},
                  "size":{
                    "width":41,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/农场列表_1/u93.png"}},
{
            "id":"6c17287b2bc14f99a5db67d039fd7863",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":44,
                "y":4},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e044ebdec77c42309e4dc2a65b371385",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":44,
                    "y":4},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页2/u75.png"}},
{
            "id":"8ea57a5b3f8e48fb8d26368b9cd9484c",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":18,
                "y":0},
              "size":{
                "width":73,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页(安卓)",
                        "target":{
                          "targetType":"page",
                          "url":"主页_安卓_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"37d725101ff24d929d72070bb2e0c4d1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":131,
                "y":5},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf130d31e6be4d1cba8c1f0493a96875",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":131,
                    "y":5},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/会员主页_安卓_/u191.png"}},
{
            "id":"6b19b755d2b64fe283aaa9ac475df667",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":210,
                "y":4},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1759e02ed4374bd09389c79665947a6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":210,
                    "y":4},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/农场列表_1/u102.png"}},
{
            "id":"03ed968a08da4a80bd7495c1bb6340a9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":291.5,
                "y":4},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9067e01d94e48d0adc2237491b1d6a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":291.5,
                    "y":4},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页2/u77.png"}},
{
            "id":"947fc150c84545bc959a65c3c98bf4d6",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":0},
              "size":{
                "width":60,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 商品列表",
                        "target":{
                          "targetType":"page",
                          "url":"商品列表_1.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"a2e97db8dcda4a3aac93c1c9b8657f23",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":113,
                "y":2},
              "size":{
                "width":57,
                "height":37}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 体验路线列表",
                        "target":{
                          "targetType":"page",
                          "url":"体验路线列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9c7a13d46795479c92f0dc37c386aec1",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":272,
                "y":0},
              "size":{
                "width":60,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心主页",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心主页_1.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "5b22112a07c9431e853d410e476e6a60":{
      "scriptId":"u0"},
    "6c4f12348a5a4755ad2d3ab165236d46":{
      "scriptId":"u1"},
    "c9352d30998f480399d9a1df1af63aa1":{
      "scriptId":"u2"},
    "43e16382e59d4ec2af48f96a78601490":{
      "scriptId":"u3"},
    "872640187cde461995c12c3310c50370":{
      "scriptId":"u4"},
    "f264fdd782a640e8a051e29c9e1b4538":{
      "scriptId":"u5"},
    "5d461c2f6d804383a230526066d1af49":{
      "scriptId":"u6"},
    "7f07622d5d71432b9a6ed0a168a2cbaa":{
      "scriptId":"u7"},
    "b7b118934fe14d9ab5239efbce7d0154":{
      "scriptId":"u8"},
    "e9fe1291e9a1400b8c33ba0fe50605e6":{
      "scriptId":"u9"},
    "1095b6aaa09a4e79b08c8cb1c8292c95":{
      "scriptId":"u10"},
    "bc96eba7b7e6441bae995261472d00ce":{
      "scriptId":"u11"},
    "c46432eebce64b69a48af648b4a0350e":{
      "scriptId":"u12"},
    "3ba490fe420e48898793bda2c8daa956":{
      "scriptId":"u13"},
    "851e42ba5cfc4b229c75b3321f254661":{
      "scriptId":"u14"},
    "59b867ddcf7849638ec7ceb9e85c22c1":{
      "scriptId":"u15",
      "87500d8b8b844c309601540b4619d68c":{
        "scriptId":"u16"},
      "08515cc118c040c3999f325ab93566f2":{
        "scriptId":"u17"},
      "506791ca29ed45d4a2ce7c6554b086f0":{
        "scriptId":"u18"},
      "2095c2f0c9424993952f697a18668ec6":{
        "scriptId":"u19"},
      "3df70097703244faa1527a5a494c8c42":{
        "scriptId":"u20"},
      "f7f494690f7647dba3345b464317963a":{
        "scriptId":"u21"},
      "042cb23104d742f2ae2b63e077e1712d":{
        "scriptId":"u22"},
      "a93b06fed9a846fcbebd845a157d74d3":{
        "scriptId":"u23"},
      "7059bc5e155a401bac0768cc3d613ce5":{
        "scriptId":"u24"},
      "c7a87c87752f49fba0d0cb8e99c88f4a":{
        "scriptId":"u25"},
      "6c17287b2bc14f99a5db67d039fd7863":{
        "scriptId":"u26"},
      "e044ebdec77c42309e4dc2a65b371385":{
        "scriptId":"u27"},
      "8ea57a5b3f8e48fb8d26368b9cd9484c":{
        "scriptId":"u28"},
      "37d725101ff24d929d72070bb2e0c4d1":{
        "scriptId":"u29"},
      "cf130d31e6be4d1cba8c1f0493a96875":{
        "scriptId":"u30"},
      "6b19b755d2b64fe283aaa9ac475df667":{
        "scriptId":"u31"},
      "1759e02ed4374bd09389c79665947a6b":{
        "scriptId":"u32"},
      "03ed968a08da4a80bd7495c1bb6340a9":{
        "scriptId":"u33"},
      "d9067e01d94e48d0adc2237491b1d6a5":{
        "scriptId":"u34"},
      "947fc150c84545bc959a65c3c98bf4d6":{
        "scriptId":"u35"},
      "a2e97db8dcda4a3aac93c1c9b8657f23":{
        "scriptId":"u36"},
      "9c7a13d46795479c92f0dc37c386aec1":{
        "scriptId":"u37"}},
    "3bb474fe2331494f98676f533bf96f8b":{
      "scriptId":"u38"},
    "ac7348986c3a40bd97780498025052a3":{
      "scriptId":"u39"},
    "2f2ac270c740456d94b0c4681f68e3d3":{
      "scriptId":"u40"},
    "367a21ae084047a795f4e26d2cd3d10e":{
      "scriptId":"u41"},
    "5c158335eaae49bd9a7d7f37013f902a":{
      "scriptId":"u42"},
    "db577534b4364e9b8a4ef0088442c700":{
      "scriptId":"u43"},
    "9954c7e3ef864486b95bea4234fc4e8c":{
      "scriptId":"u44"},
    "65d8f26b3c30480e83c9ccf034d4ee3f":{
      "scriptId":"u45"},
    "e4012f67a7fe483993aa2dd28c867af1":{
      "scriptId":"u46"},
    "163d19486efb47a3be29a2ec622b77a9":{
      "scriptId":"u47"},
    "4d283a529ae54ab8b9d193ec6d3f5d2e":{
      "scriptId":"u48"},
    "59c183a0babc4ebcb28af6a2f5946ba3":{
      "scriptId":"u49"},
    "460bf0e19c6d4999ac3110da6f4b229d":{
      "scriptId":"u50"},
    "72f7bf06556f4d0488e92d9f91f37318":{
      "scriptId":"u51"},
    "ecd7751e186d4b1e929460077ed57534":{
      "scriptId":"u52"},
    "288aac31dffd415f8a74fcad0f6bf3fd":{
      "scriptId":"u53"},
    "129f81d868f743b38333f55463279208":{
      "scriptId":"u54"},
    "1e2ade77bcf2437ea4dc5cd98fd9b9c9":{
      "scriptId":"u55"},
    "878a06323964404196e0e84fd99f70d4":{
      "scriptId":"u56"},
    "f3c018f5fa0e4ea2b041cf2992dbdf9d":{
      "scriptId":"u57"},
    "91d80e60fcec49e68085b7e950194ccd":{
      "scriptId":"u58"},
    "65dc7a8ee9f14bae9ff8dde5194a96f4":{
      "scriptId":"u59"},
    "aa30a3a811194394be070aebcb542a51":{
      "scriptId":"u60"},
    "11ec7b626414426bb45354589a12e65d":{
      "scriptId":"u61"},
    "3175b50ec10c48508adca51cbb73ac4c":{
      "scriptId":"u62"},
    "e9a9e5a909944aed9c523fe28e17458f":{
      "scriptId":"u63"},
    "5a3301a3c97748f683227093429597ed":{
      "scriptId":"u64"},
    "7b5448252284477eae729c6443c69edd":{
      "scriptId":"u65"},
    "6e2407b1270440738edc35acfd9f7ed6":{
      "scriptId":"u66"},
    "dbcefdcfcc8c437890c1d555d393835c":{
      "scriptId":"u67"},
    "f4a26c66b7c841aca5622c25fc70029a":{
      "scriptId":"u68"},
    "d5aed520f7884ff09c79299ae336ae00":{
      "scriptId":"u69"},
    "62055a507d3f45eab0406040ad1e08b9":{
      "scriptId":"u70"},
    "16f84fa4e4bf409c981649bf7d956d15":{
      "scriptId":"u71"},
    "72ed3d8a20c04c368287fff68dea84a1":{
      "scriptId":"u72"},
    "742acaf17431428481104f3acafa3421":{
      "scriptId":"u73"},
    "04e4ff3aa29a47ef8482dc52c847eaf7":{
      "scriptId":"u74"},
    "e13abde771324f28b2a92b92b308e90c":{
      "scriptId":"u75"},
    "9579e84498ba4ffd83df6a099f0ec48c":{
      "scriptId":"u76"},
    "0ccb02a7b7c440dab2a83aebcff1bde4":{
      "scriptId":"u77"},
    "b5f313bcb06a43dc87048e57f050323c":{
      "scriptId":"u78"},
    "2816fd5db0314e1f85e02d55b50960eb":{
      "scriptId":"u79"},
    "c59dab51f02142738e702334a136b618":{
      "scriptId":"u80"},
    "0dfdb593d55541a697f6a21cf65e593c":{
      "scriptId":"u81"},
    "236c06e499cf4d349b02ee6d1aaeb136":{
      "scriptId":"u82"},
    "1dc682f9ee6643a38b39359e6f5231a1":{
      "scriptId":"u83"},
    "d391add23f714e3bbda81dd7fb65ac2a":{
      "scriptId":"u84"},
    "f79f00db25ca49eda0183cb7e89374d9":{
      "scriptId":"u85"},
    "691bae1617c6465098ddfe01aac8eee6":{
      "scriptId":"u86"},
    "5617080c471a4badaa2b28ffc9df23f4":{
      "scriptId":"u87"},
    "594ea7ba20484d23a51fd10d1c383216":{
      "scriptId":"u88"},
    "77bb686ae0d64f4d8483c50340d74a92":{
      "scriptId":"u89"}}});