$axure.loadCurrentPage({
  "url":"农旅订单状态流程图_1.html",
  "generationDate":new Date(1513847490383.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"c1140ad755554adaa204ba44cef8fe1e",
    "type":"Axure:Page",
    "name":"农旅订单状态流程图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e6029deeca464c67b20014c7664a6168",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":29},
            "size":{
              "width":783,
              "height":311}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9afd6c88292f4654bddd745e08b23c93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":29},
                "size":{
                  "width":783,
                  "height":311}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅订单状态流程图_1/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "e6029deeca464c67b20014c7664a6168":{
      "scriptId":"u0"},
    "9afd6c88292f4654bddd745e08b23c93":{
      "scriptId":"u1"}}});