$axure.loadCurrentPage({
  "url":"2_4_1_实名认证.html",
  "generationDate":new Date(1510229478832.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"2413f65a95234b808524c2fae55f4ee9",
    "type":"Axure:Page",
    "name":"2.4.1 实名认证",
    "notes":{
      "默认":"<p><span>1107更新：</span></p><p><span>1.新增增加实名认证按钮</span></p><p><span>2.提交实名认证资料后，在审核期间，实名认证按钮里面的文字变成“实名认证审核中”，并按钮色变为灰色。</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"33fa3b79e725468d863bdc1f61488352",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":684}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82392e191b3647c58cc208909b2ebb5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":684}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u0.png"}},
{
          "id":"fd5e4998aff8457caf749296a1d21bee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89d5a4680ec7484394155e5e21407da6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u2.png"}},
{
          "id":"199cf5432b0e4723a08edcb0c3abf599",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9fc9ab7f6bf4d4da2e47fe15ec9181f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"e9badd81215044e1921cba99800583e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":134,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccd53a34bc714e67996c2f565a66f4cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":134,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c872a46b34045b380fbb16da73a2b8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-9.5,
              "y":50},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"071e6802605645eb8bd28c2e8c0cc97a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-9.5,
                  "y":50},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
          "id":"83f808eae28344d3abae94ea812c9b86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-9.5,
              "y":89},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6761a97ec6b74ad5a60a03fa38a9d1e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-9.5,
                  "y":89},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_1_1确认订单（现场）/u2.png"}},
{
          "id":"25f875e6863b4823a04a630d6ece200d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":64},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cabab145e783444b8b461690f1118221",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":64},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa80222a862049e0b66715985fa0cf51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":100},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"734d71fa24f04736846ecdc55faef469",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":100},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8046b07c9bcc43cb811a93a728e32dbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":7.5,
              "y":139},
            "size":{
              "width":333,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"190b3ec33d4e420d9c5166a795f029fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7.5,
                  "y":139},
                "size":{
                  "width":333,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.4个人资料",
                      "target":{
                        "targetType":"page",
                        "url":"2_4个人资料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_4个人资料/u28.png"}},
{
          "id":"cd3394316dd3467397c06d767ae73dbf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":70.5,
              "y":57},
            "size":{
              "width":270,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"726fe352fd1c414a91b156772fb9cec1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":70.5,
              "y":96},
            "size":{
              "width":270,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "33fa3b79e725468d863bdc1f61488352":{
      "scriptId":"u0"},
    "82392e191b3647c58cc208909b2ebb5f":{
      "scriptId":"u1"},
    "fd5e4998aff8457caf749296a1d21bee":{
      "scriptId":"u2"},
    "89d5a4680ec7484394155e5e21407da6":{
      "scriptId":"u3"},
    "199cf5432b0e4723a08edcb0c3abf599":{
      "scriptId":"u4"},
    "d9fc9ab7f6bf4d4da2e47fe15ec9181f":{
      "scriptId":"u5"},
    "e9badd81215044e1921cba99800583e6":{
      "scriptId":"u6"},
    "ccd53a34bc714e67996c2f565a66f4cd":{
      "scriptId":"u7"},
    "7c872a46b34045b380fbb16da73a2b8b":{
      "scriptId":"u8"},
    "071e6802605645eb8bd28c2e8c0cc97a":{
      "scriptId":"u9"},
    "83f808eae28344d3abae94ea812c9b86":{
      "scriptId":"u10"},
    "6761a97ec6b74ad5a60a03fa38a9d1e7":{
      "scriptId":"u11"},
    "25f875e6863b4823a04a630d6ece200d":{
      "scriptId":"u12"},
    "cabab145e783444b8b461690f1118221":{
      "scriptId":"u13"},
    "aa80222a862049e0b66715985fa0cf51":{
      "scriptId":"u14"},
    "734d71fa24f04736846ecdc55faef469":{
      "scriptId":"u15"},
    "8046b07c9bcc43cb811a93a728e32dbd":{
      "scriptId":"u16"},
    "190b3ec33d4e420d9c5166a795f029fd":{
      "scriptId":"u17"},
    "cd3394316dd3467397c06d767ae73dbf":{
      "scriptId":"u18"},
    "726fe352fd1c414a91b156772fb9cec1":{
      "scriptId":"u19"}}});