$axure.loadCurrentPage({
  "url":"选择城市_3.html",
  "generationDate":new Date(1505201780126.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"6b11e14cc9174fd3ab35c2baca9e72b1",
    "type":"Axure:Page",
    "name":"选择城市",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5536c31a292a41d8bfdd80f7fcc5d1af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":359,
              "height":820},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c411e2cc49f4e9ca37a1cdf09b95de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":359,
                  "height":820},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u0.png"}},
{
          "id":"0f17684f7e1b486b9ff015d56664c569",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":359,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05e332e3c3274a588701f280a73bf3d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":359,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u2.png"}},
{
          "id":"d4d8cb00187f41b5b763d9c25aa65c14",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b793fc32a0e47189a57b4ac66f90d22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u107.png"}},
{
          "id":"91c266d9631b44ff8e81f8488640e4d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":60,
              "y":7},
            "size":{
              "width":288,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"636ef4e75b4f40eaa92149dcbeeb0155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":60,
                  "y":7},
                "size":{
                  "width":288,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u6.png"}},
{
          "id":"86e978164ae944b4bfe3b4c14024ac01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":93,
              "y":12},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84696916c87848f3a5a78a7c1dc35e8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":12},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"445caa48a6d7484a923ffa65b82ad750",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":9.5},
            "size":{
              "width":18,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d21e2e4aa924c9c8d2a64ce4093f421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":9.5},
                "size":{
                  "width":18,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u56.png"}},
{
          "id":"2042734c6674459b9f98a4c96068aa73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":51},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29f3070cccca4e5d96374116332fbc1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":51},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1084f52cc224bc48503becd511d0844",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13469af061c24b1f976fa6ae1d8c138e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"0a40cce374d040b69e86b6ceab87c5af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":82},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"295bd69f94a1401f9035d1bb1e20f23e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":82},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ff382b47a754aefac1d93e6c6f35693",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":120},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"781c991eacca4f4e93f76e90510e5419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":120},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76ac1f6630754e32a2696aeb2b082be3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":139},
            "size":{
              "width":360,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b597d6831c4127bdd90383bf862548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":139},
                "size":{
                  "width":360,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u20.png"}},
{
          "id":"f8070f2a16034266a28fc5d22a602c1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c9d2cb51f55479cb55c2bea6f8458e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":150},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u22.png"}},
{
          "id":"dde262f3cff24bf581db134334e26b29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":150},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e26b376912c543dd8d844d6a2bee2ac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":150},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u22.png"}},
{
          "id":"3d165de89eca462db432cc282a7b20e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":150},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93ec4d4b04984cc9a92d6c0ba8301360",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":150},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u22.png"}},
{
          "id":"27113612022c4ae993c0cb0972fe28e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":150},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"762f999d16574d3db67783edacf04f84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":150},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u22.png"}},
{
          "id":"b9a7c43cf0eb45469ef758dfbeb5d924",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":190},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e08f26fcb9134694b2ed0054763a17de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":190},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u22.png"}},
{
          "id":"f8d8fe88da744e6fa8de0030c38b58bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":190},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56c78b2fa26c471e927b01e60dbdb42f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":190},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u22.png"}},
{
          "id":"fa840db30c63449a861a289ebbf5572d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":190},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b63b30701be4337b59c6a6535425602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":190},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u22.png"}},
{
          "id":"aefd81254550452dbba8b2cd73586e7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":190},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea7edee8e7274f8fbd4dfcc97bb7f281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":190},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择城市/u22.png"}},
{
          "id":"e9397e7de016435ba0e01d82723c6eb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":244},
            "size":{
              "width":9,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"414f1156852c45a2b9ecf7571c20ba48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":244},
                "size":{
                  "width":9,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0d5dbf960394d658e239e80f8857989",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":263},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45fbc244d20a4cdf97e92a8e8032b0d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":263},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"10c7f819d59046c4900bc145bbd5a631",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":275},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c06076a6b16848b68882b9cdb7d49212",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":275},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"462c753c635a492e8811a3a21b2b29df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":313},
            "size":{
              "width":11,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d6386c28d764cccb6f7042c32430fe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":313},
                "size":{
                  "width":11,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"557d65bc65b04698a759fbe57f6b71ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":332},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dc8b3571e364b3db14c39ba34f1bcc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":332},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"80e4051c15b94067a48e61d46367938c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":344},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b36f5f7779b342bd8228d7afa3fcdfc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":344},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26da94a605724fd5b7dd13095909d552",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":382},
            "size":{
              "width":10,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f24ff2f5a6044d78f2bac2ad0788f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":382},
                "size":{
                  "width":10,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acdab9fa78ac44fb86867e8ac6ecaaa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":401},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"530124deffa74b4680c0e16bca21f9e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":401},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"75c135eb1f9c462b94be2b71a758f74a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":413},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e30850bde364468e8c018f31989f02d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":413},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"442b6f0c66934b5f85ef6f4723ab4133",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":451},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d687c39e43924929bd8d524b13d7a45a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":451},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd5226fda3d44c978eef1b459af80f1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":470},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d8fe6b3ec694f32a2390ccca42a3e06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":470},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"0c9deb66a2cc4f878036c98f26a04f8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":482},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d10a52dff64b462cbba19a690ef876c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":482},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44269b188ddd47e1be8fa432c0bbb9fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":520},
            "size":{
              "width":11,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4ade9f977d3466786ef2c56a24f5020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":520},
                "size":{
                  "width":11,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afc90c106ce242f3beec10e82b6a3513",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":539},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"188655dc917d491c861a528d70f161e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":539},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"973b3a42f6054f4e8b9476bb4a8fe36c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":551},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a10669446d6348fb8c33f11724afd32b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":551},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40497973f5224c2bbe9cdaeccd5ea5c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":589},
            "size":{
              "width":10,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"873e4ca05a1e4b998576939d492d3041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":589},
                "size":{
                  "width":10,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2a28e875e69426a88d62922c3e24f11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":608},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac34ecc4b0a247638716f52cab3daf84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":608},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"0f48493c88de4cd48138e5cdd507a5a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":620},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"866949df41f04bc2bd8aec9a7999f8d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":620},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3591ae1d02b4416592d224a9963fe198",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":10,
              "y":658},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b57ce57c5443fcb5283f174903c478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":10,
                  "y":658},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d66a68e5ad4843a2aaf71c7ae88b6f7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":677},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"815f8b67f1c948628ca4e1dd6c214b8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":677},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"87c6ca79db3243228fe52a9c486b2d65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":689},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52729744116d4420910bb5ca2f0004bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":689},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f40ff5f47b8b4f05a44dee49c4a97021",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":717},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75eadbb8364649c0bf8d6106f5b5ad81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":717},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"a9785711b2894a9bbac6f11ae50a3df6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":729},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac22d5613c4a4ab09b4ec514ce3f7348",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":729},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5536c31a292a41d8bfdd80f7fcc5d1af":{
      "scriptId":"u0"},
    "4c411e2cc49f4e9ca37a1cdf09b95de9":{
      "scriptId":"u1"},
    "0f17684f7e1b486b9ff015d56664c569":{
      "scriptId":"u2"},
    "05e332e3c3274a588701f280a73bf3d0":{
      "scriptId":"u3"},
    "d4d8cb00187f41b5b763d9c25aa65c14":{
      "scriptId":"u4"},
    "5b793fc32a0e47189a57b4ac66f90d22":{
      "scriptId":"u5"},
    "91c266d9631b44ff8e81f8488640e4d0":{
      "scriptId":"u6"},
    "636ef4e75b4f40eaa92149dcbeeb0155":{
      "scriptId":"u7"},
    "86e978164ae944b4bfe3b4c14024ac01":{
      "scriptId":"u8"},
    "84696916c87848f3a5a78a7c1dc35e8e":{
      "scriptId":"u9"},
    "445caa48a6d7484a923ffa65b82ad750":{
      "scriptId":"u10"},
    "0d21e2e4aa924c9c8d2a64ce4093f421":{
      "scriptId":"u11"},
    "2042734c6674459b9f98a4c96068aa73":{
      "scriptId":"u12"},
    "29f3070cccca4e5d96374116332fbc1d":{
      "scriptId":"u13"},
    "f1084f52cc224bc48503becd511d0844":{
      "scriptId":"u14"},
    "13469af061c24b1f976fa6ae1d8c138e":{
      "scriptId":"u15"},
    "0a40cce374d040b69e86b6ceab87c5af":{
      "scriptId":"u16"},
    "295bd69f94a1401f9035d1bb1e20f23e":{
      "scriptId":"u17"},
    "1ff382b47a754aefac1d93e6c6f35693":{
      "scriptId":"u18"},
    "781c991eacca4f4e93f76e90510e5419":{
      "scriptId":"u19"},
    "76ac1f6630754e32a2696aeb2b082be3":{
      "scriptId":"u20"},
    "d7b597d6831c4127bdd90383bf862548":{
      "scriptId":"u21"},
    "f8070f2a16034266a28fc5d22a602c1a":{
      "scriptId":"u22"},
    "8c9d2cb51f55479cb55c2bea6f8458e6":{
      "scriptId":"u23"},
    "dde262f3cff24bf581db134334e26b29":{
      "scriptId":"u24"},
    "e26b376912c543dd8d844d6a2bee2ac2":{
      "scriptId":"u25"},
    "3d165de89eca462db432cc282a7b20e9":{
      "scriptId":"u26"},
    "93ec4d4b04984cc9a92d6c0ba8301360":{
      "scriptId":"u27"},
    "27113612022c4ae993c0cb0972fe28e3":{
      "scriptId":"u28"},
    "762f999d16574d3db67783edacf04f84":{
      "scriptId":"u29"},
    "b9a7c43cf0eb45469ef758dfbeb5d924":{
      "scriptId":"u30"},
    "e08f26fcb9134694b2ed0054763a17de":{
      "scriptId":"u31"},
    "f8d8fe88da744e6fa8de0030c38b58bf":{
      "scriptId":"u32"},
    "56c78b2fa26c471e927b01e60dbdb42f":{
      "scriptId":"u33"},
    "fa840db30c63449a861a289ebbf5572d":{
      "scriptId":"u34"},
    "6b63b30701be4337b59c6a6535425602":{
      "scriptId":"u35"},
    "aefd81254550452dbba8b2cd73586e7e":{
      "scriptId":"u36"},
    "ea7edee8e7274f8fbd4dfcc97bb7f281":{
      "scriptId":"u37"},
    "e9397e7de016435ba0e01d82723c6eb0":{
      "scriptId":"u38"},
    "414f1156852c45a2b9ecf7571c20ba48":{
      "scriptId":"u39"},
    "d0d5dbf960394d658e239e80f8857989":{
      "scriptId":"u40"},
    "45fbc244d20a4cdf97e92a8e8032b0d1":{
      "scriptId":"u41"},
    "10c7f819d59046c4900bc145bbd5a631":{
      "scriptId":"u42"},
    "c06076a6b16848b68882b9cdb7d49212":{
      "scriptId":"u43"},
    "462c753c635a492e8811a3a21b2b29df":{
      "scriptId":"u44"},
    "3d6386c28d764cccb6f7042c32430fe3":{
      "scriptId":"u45"},
    "557d65bc65b04698a759fbe57f6b71ed":{
      "scriptId":"u46"},
    "8dc8b3571e364b3db14c39ba34f1bcc9":{
      "scriptId":"u47"},
    "80e4051c15b94067a48e61d46367938c":{
      "scriptId":"u48"},
    "b36f5f7779b342bd8228d7afa3fcdfc1":{
      "scriptId":"u49"},
    "26da94a605724fd5b7dd13095909d552":{
      "scriptId":"u50"},
    "1f24ff2f5a6044d78f2bac2ad0788f8b":{
      "scriptId":"u51"},
    "acdab9fa78ac44fb86867e8ac6ecaaa5":{
      "scriptId":"u52"},
    "530124deffa74b4680c0e16bca21f9e7":{
      "scriptId":"u53"},
    "75c135eb1f9c462b94be2b71a758f74a":{
      "scriptId":"u54"},
    "e30850bde364468e8c018f31989f02d4":{
      "scriptId":"u55"},
    "442b6f0c66934b5f85ef6f4723ab4133":{
      "scriptId":"u56"},
    "d687c39e43924929bd8d524b13d7a45a":{
      "scriptId":"u57"},
    "cd5226fda3d44c978eef1b459af80f1f":{
      "scriptId":"u58"},
    "2d8fe6b3ec694f32a2390ccca42a3e06":{
      "scriptId":"u59"},
    "0c9deb66a2cc4f878036c98f26a04f8d":{
      "scriptId":"u60"},
    "d10a52dff64b462cbba19a690ef876c5":{
      "scriptId":"u61"},
    "44269b188ddd47e1be8fa432c0bbb9fa":{
      "scriptId":"u62"},
    "a4ade9f977d3466786ef2c56a24f5020":{
      "scriptId":"u63"},
    "afc90c106ce242f3beec10e82b6a3513":{
      "scriptId":"u64"},
    "188655dc917d491c861a528d70f161e2":{
      "scriptId":"u65"},
    "973b3a42f6054f4e8b9476bb4a8fe36c":{
      "scriptId":"u66"},
    "a10669446d6348fb8c33f11724afd32b":{
      "scriptId":"u67"},
    "40497973f5224c2bbe9cdaeccd5ea5c0":{
      "scriptId":"u68"},
    "873e4ca05a1e4b998576939d492d3041":{
      "scriptId":"u69"},
    "f2a28e875e69426a88d62922c3e24f11":{
      "scriptId":"u70"},
    "ac34ecc4b0a247638716f52cab3daf84":{
      "scriptId":"u71"},
    "0f48493c88de4cd48138e5cdd507a5a5":{
      "scriptId":"u72"},
    "866949df41f04bc2bd8aec9a7999f8d5":{
      "scriptId":"u73"},
    "3591ae1d02b4416592d224a9963fe198":{
      "scriptId":"u74"},
    "b9b57ce57c5443fcb5283f174903c478":{
      "scriptId":"u75"},
    "d66a68e5ad4843a2aaf71c7ae88b6f7d":{
      "scriptId":"u76"},
    "815f8b67f1c948628ca4e1dd6c214b8b":{
      "scriptId":"u77"},
    "87c6ca79db3243228fe52a9c486b2d65":{
      "scriptId":"u78"},
    "52729744116d4420910bb5ca2f0004bc":{
      "scriptId":"u79"},
    "f40ff5f47b8b4f05a44dee49c4a97021":{
      "scriptId":"u80"},
    "75eadbb8364649c0bf8d6106f5b5ad81":{
      "scriptId":"u81"},
    "a9785711b2894a9bbac6f11ae50a3df6":{
      "scriptId":"u82"},
    "ac22d5613c4a4ab09b4ec514ce3f7348":{
      "scriptId":"u83"}}});