$axure.loadCurrentPage({
  "url":"文章详情_1.html",
  "generationDate":new Date(1505127552708.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"ec6fd5b240e342eba0466b03b1143eb0",
    "type":"Axure:Page",
    "name":"文章详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e6e3eeb23cc648cda1c4f9180d3aba9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "size":{
              "width":360,
              "height":1840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF1F1F1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c54a11d5966b4f5c9e383e5149a31b60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "size":{
                  "width":360,
                  "height":1840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文章详情_1/u0.png"}},
{
          "id":"20275300dcef45c6806b5cd0206286e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":359,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e52a44655f4fadbf05199257f2fcd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":359,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u2.png"}},
{
          "id":"48b24337312a47d68105518e1f4e6c3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90731d9dd4254a8682ae70ae4d8f1a73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u398.png"}},
{
          "id":"f7f257f2bbe1412498af452a6d93096c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":359,
              "height":85},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53856358c01b4f8c9bf81c1fb13ac841",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":359,
                  "height":85},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文章详情/u6.png"}},
{
          "id":"161a1c7b429d4d9499bfb60bbdd3a4e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":17,
              "y":50},
            "size":{
              "width":328,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1682a400b2f24eb598c3adabe1a671ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":17,
                  "y":50},
                "size":{
                  "width":328,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1af63c65090407899563554a6a23f3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":99},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1cc1e60c244f99b05c1d94ebf6799e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":99},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅线路/u195.png"}},
{
          "id":"d5a08b18637a4ed09207ea62a10493ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":43,
              "y":99},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"519923a5db6141b6ba7ccb700b00606c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":43,
                  "y":99},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1df5d217e414e5db01784a90689356c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":296,
              "y":102},
            "size":{
              "width":47,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6168e973fe340539c3a34aa55083be6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":296,
                  "y":102},
                "size":{
                  "width":47,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18be7619239e44ca950fb1c8b450a00d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":99},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83af0f817d9f4739a22543078c1f9ea7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":99},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅线路/u201.png"}},
{
          "id":"8d3242cc83904a858a91bd2f1f2b97b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":250,
              "y":102},
            "size":{
              "width":16,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b22eeebce2174df99416f09df4656f01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":250,
                  "y":102},
                "size":{
                  "width":16,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcb7658e29954a748c19ba363e1e8eae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":100},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df13d348aee54a23a8a2942d0716a168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":100},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅线路/u205.png"}},
{
          "id":"d3406da983db46d899f7e9af25abbd0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":359,
              "height":1230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2684669077544092b3830ae25fc115a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":359,
                  "height":1230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文章详情/u22.png"}},
{
          "id":"0d84e09c2403463dbe173dee2ba07a55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":272},
            "size":{
              "width":327,
              "height":246}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b17fea3df30444a89c4acbd6009e3ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":272},
                "size":{
                  "width":327,
                  "height":246}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文章详情/u24.jpg"}},
{
          "id":"3a4ddbb8ce7d4834b812daadce2ecfb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":150},
            "size":{
              "width":326,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"357a959499824e72bdff0eb21f3d5a3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":150},
                "size":{
                  "width":326,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34015bdc6e3249dea227eab614338ece",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":528},
            "size":{
              "width":326,
              "height":122}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"096816564c684c2ca91995a544f29df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":528},
                "size":{
                  "width":326,
                  "height":122}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f17b820e4914e748f2e0061197b1423",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":650},
            "size":{
              "width":323,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bffd3c594a04aff8240df7394dcfdba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":650},
                "size":{
                  "width":323,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文章详情/u30.jpg"}},
{
          "id":"f85b7b7c0b1e4b939ccca968b422a26d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":875},
            "size":{
              "width":323,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96279aed204146e8a8c2b3775cd90ade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":875},
                "size":{
                  "width":323,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e7f7891b89f4830bb7c9a422eecc415",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":997},
            "size":{
              "width":326,
              "height":217}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77a787abc75f4f1c8247df6c4b3cc8ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":997},
                "size":{
                  "width":326,
                  "height":217}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文章详情/u34.jpg"}},
{
          "id":"9ca2c4e7069544e5b5d8ac74ab4e5ab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":1224},
            "size":{
              "width":325,
              "height":136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"570ecdc4b19d4980aef735c26ebf2c4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":1224},
                "size":{
                  "width":325,
                  "height":136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8b083b2f0aa4e1d8a58479c7da6008c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1390},
            "size":{
              "width":359,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30a000774ee0451087fe78982a3fba54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1390},
                "size":{
                  "width":359,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u200.png"}},
{
          "id":"00448f98c74a4ea3aadab8baab2a987e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":1372},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a98112c5be99447d8da574c1c1af5132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":1372},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a48f57e7345d431686838931d357b519",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1400},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9c94774257f49b69d21ad3c4e17434d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1400},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u204.jpg"}},
{
          "id":"8a3efbd7c6194810ac6a681e937a7bec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":1400},
            "size":{
              "width":242,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d335e431600c4b1b85b49759d250ebc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":1400},
                "size":{
                  "width":242,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4291011a5a1f486380a4be8c928e0ecf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":1410.5},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f321ef7764554d859024b8bce08a4dc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":1410.5},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u223.png"}},
{
          "id":"84e8c2df97ad48b99d29b4b8ca23634c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1488},
            "size":{
              "width":359,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"727191e64724423d86fb8533fa3207b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1488},
                "size":{
                  "width":359,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u200.png"}},
{
          "id":"7e72dd85daab44149d65090cf2f814fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":1470},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbd4ffa23cc74b30916c2d9b387f4225",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":1470},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"215f3cf5f82047168a37de16cc388a8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1498},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fab6dbf953a4bfbb1084799cd685dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1498},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u214.jpg"}},
{
          "id":"4259b019ec1f4cdfb5bd0e936df2cb0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":1498},
            "size":{
              "width":252,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96563abea05746099c95b29e87df01ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":1498},
                "size":{
                  "width":252,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df80e1e9146646fc8b2bf3779ef37f7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":1508},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a46f520413b4b9d97901f942e73b998",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":1508},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u223.png"}},
{
          "id":"15ab1fd4bedd47c194f1f929f537095a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1558},
            "size":{
              "width":359,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6980c0cb6c564a4e88115a7b79ae9964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1558},
                "size":{
                  "width":359,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u200.png"}},
{
          "id":"e428fd01a8f741b8b775c379f7b7e365",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1568},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b50eea4719d4acf9e0abbdc3aa9165c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1568},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u222.jpg"}},
{
          "id":"0a87cc1c60334c36a96e57db777ca2d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":1568},
            "size":{
              "width":252,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a77f1b07e34b4ed68518ce736ef04e7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":1568},
                "size":{
                  "width":252,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1416972b72c848618ee71c0b32db1847",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":1578},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73b5fc3835d245b99931c6ff779bc31e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":1578},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u223.png"}},
{
          "id":"d0dc2dbc11b74391a76393cb95b932ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1628},
            "size":{
              "width":359,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c74ce0f3e5e74934a4700c6ee11aec9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1628},
                "size":{
                  "width":359,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u200.png"}},
{
          "id":"cb9c9fa714444a63b3dfaa170a97ec32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1638},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a589d03de0ad415ca1acdc35dec3ffab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1638},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u230.jpg"}},
{
          "id":"81aa2ad68a9c4e338adfc54fcca96928",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":1638},
            "size":{
              "width":252,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601ef0b99bde42299df8e379562f7a30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":1638},
                "size":{
                  "width":252,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"505ed5b85b4f49a18f47e6bb93fc4cef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":1648},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6659c5c6a374d77bf894e245a602ad7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":1648},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u223.png"}},
{
          "id":"1b2eeaaf133c41918271c6b34c2b9ded",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1708},
            "size":{
              "width":360,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b9114b9c2ab4fda98dee317f8ed2a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1708},
                "size":{
                  "width":360,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会员特权",
                      "target":{
                        "targetType":"page",
                        "url":"会员特权.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页_安卓_/u89.png"}},
{
          "id":"2245e8e283d0431e81ed4166e4f2bb9e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1390},
            "size":{
              "width":359,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 线路详情",
                      "target":{
                        "targetType":"page",
                        "url":"线路详情_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"46ac8f9eae3644e88b505ee1b342106a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1488},
            "size":{
              "width":359,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 线路详情",
                      "target":{
                        "targetType":"page",
                        "url":"线路详情_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e57b7efb636f482cb059544f56af1943",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1558},
            "size":{
              "width":359,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 线路详情",
                      "target":{
                        "targetType":"page",
                        "url":"线路详情_6.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"676e5044c17643cf9e3e3620ef6a8680",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1628},
            "size":{
              "width":359,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 线路详情",
                      "target":{
                        "targetType":"page",
                        "url":"线路详情_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "e6e3eeb23cc648cda1c4f9180d3aba9c":{
      "scriptId":"u0"},
    "c54a11d5966b4f5c9e383e5149a31b60":{
      "scriptId":"u1"},
    "20275300dcef45c6806b5cd0206286e9":{
      "scriptId":"u2"},
    "19e52a44655f4fadbf05199257f2fcd6":{
      "scriptId":"u3"},
    "48b24337312a47d68105518e1f4e6c3a":{
      "scriptId":"u4"},
    "90731d9dd4254a8682ae70ae4d8f1a73":{
      "scriptId":"u5"},
    "f7f257f2bbe1412498af452a6d93096c":{
      "scriptId":"u6"},
    "53856358c01b4f8c9bf81c1fb13ac841":{
      "scriptId":"u7"},
    "161a1c7b429d4d9499bfb60bbdd3a4e0":{
      "scriptId":"u8"},
    "1682a400b2f24eb598c3adabe1a671ab":{
      "scriptId":"u9"},
    "d1af63c65090407899563554a6a23f3c":{
      "scriptId":"u10"},
    "5f1cc1e60c244f99b05c1d94ebf6799e":{
      "scriptId":"u11"},
    "d5a08b18637a4ed09207ea62a10493ea":{
      "scriptId":"u12"},
    "519923a5db6141b6ba7ccb700b00606c":{
      "scriptId":"u13"},
    "b1df5d217e414e5db01784a90689356c":{
      "scriptId":"u14"},
    "b6168e973fe340539c3a34aa55083be6":{
      "scriptId":"u15"},
    "18be7619239e44ca950fb1c8b450a00d":{
      "scriptId":"u16"},
    "83af0f817d9f4739a22543078c1f9ea7":{
      "scriptId":"u17"},
    "8d3242cc83904a858a91bd2f1f2b97b1":{
      "scriptId":"u18"},
    "b22eeebce2174df99416f09df4656f01":{
      "scriptId":"u19"},
    "fcb7658e29954a748c19ba363e1e8eae":{
      "scriptId":"u20"},
    "df13d348aee54a23a8a2942d0716a168":{
      "scriptId":"u21"},
    "d3406da983db46d899f7e9af25abbd0a":{
      "scriptId":"u22"},
    "2684669077544092b3830ae25fc115a6":{
      "scriptId":"u23"},
    "0d84e09c2403463dbe173dee2ba07a55":{
      "scriptId":"u24"},
    "0b17fea3df30444a89c4acbd6009e3ff":{
      "scriptId":"u25"},
    "3a4ddbb8ce7d4834b812daadce2ecfb6":{
      "scriptId":"u26"},
    "357a959499824e72bdff0eb21f3d5a3a":{
      "scriptId":"u27"},
    "34015bdc6e3249dea227eab614338ece":{
      "scriptId":"u28"},
    "096816564c684c2ca91995a544f29df1":{
      "scriptId":"u29"},
    "5f17b820e4914e748f2e0061197b1423":{
      "scriptId":"u30"},
    "8bffd3c594a04aff8240df7394dcfdba":{
      "scriptId":"u31"},
    "f85b7b7c0b1e4b939ccca968b422a26d":{
      "scriptId":"u32"},
    "96279aed204146e8a8c2b3775cd90ade":{
      "scriptId":"u33"},
    "3e7f7891b89f4830bb7c9a422eecc415":{
      "scriptId":"u34"},
    "77a787abc75f4f1c8247df6c4b3cc8ee":{
      "scriptId":"u35"},
    "9ca2c4e7069544e5b5d8ac74ab4e5ab9":{
      "scriptId":"u36"},
    "570ecdc4b19d4980aef735c26ebf2c4a":{
      "scriptId":"u37"},
    "a8b083b2f0aa4e1d8a58479c7da6008c":{
      "scriptId":"u38"},
    "30a000774ee0451087fe78982a3fba54":{
      "scriptId":"u39"},
    "00448f98c74a4ea3aadab8baab2a987e":{
      "scriptId":"u40"},
    "a98112c5be99447d8da574c1c1af5132":{
      "scriptId":"u41"},
    "a48f57e7345d431686838931d357b519":{
      "scriptId":"u42"},
    "d9c94774257f49b69d21ad3c4e17434d":{
      "scriptId":"u43"},
    "8a3efbd7c6194810ac6a681e937a7bec":{
      "scriptId":"u44"},
    "d335e431600c4b1b85b49759d250ebc9":{
      "scriptId":"u45"},
    "4291011a5a1f486380a4be8c928e0ecf":{
      "scriptId":"u46"},
    "f321ef7764554d859024b8bce08a4dc7":{
      "scriptId":"u47"},
    "84e8c2df97ad48b99d29b4b8ca23634c":{
      "scriptId":"u48"},
    "727191e64724423d86fb8533fa3207b2":{
      "scriptId":"u49"},
    "7e72dd85daab44149d65090cf2f814fd":{
      "scriptId":"u50"},
    "fbd4ffa23cc74b30916c2d9b387f4225":{
      "scriptId":"u51"},
    "215f3cf5f82047168a37de16cc388a8f":{
      "scriptId":"u52"},
    "6fab6dbf953a4bfbb1084799cd685dac":{
      "scriptId":"u53"},
    "4259b019ec1f4cdfb5bd0e936df2cb0a":{
      "scriptId":"u54"},
    "96563abea05746099c95b29e87df01ec":{
      "scriptId":"u55"},
    "df80e1e9146646fc8b2bf3779ef37f7e":{
      "scriptId":"u56"},
    "5a46f520413b4b9d97901f942e73b998":{
      "scriptId":"u57"},
    "15ab1fd4bedd47c194f1f929f537095a":{
      "scriptId":"u58"},
    "6980c0cb6c564a4e88115a7b79ae9964":{
      "scriptId":"u59"},
    "e428fd01a8f741b8b775c379f7b7e365":{
      "scriptId":"u60"},
    "9b50eea4719d4acf9e0abbdc3aa9165c":{
      "scriptId":"u61"},
    "0a87cc1c60334c36a96e57db777ca2d3":{
      "scriptId":"u62"},
    "a77f1b07e34b4ed68518ce736ef04e7d":{
      "scriptId":"u63"},
    "1416972b72c848618ee71c0b32db1847":{
      "scriptId":"u64"},
    "73b5fc3835d245b99931c6ff779bc31e":{
      "scriptId":"u65"},
    "d0dc2dbc11b74391a76393cb95b932ab":{
      "scriptId":"u66"},
    "c74ce0f3e5e74934a4700c6ee11aec9e":{
      "scriptId":"u67"},
    "cb9c9fa714444a63b3dfaa170a97ec32":{
      "scriptId":"u68"},
    "a589d03de0ad415ca1acdc35dec3ffab":{
      "scriptId":"u69"},
    "81aa2ad68a9c4e338adfc54fcca96928":{
      "scriptId":"u70"},
    "601ef0b99bde42299df8e379562f7a30":{
      "scriptId":"u71"},
    "505ed5b85b4f49a18f47e6bb93fc4cef":{
      "scriptId":"u72"},
    "a6659c5c6a374d77bf894e245a602ad7":{
      "scriptId":"u73"},
    "1b2eeaaf133c41918271c6b34c2b9ded":{
      "scriptId":"u74"},
    "6b9114b9c2ab4fda98dee317f8ed2a42":{
      "scriptId":"u75"},
    "2245e8e283d0431e81ed4166e4f2bb9e":{
      "scriptId":"u76"},
    "46ac8f9eae3644e88b505ee1b342106a":{
      "scriptId":"u77"},
    "e57b7efb636f482cb059544f56af1943":{
      "scriptId":"u78"},
    "676e5044c17643cf9e3e3620ef6a8680":{
      "scriptId":"u79"}}});