$axure.loadCurrentPage({
  "url":"7_6订单详情（优品）交易完成.html",
  "generationDate":new Date(1511332459357.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"b3e45af604174422abc41418d895eb97",
    "type":"Axure:Page",
    "name":"7.6订单详情（优品）交易完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"efbfe02318414a33aa37749034d14392",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":88},
            "size":{
              "width":330,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c98dead566490c999d2dc309b5ac85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":88},
                "size":{
                  "width":330,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05f85479ee7343ccaae46bb4c2deeb09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":780}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad8329d904e3442197a7f3ccc79635c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":780}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7_6订单详情（优品）/u0.png"}},
{
          "id":"725c1361229d438b8472eccf4ac33657",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cee3eb7e9c44438b08d924ad09e7765",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"b6f2ad06ad2b43a38b0118ba2a8f9c29",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a913ec7e487346dcb634c22f1c5814a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"75bc7baee41944648fb9ebdf88495e83",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":145,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d6bc1099fe642f689795660bed55907",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":145,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3e176d456ca47ec8311c603b1f68a87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":47},
            "size":{
              "width":360,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b28407afa2b4288a5e153fd0b9cbb69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":47},
                "size":{
                  "width":360,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u8.png"}},
{
          "id":"473b23b474414f5cbeb3eec7298e3cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":89},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3c54ca53baf4a668f76d40e5683cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":89},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"775bb9cd218b4faeaae02bfb019af7b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":56},
            "size":{
              "width":302,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a25fe0e7702c44fc9ef27f6ae8b54145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":56},
                "size":{
                  "width":302,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"883ccbee0a0e4843a982dda14e16f1bb",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f3bea6a608974bdba07cea0957934d5b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"03a524e160e3444e8ef676149fd164ec",
                  "label":"",
                  "parentDynamicPanel":"883ccbee0a0e4843a982dda14e16f1bb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"44cda2d6dabc445d81438ff42f0bc8f7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"883ccbee0a0e4843a982dda14e16f1bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
                  "id":"6ebec82256884e51bf0ef88d8c293d4c",
                  "label":"",
                  "parentDynamicPanel":"883ccbee0a0e4843a982dda14e16f1bb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":12},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f6075f1a681414ba7ec19126320be44",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"883ccbee0a0e4843a982dda14e16f1bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":12},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"827b438fc03442b98e19719672b2bf80",
                  "label":"",
                  "parentDynamicPanel":"883ccbee0a0e4843a982dda14e16f1bb",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"b7ddac0dbcec4f14b0fc4d5f4f35f40a",
                  "label":"",
                  "parentDynamicPanel":"883ccbee0a0e4843a982dda14e16f1bb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":283,
                      "y":5},
                    "size":{
                      "width":67,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c8b66ff6cff749f7a96a9731d8360fec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"883ccbee0a0e4843a982dda14e16f1bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":283,
                          "y":5},
                        "size":{
                          "width":67,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/1_9订单详情（农旅卡）/u34.png"}}]}]},
{
          "id":"a6ba9d3906cd4cec8b5d35a8d3d9b0bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":61},
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18cecfdcced5433cb8d7bf6652a79f05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":61},
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u22.png"}},
{
          "id":"c98913d678fb4b29a7bd92168a705d5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f14307055b461aa6f517ed0b4ca6e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"69d3c962a6ed4f62b471b8f0782fcda8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":125},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa25a2348244ebc8dedd81fb6f51612",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":125},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u25.png"}},
{
          "id":"170c67a057734045aa1aff742a4ccf84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":132},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e2cb85ef8a04d7aa04cbe5fc82ff4ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":132},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"493ed921e5634e70ae0b4734b5517f30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":79,
              "y":132},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd22e930990645e2b048376ee5e12254",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":132},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61d1f8f71bcb4b9187da15ba83e3b8c4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":-3,
              "y":170},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ced1adc4c6154998a3b391b35a4e188c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":480},
            "size":{
              "width":360,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b448e6284a444e67831ddb442c8883ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":480},
                "size":{
                  "width":360,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_9订单详情（农旅卡）/u8.png"}},
{
          "id":"20984d3d0add4d15a178007ea600850a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":9,
              "y":490},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c621d5e6c1e343b6948c8f7a0793865d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":9,
                  "y":490},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f3edcab6f7943c7ae5ca479c7e6fa0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":509},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6700e3080db84911835e462026329b2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":509},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcc4b7ff244f4696b6f21fc9be8a7ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":525},
            "size":{
              "width":45,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f72a6f7d28a44af94e912a9c88dd8ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":525},
                "size":{
                  "width":45,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0ff931dd47f44d1a740b94f35079317",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":222,
              "y":553},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5b1981054fb4d508106856f68637872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":222,
                  "y":553},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ba1d1de54014fd7a24b86df81f59f51",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":541},
            "size":{
              "width":338,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/1_9订单详情（农旅卡）/u18_line.png"}},
{
          "id":"c42c617b05e24fe680238a627efd42d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":489},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"917097e015ab4b768f901873f304b609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":489},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0c04436a38a41e5abc8be1f4a5b8ded",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":291,
              "y":525},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"423333c720f5412ba99f745c2ce4b905",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":291,
                  "y":525},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbc44be71b834991a46a4ce6782e9df4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":289,
              "y":553},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a50a11859f8448b86ff78e0a38ea654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":289,
                  "y":553},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7dc6fccb0514a54be732261548ab86f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":291,
              "y":509},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"829c795416574703a01adaa42459937f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":291,
                  "y":509},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"924d7a925bbe4416a426a5078d19c4fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":360,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dff035e674740698b1b40caf7cbd907",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":360,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u36.png"}},
{
          "id":"495ace16e42443628bac86153ce480de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":177},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8819a8d89e54697abd9d38fda650d39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":177},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"266d41357a2c4f41aa51ab5b27569f04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":177},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb7c4f32a8504e499e0c8683da4af021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":177},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d4c3c1db28842d081f5af56b3353d07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":7},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eca90fde19e04fb3b575f40fe3eb7e24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":7},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_9订单详情（农旅卡）/u36.png"}},
{
          "id":"c4ce967c75df4ce19bb3670a832d2e6b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":0},
            "size":{
              "width":45,
              "height":41}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0bb7042464674ed0b9026e36603b1a70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":202},
            "size":{
              "width":360,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab1d740f438147a29953e754881f4b17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":202},
                "size":{
                  "width":360,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u42.png"}},
{
          "id":"ac3d7b1dad7c47bfb4a0cbfc4d383a1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":212},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9e74a5209504199b7eb070531ca4f4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":212},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u44.png"}},
{
          "id":"a08ee5c3a46c4917a0d14b49ed41b630",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":120,
              "y":212},
            "size":{
              "width":225,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcd5b522ec694e509df662d40515dc59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":120,
                  "y":212},
                "size":{
                  "width":225,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"951872debb374e33814785c2019931b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":120,
              "y":241},
            "size":{
              "width":100,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19b64e698d6e4c908b1a03c14e03b303",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":241},
                "size":{
                  "width":100,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb1665fbc1ef456782146fdaf25899d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":266},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"173b84aaa83443e08584642c7dcb014d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":266},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d5ebde9d1c14dd1b30e22ff7634ced9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":326,
              "y":266},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69ec0494f8ea4727a2ac18a763be3a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":326,
                  "y":266},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efa8de3c3aba49bcb24fe9549ec19862",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":30,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c39f906b14e41239372c415081c63e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":30,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u54.png"}},
{
          "id":"d2474330e8f1461a9467bb9ac3fabd8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":293},
            "size":{
              "width":360,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"336256a006db4e8cb1ce1b7769b6f865",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":293},
                "size":{
                  "width":360,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u42.png"}},
{
          "id":"83bbed40698848a2bab32d5ac819f805",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":303},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae1b4f8ea44b47da99e6255654711309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":303},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u44.png"}},
{
          "id":"2acc4486d27b44e59c2576967196a351",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":120,
              "y":303},
            "size":{
              "width":225,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64bf2cb301e34d4d8d236c0cb8d28c10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":120,
                  "y":303},
                "size":{
                  "width":225,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27310b55aae543e4a1f624a12a400e5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":120,
              "y":332},
            "size":{
              "width":100,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5fa57b9847a481aa1934b4737e55788",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":332},
                "size":{
                  "width":100,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a703319168b468f83c330c6e04538c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":357},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b85be045343453ea757a79bb0f9ea7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":357},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"493697382d5d4c6cbd87c83d41742796",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":326,
              "y":357},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"463868b02e5e40a985edab904d92cd4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":326,
                  "y":357},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31d60992e74a4dbea338d9b12ff4da0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":0,
              "y":291},
            "size":{
              "width":30,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e362b4906984b42b7e8868cf390d3bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":0,
                  "y":291},
                "size":{
                  "width":30,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u54.png"}},
{
          "id":"2799ed63749c41eab51761c0c7eb2d6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":384},
            "size":{
              "width":360,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9429365c0dd408eb63eca3cd001c342",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":384},
                "size":{
                  "width":360,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u42.png"}},
{
          "id":"0e8c8b858c6e497c8d314083c1b43c7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":394},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb91d9258f2d49409f35b584a359eaca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":394},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u44.png"}},
{
          "id":"19d6e5d27bdb4834bdd0e9a8f9fedb22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":120,
              "y":394},
            "size":{
              "width":225,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31db386a36ed4178a66e42051b530013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":120,
                  "y":394},
                "size":{
                  "width":225,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"063c1d93893944c6bfc342cd410b46df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":120,
              "y":423},
            "size":{
              "width":100,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b45cb005068d4205bc7c2dd6573c1519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":423},
                "size":{
                  "width":100,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5afc7872c7045f5a5820c74c5a7043c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":448},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5b2d31868c54fc1878719206ac46ec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":448},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f385c5b859344c818aa7a172ba0c5bf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":326,
              "y":448},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13de64d830104e77a26ae16832f49fbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":326,
                  "y":448},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dacec2d5e954cff8c037aa517ead346",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":0,
              "y":382},
            "size":{
              "width":30,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6d70f6f49774bda87fc6ba04a8f1827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":0,
                  "y":382},
                "size":{
                  "width":30,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_3_1订单详情（权益优品）/u54.png"}},
{
          "id":"68d73bd2f2ed44f8995e8868f09cb406",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":585},
            "size":{
              "width":360,
              "height":125}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4bff70945564419b8df11dd5d4ef643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":585},
                "size":{
                  "width":360,
                  "height":125}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/4_2_5订单详情（农旅）/u80.png"}},
{
          "id":"970bbba051924e26b2660940784385e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":8,
              "y":592},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c25db79eafbb4d1a87389f45fc7f947d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":8,
                  "y":592},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9298e8954c2d441a9ebb7dd01bf02469",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":592},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e7caeb3a633451da65de6da1cc53494",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":592},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17cf9a38cf5740738f8ecd1838b5d814",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":8,
              "y":612},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"812620c50ee9407b8385de58974d570d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":8,
                  "y":612},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e50c0cdbe3d406cba27fa6a425e040b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":612},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de7415fef03e4fe3933e35100ca3c89c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":612},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6709cb05d9d6483db9b0bda9836c4cab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":8,
              "y":666},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2833d6c2f3943648cb95a67fb62aa28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":8,
                  "y":666},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4432e1f52b5943ce8d41c60383a7a893",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":664},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50c64b6182f940ac87447d487c0593b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":664},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c963ce6061d642de9044138de1bd4441",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":8,
              "y":649},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c010fbb1898e48f88abf5641f0076678",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":8,
                  "y":649},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96b53922ed124a98a3f8d3db5a06b79f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":71,
              "y":649},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46020894eafd4cdf826d1be16d5e38d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":71,
                  "y":649},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd16eefb109d48f39e933b02a03c91fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":8,
              "y":630},
            "size":{
              "width":148,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceb9606e47c54b44b525f04907538c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":8,
                  "y":630},
                "size":{
                  "width":148,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"228ba4713e9b45b4a4ece26ec0efabca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":8,
              "y":682},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0f834bcf6b94c1792c7048c2e23aac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":8,
                  "y":682},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bd6649ee256412b9d4f0c0a59632cfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":680},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ccbfb59472a4a1497cf077f264ae1ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":680},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "efbfe02318414a33aa37749034d14392":{
      "scriptId":"u0"},
    "d1c98dead566490c999d2dc309b5ac85":{
      "scriptId":"u1"},
    "05f85479ee7343ccaae46bb4c2deeb09":{
      "scriptId":"u2"},
    "ad8329d904e3442197a7f3ccc79635c3":{
      "scriptId":"u3"},
    "725c1361229d438b8472eccf4ac33657":{
      "scriptId":"u4"},
    "9cee3eb7e9c44438b08d924ad09e7765":{
      "scriptId":"u5"},
    "b6f2ad06ad2b43a38b0118ba2a8f9c29":{
      "scriptId":"u6"},
    "a913ec7e487346dcb634c22f1c5814a6":{
      "scriptId":"u7"},
    "75bc7baee41944648fb9ebdf88495e83":{
      "scriptId":"u8"},
    "1d6bc1099fe642f689795660bed55907":{
      "scriptId":"u9"},
    "f3e176d456ca47ec8311c603b1f68a87":{
      "scriptId":"u10"},
    "4b28407afa2b4288a5e153fd0b9cbb69":{
      "scriptId":"u11"},
    "473b23b474414f5cbeb3eec7298e3cd9":{
      "scriptId":"u12"},
    "c3c54ca53baf4a668f76d40e5683cff5":{
      "scriptId":"u13"},
    "775bb9cd218b4faeaae02bfb019af7b1":{
      "scriptId":"u14"},
    "a25fe0e7702c44fc9ef27f6ae8b54145":{
      "scriptId":"u15"},
    "883ccbee0a0e4843a982dda14e16f1bb":{
      "scriptId":"u16"},
    "03a524e160e3444e8ef676149fd164ec":{
      "scriptId":"u17"},
    "44cda2d6dabc445d81438ff42f0bc8f7":{
      "scriptId":"u18"},
    "6ebec82256884e51bf0ef88d8c293d4c":{
      "scriptId":"u19"},
    "0f6075f1a681414ba7ec19126320be44":{
      "scriptId":"u20"},
    "827b438fc03442b98e19719672b2bf80":{
      "scriptId":"u21"},
    "b7ddac0dbcec4f14b0fc4d5f4f35f40a":{
      "scriptId":"u22"},
    "c8b66ff6cff749f7a96a9731d8360fec":{
      "scriptId":"u23"},
    "a6ba9d3906cd4cec8b5d35a8d3d9b0bf":{
      "scriptId":"u24"},
    "18cecfdcced5433cb8d7bf6652a79f05":{
      "scriptId":"u25"},
    "c98913d678fb4b29a7bd92168a705d5e":{
      "scriptId":"u26"},
    "f5f14307055b461aa6f517ed0b4ca6e2":{
      "scriptId":"u27"},
    "69d3c962a6ed4f62b471b8f0782fcda8":{
      "scriptId":"u28"},
    "afa25a2348244ebc8dedd81fb6f51612":{
      "scriptId":"u29"},
    "170c67a057734045aa1aff742a4ccf84":{
      "scriptId":"u30"},
    "8e2cb85ef8a04d7aa04cbe5fc82ff4ee":{
      "scriptId":"u31"},
    "493ed921e5634e70ae0b4734b5517f30":{
      "scriptId":"u32"},
    "dd22e930990645e2b048376ee5e12254":{
      "scriptId":"u33"},
    "61d1f8f71bcb4b9187da15ba83e3b8c4":{
      "scriptId":"u34"},
    "ced1adc4c6154998a3b391b35a4e188c":{
      "scriptId":"u35"},
    "b448e6284a444e67831ddb442c8883ee":{
      "scriptId":"u36"},
    "20984d3d0add4d15a178007ea600850a":{
      "scriptId":"u37"},
    "c621d5e6c1e343b6948c8f7a0793865d":{
      "scriptId":"u38"},
    "8f3edcab6f7943c7ae5ca479c7e6fa0b":{
      "scriptId":"u39"},
    "6700e3080db84911835e462026329b2c":{
      "scriptId":"u40"},
    "bcc4b7ff244f4696b6f21fc9be8a7ac2":{
      "scriptId":"u41"},
    "7f72a6f7d28a44af94e912a9c88dd8ec":{
      "scriptId":"u42"},
    "e0ff931dd47f44d1a740b94f35079317":{
      "scriptId":"u43"},
    "c5b1981054fb4d508106856f68637872":{
      "scriptId":"u44"},
    "2ba1d1de54014fd7a24b86df81f59f51":{
      "scriptId":"u45"},
    "c42c617b05e24fe680238a627efd42d0":{
      "scriptId":"u46"},
    "917097e015ab4b768f901873f304b609":{
      "scriptId":"u47"},
    "a0c04436a38a41e5abc8be1f4a5b8ded":{
      "scriptId":"u48"},
    "423333c720f5412ba99f745c2ce4b905":{
      "scriptId":"u49"},
    "dbc44be71b834991a46a4ce6782e9df4":{
      "scriptId":"u50"},
    "6a50a11859f8448b86ff78e0a38ea654":{
      "scriptId":"u51"},
    "c7dc6fccb0514a54be732261548ab86f":{
      "scriptId":"u52"},
    "829c795416574703a01adaa42459937f":{
      "scriptId":"u53"},
    "924d7a925bbe4416a426a5078d19c4fb":{
      "scriptId":"u54"},
    "0dff035e674740698b1b40caf7cbd907":{
      "scriptId":"u55"},
    "495ace16e42443628bac86153ce480de":{
      "scriptId":"u56"},
    "f8819a8d89e54697abd9d38fda650d39":{
      "scriptId":"u57"},
    "266d41357a2c4f41aa51ab5b27569f04":{
      "scriptId":"u58"},
    "bb7c4f32a8504e499e0c8683da4af021":{
      "scriptId":"u59"},
    "0d4c3c1db28842d081f5af56b3353d07":{
      "scriptId":"u60"},
    "eca90fde19e04fb3b575f40fe3eb7e24":{
      "scriptId":"u61"},
    "c4ce967c75df4ce19bb3670a832d2e6b":{
      "scriptId":"u62"},
    "0bb7042464674ed0b9026e36603b1a70":{
      "scriptId":"u63"},
    "ab1d740f438147a29953e754881f4b17":{
      "scriptId":"u64"},
    "ac3d7b1dad7c47bfb4a0cbfc4d383a1c":{
      "scriptId":"u65"},
    "f9e74a5209504199b7eb070531ca4f4e":{
      "scriptId":"u66"},
    "a08ee5c3a46c4917a0d14b49ed41b630":{
      "scriptId":"u67"},
    "dcd5b522ec694e509df662d40515dc59":{
      "scriptId":"u68"},
    "951872debb374e33814785c2019931b9":{
      "scriptId":"u69"},
    "19b64e698d6e4c908b1a03c14e03b303":{
      "scriptId":"u70"},
    "bb1665fbc1ef456782146fdaf25899d1":{
      "scriptId":"u71"},
    "173b84aaa83443e08584642c7dcb014d":{
      "scriptId":"u72"},
    "6d5ebde9d1c14dd1b30e22ff7634ced9":{
      "scriptId":"u73"},
    "69ec0494f8ea4727a2ac18a763be3a15":{
      "scriptId":"u74"},
    "efa8de3c3aba49bcb24fe9549ec19862":{
      "scriptId":"u75"},
    "0c39f906b14e41239372c415081c63e3":{
      "scriptId":"u76"},
    "d2474330e8f1461a9467bb9ac3fabd8c":{
      "scriptId":"u77"},
    "336256a006db4e8cb1ce1b7769b6f865":{
      "scriptId":"u78"},
    "83bbed40698848a2bab32d5ac819f805":{
      "scriptId":"u79"},
    "ae1b4f8ea44b47da99e6255654711309":{
      "scriptId":"u80"},
    "2acc4486d27b44e59c2576967196a351":{
      "scriptId":"u81"},
    "64bf2cb301e34d4d8d236c0cb8d28c10":{
      "scriptId":"u82"},
    "27310b55aae543e4a1f624a12a400e5b":{
      "scriptId":"u83"},
    "b5fa57b9847a481aa1934b4737e55788":{
      "scriptId":"u84"},
    "2a703319168b468f83c330c6e04538c1":{
      "scriptId":"u85"},
    "5b85be045343453ea757a79bb0f9ea7b":{
      "scriptId":"u86"},
    "493697382d5d4c6cbd87c83d41742796":{
      "scriptId":"u87"},
    "463868b02e5e40a985edab904d92cd4a":{
      "scriptId":"u88"},
    "31d60992e74a4dbea338d9b12ff4da0d":{
      "scriptId":"u89"},
    "7e362b4906984b42b7e8868cf390d3bf":{
      "scriptId":"u90"},
    "2799ed63749c41eab51761c0c7eb2d6f":{
      "scriptId":"u91"},
    "e9429365c0dd408eb63eca3cd001c342":{
      "scriptId":"u92"},
    "0e8c8b858c6e497c8d314083c1b43c7c":{
      "scriptId":"u93"},
    "bb91d9258f2d49409f35b584a359eaca":{
      "scriptId":"u94"},
    "19d6e5d27bdb4834bdd0e9a8f9fedb22":{
      "scriptId":"u95"},
    "31db386a36ed4178a66e42051b530013":{
      "scriptId":"u96"},
    "063c1d93893944c6bfc342cd410b46df":{
      "scriptId":"u97"},
    "b45cb005068d4205bc7c2dd6573c1519":{
      "scriptId":"u98"},
    "d5afc7872c7045f5a5820c74c5a7043c":{
      "scriptId":"u99"},
    "a5b2d31868c54fc1878719206ac46ec1":{
      "scriptId":"u100"},
    "f385c5b859344c818aa7a172ba0c5bf9":{
      "scriptId":"u101"},
    "13de64d830104e77a26ae16832f49fbf":{
      "scriptId":"u102"},
    "4dacec2d5e954cff8c037aa517ead346":{
      "scriptId":"u103"},
    "e6d70f6f49774bda87fc6ba04a8f1827":{
      "scriptId":"u104"},
    "68d73bd2f2ed44f8995e8868f09cb406":{
      "scriptId":"u105"},
    "c4bff70945564419b8df11dd5d4ef643":{
      "scriptId":"u106"},
    "970bbba051924e26b2660940784385e6":{
      "scriptId":"u107"},
    "c25db79eafbb4d1a87389f45fc7f947d":{
      "scriptId":"u108"},
    "9298e8954c2d441a9ebb7dd01bf02469":{
      "scriptId":"u109"},
    "5e7caeb3a633451da65de6da1cc53494":{
      "scriptId":"u110"},
    "17cf9a38cf5740738f8ecd1838b5d814":{
      "scriptId":"u111"},
    "812620c50ee9407b8385de58974d570d":{
      "scriptId":"u112"},
    "8e50c0cdbe3d406cba27fa6a425e040b":{
      "scriptId":"u113"},
    "de7415fef03e4fe3933e35100ca3c89c":{
      "scriptId":"u114"},
    "6709cb05d9d6483db9b0bda9836c4cab":{
      "scriptId":"u115"},
    "b2833d6c2f3943648cb95a67fb62aa28":{
      "scriptId":"u116"},
    "4432e1f52b5943ce8d41c60383a7a893":{
      "scriptId":"u117"},
    "50c64b6182f940ac87447d487c0593b6":{
      "scriptId":"u118"},
    "c963ce6061d642de9044138de1bd4441":{
      "scriptId":"u119"},
    "c010fbb1898e48f88abf5641f0076678":{
      "scriptId":"u120"},
    "96b53922ed124a98a3f8d3db5a06b79f":{
      "scriptId":"u121"},
    "46020894eafd4cdf826d1be16d5e38d1":{
      "scriptId":"u122"},
    "cd16eefb109d48f39e933b02a03c91fd":{
      "scriptId":"u123"},
    "ceb9606e47c54b44b525f04907538c5f":{
      "scriptId":"u124"},
    "228ba4713e9b45b4a4ece26ec0efabca":{
      "scriptId":"u125"},
    "f0f834bcf6b94c1792c7048c2e23aac2":{
      "scriptId":"u126"},
    "2bd6649ee256412b9d4f0c0a59632cfb":{
      "scriptId":"u127"},
    "7ccbfb59472a4a1497cf077f264ae1ed":{
      "scriptId":"u128"}}});