$axure.loadCurrentPage({
  "url":"菜品详情.html",
  "generationDate":new Date(1505201778709.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"1f9ed28a019c453d8e21056a68ddcffa",
    "type":"Axure:Page",
    "name":"菜品详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"93fc559d8180414982faf72d42539023",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "size":{
              "width":360,
              "height":730},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF1F1F1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c246cf616b4d4e33ac6e673b32258833",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "size":{
                  "width":360,
                  "height":730},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜品详情/u0.png"}},
{
          "id":"ba1050bd091849359880aa2c73bb4441",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8bdde23b19c408b97308ca9ea977be4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/待发货/u2.png"}},
{
          "id":"b9cff1aa06f64d3cbea810dc79706469",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":7.5},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"476d5928cdc343dfae4334c0fcaded7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":7.5},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页2/u416.png"}},
{
          "id":"5b5cfe99197147e0b670e7698380e85e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":148,
              "y":11},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df7304c95e2e454199b389fdf1238a85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":11},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5c3ab6129204250a1469a6a6e0566a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":50},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36c80c05a28743cb8f8de8f1ff42a972",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":50},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜品列表/u16.jpg"}},
{
          "id":"5f2b5bf7bc784361b49f1995ee52cdde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":260},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ad47de60d7a44dda7a8613c38ffb4b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":260},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"f5b660bbf79841078e049bf4ac1f1b2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":53,
              "y":272},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6576f0200e44f9086dced3b6673152c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":53,
                  "y":272},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"537628bd2fad42b2901a1cb13295e7ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":299},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75618831b9d7441e922dd30d71e0aced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":299},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"c44d7c1a4a8e4cb585f3073eeff814b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":53,
              "y":311},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbf82807cd6f4d2392a82071876f2c84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":53,
                  "y":311},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05804f7b06914eaeba2bcec45bf58f76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":338},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c80b83dba64465fa7d21b04e757f89a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":338},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"ddd815504a3f4eecbd718a1a222e54d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":53,
              "y":350},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a624f9a75db547b38ee8b9e8bf8d6900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":53,
                  "y":350},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab18fef33d6c40d68170150e5629b2e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":377},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"208000d8546d41c293076b29850ed2cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":377},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页2/u67.png"}},
{
          "id":"231a53c281204ff1abbfd4ce1ef37b8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":53,
              "y":389},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d55abb2a2b514d6ea9309bfc43bd9964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":53,
                  "y":389},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b21f18a6b13c4732910c54ead5283217",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":268},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1bc112d662a3477ebfa2b312dba5f529",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":307},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2aa5839b17954a32917d492df22fbf03",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":346},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"176bafcb44e7454392cc1b9b1314aa13",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":384},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"493cb52b59d8447ca52aed8d268fb19f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":451},
            "size":{
              "width":360,
              "height":190},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1331c0435b084b7bb7bd7d6dbdde7877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":451},
                "size":{
                  "width":360,
                  "height":190},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜品详情/u30.png"}},
{
          "id":"5b4376989e3042f98c45813f224b3a6d",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":461},
            "size":{
              "width":337,
              "height":170}},
          "adaptiveStyles":{
}},
{
          "id":"3da24d987e814243863b7ac0f9190f4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":12,
              "y":432},
            "size":{
              "width":45,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32b02d8a3a4c40c2977d00b0159e4198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":432},
                "size":{
                  "width":45,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69aab9c61a0f47e7af336b174dc923ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":660},
            "size":{
              "width":150,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c36f64a2c52447a5929392305edc1809",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":660},
                "size":{
                  "width":150,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜品详情/u35.png"}},
{
          "id":"03fd1f3872084a93ac81e5d2b863144f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":190,
              "y":660},
            "size":{
              "width":150,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d1c095de48c429e8dfa8c9d6551826d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":190,
                  "y":660},
                "size":{
                  "width":150,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜品详情/u37.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "93fc559d8180414982faf72d42539023":{
      "scriptId":"u0"},
    "c246cf616b4d4e33ac6e673b32258833":{
      "scriptId":"u1"},
    "ba1050bd091849359880aa2c73bb4441":{
      "scriptId":"u2"},
    "f8bdde23b19c408b97308ca9ea977be4":{
      "scriptId":"u3"},
    "b9cff1aa06f64d3cbea810dc79706469":{
      "scriptId":"u4"},
    "476d5928cdc343dfae4334c0fcaded7c":{
      "scriptId":"u5"},
    "5b5cfe99197147e0b670e7698380e85e":{
      "scriptId":"u6"},
    "df7304c95e2e454199b389fdf1238a85":{
      "scriptId":"u7"},
    "a5c3ab6129204250a1469a6a6e0566a0":{
      "scriptId":"u8"},
    "36c80c05a28743cb8f8de8f1ff42a972":{
      "scriptId":"u9"},
    "5f2b5bf7bc784361b49f1995ee52cdde":{
      "scriptId":"u10"},
    "4ad47de60d7a44dda7a8613c38ffb4b7":{
      "scriptId":"u11"},
    "f5b660bbf79841078e049bf4ac1f1b2c":{
      "scriptId":"u12"},
    "b6576f0200e44f9086dced3b6673152c":{
      "scriptId":"u13"},
    "537628bd2fad42b2901a1cb13295e7ad":{
      "scriptId":"u14"},
    "75618831b9d7441e922dd30d71e0aced":{
      "scriptId":"u15"},
    "c44d7c1a4a8e4cb585f3073eeff814b9":{
      "scriptId":"u16"},
    "cbf82807cd6f4d2392a82071876f2c84":{
      "scriptId":"u17"},
    "05804f7b06914eaeba2bcec45bf58f76":{
      "scriptId":"u18"},
    "9c80b83dba64465fa7d21b04e757f89a":{
      "scriptId":"u19"},
    "ddd815504a3f4eecbd718a1a222e54d1":{
      "scriptId":"u20"},
    "a624f9a75db547b38ee8b9e8bf8d6900":{
      "scriptId":"u21"},
    "ab18fef33d6c40d68170150e5629b2e7":{
      "scriptId":"u22"},
    "208000d8546d41c293076b29850ed2cb":{
      "scriptId":"u23"},
    "231a53c281204ff1abbfd4ce1ef37b8d":{
      "scriptId":"u24"},
    "d55abb2a2b514d6ea9309bfc43bd9964":{
      "scriptId":"u25"},
    "b21f18a6b13c4732910c54ead5283217":{
      "scriptId":"u26"},
    "1bc112d662a3477ebfa2b312dba5f529":{
      "scriptId":"u27"},
    "2aa5839b17954a32917d492df22fbf03":{
      "scriptId":"u28"},
    "176bafcb44e7454392cc1b9b1314aa13":{
      "scriptId":"u29"},
    "493cb52b59d8447ca52aed8d268fb19f":{
      "scriptId":"u30"},
    "1331c0435b084b7bb7bd7d6dbdde7877":{
      "scriptId":"u31"},
    "5b4376989e3042f98c45813f224b3a6d":{
      "scriptId":"u32"},
    "3da24d987e814243863b7ac0f9190f4f":{
      "scriptId":"u33"},
    "32b02d8a3a4c40c2977d00b0159e4198":{
      "scriptId":"u34"},
    "69aab9c61a0f47e7af336b174dc923ab":{
      "scriptId":"u35"},
    "c36f64a2c52447a5929392305edc1809":{
      "scriptId":"u36"},
    "03fd1f3872084a93ac81e5d2b863144f":{
      "scriptId":"u37"},
    "0d1c095de48c429e8dfa8c9d6551826d":{
      "scriptId":"u38"}}});