$axure.loadCurrentPage({
  "url":"1_4蔬菜宅配订单详情.html",
  "generationDate":new Date(1505906464025.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"b0c3cc8b4f5343f6a25c8a9ff95b3102",
    "type":"Axure:Page",
    "name":"1.4蔬菜宅配订单详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f71ab9f2b5eb4ccfada89c7c945b091e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac626980264340e9a8601c7efa943bc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_2订单支付页/u0.png"}},
{
          "id":"6514a15f0c164eed895ec10eae992464",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f0ac57c554b4a019ec97b01f5e27b5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u99.png"}},
{
          "id":"54215657aa204d649cbe67344ec0084d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc1f07e6821b49efaf334485359e8cda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 5.3全部订单",
                      "target":{
                        "targetType":"page",
                        "url":"5_3全部订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u5.png"}},
{
          "id":"0537fa734f214518b09113054f8164bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":145,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b98b3e1ea09489a8dac9b6674585df7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":145,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec166e24a8ec4adb87faef19fe727f15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":47},
            "size":{
              "width":360,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b19ccf2a37a40f68c32c9993a5a8adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":47},
                "size":{
                  "width":360,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_4蔬菜宅配订单详情/u8.png"}},
{
          "id":"e7e89fbd006a460d98787ac14fed2027",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":89},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"225375215a554e9f962a608249941d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":89},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e431a95188647639c335275e044258c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":56},
            "size":{
              "width":302,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97e76a4058df4f149847298cbd33cc72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":56},
                "size":{
                  "width":302,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6e2560c446e413e8866361f0f1ec82c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":365},
            "size":{
              "width":360,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9121c41030547c0a35a5dd120900d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":365},
                "size":{
                  "width":360,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_4蔬菜宅配订单详情/u14.png"}},
{
          "id":"12cbe6452eeb42efb2f189e4f60d4128",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":375},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75e5896252e34c37a5137c9bf71a9ac8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":375},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38207f7d856a4eb0bc821f15c49f7bd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":375},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7048fceb127e4428a1e96865a416b5f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":375},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42947167373e4e53a6278c447f1c6509",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":394},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18bb2920ab444b4b91a006325d6c298e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":394},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"718db051a4f0445daec633c15d4e65a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":394},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43aa72c78d65407a9d816c8d13952654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":394},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81a1742bc4a94ff1915e44de10267543",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":475},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e60df6ccec8a4e79b7e7e87230e19f52",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"17bb2dc0ba2746829b48dc5e5b79f49d",
                  "label":"",
                  "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"875c65c30fcf4222a28478e4b580d194",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/0_0主页/top_u99.png"}},
{
                  "id":"4bdaf3a37ac64ce390539e49e8b16206",
                  "label":"",
                  "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":12},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f13abec700544bd59d44340361102c2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":12},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c7c9d4acc2c34ffd8e541ab5deaf5244",
                  "label":"",
                  "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":280,
                      "y":5},
                    "size":{
                      "width":67,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84d6dc9faf694e5f9c3eadf10dc77404",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81a1742bc4a94ff1915e44de10267543",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":280,
                          "y":5},
                        "size":{
                          "width":67,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/1_4蔬菜宅配订单详情/u29.png"}}]}]},
{
          "id":"ae5e0e1696c54723832627145082dd0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":61},
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59b6eab8e508496e998912204d7ecdff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":61},
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_4蔬菜宅配订单详情/u31.png"}},
{
          "id":"aa2d768ce0ab441db25a1dba2ec16b15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":360,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"510527b79be3405da2af77cbc31a7c7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":360,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_4蔬菜宅配订单详情/u33.png"}},
{
          "id":"7308b18033f84838ac58e78ebc569c9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":180},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0909415b9707439cbf5c58090fac0d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":180},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b2701a62493475b87401bb3a5b6f744",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":180},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7044e43d98849cab9a47ebc1235da1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":180},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c81a1457e4184bc0a4b76412c4383a6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":202,
              "y":180},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b7f107deeac4e0db05f8b04a1a1796d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":202,
                  "y":180},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbb7e0a21f574f0dbd7035a59aa4d085",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":265,
              "y":180},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a626fbb941884f83952c2158ecae474c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":265,
                  "y":180},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa7e0c136f304e54a79e373fd117e804",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":212},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/1_2订单支付页/u11_line.png"}},
{
          "id":"2fd652a27d12486da195555779da14ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b4996757b944bfaec45a364b78a2d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u99.png"}},
{
          "id":"b83fb0e072064b058c1609d19c308866",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":125},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c0fcdefc8774df28e6a01896fc1d948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":125},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0蔬菜宅配/u5.png"}},
{
          "id":"2dad89276cf047f5950e59c421ff6886",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":132},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5dd5d71e1cf4a42b0b351e2d463ac70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":132},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d84f1ca714f45edb8385b9abc77911c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":79,
              "y":132},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8803394313745ac8db0816d27588f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":132},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4db2868b25fe44ec8fd00c8d0b1a16e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":11,
              "y":224},
            "size":{
              "width":338,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e27faadc19c847c49b0849b31630931f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":11,
                  "y":224},
                "size":{
                  "width":338,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a408c5ed62854a8fba79bf0d6402cac5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":11,
              "y":196},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad06e648c51447029063d2c41cd13252",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":11,
                  "y":196},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96b01c130c704a42a55e9e1a786fbb1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":196},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"783761ef01b44d6a94ec7ef56833bade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":196},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76c8307b4fa94d7ea8199948a6a991a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":7},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8581ca66b93347ec81ee1c1d6d3add13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":7},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/u127.png"}},
{
          "id":"591ce7cf3b8c4a9d87f6e86b2dcb484f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":0},
            "size":{
              "width":45,
              "height":41}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 0.0主页",
                      "target":{
                        "targetType":"page",
                        "url":"0_0主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f3b59fd68e004b318edc7741c3c7f17c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":415},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"822379865d1f4ef19f24f36a061b0d24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":415},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccfcab1970ee4537a322cc68eafefc9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":415},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77454b6214d3464f9e7ae78ec25c3245",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":415},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90810df82a854d36a0edc6ccae12ec0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":436},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c774beb09a44de1b3eee9a60ff5bac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":436},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5dead737bcf94d9da2c53566eff2fdd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":434},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46aaae04cc7c49198f7944b5f720a41e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":434},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52ac619e9e5a40c58a4008ec5b7cf047",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":260},
            "size":{
              "width":360,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0d4634aaa4f4e4486cedafc46922a54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":260},
                "size":{
                  "width":360,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_4蔬菜宅配订单详情/u69.png"}},
{
          "id":"40460546848240ae80de3babf671c2ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":9,
              "y":270},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb02f6eb67a74502b87f9c80ddec4da1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":9,
                  "y":270},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdb603e1de10400fb23bf856c040c658",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":289},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57d2f31c92ef46778d2b665b6e45b6f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":289},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39c3f025f9cb4623b940e2bc3e004574",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":305},
            "size":{
              "width":45,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5243b9cbcc94e599da7fbb2f866acf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":305},
                "size":{
                  "width":45,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbbb7b34cd07448fa582e62a70b2bd5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":333},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7697a78dfefd4d9d9cfb335f13054c26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":333},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6b781cecbc048fea99c09f5ad40525e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":321},
            "size":{
              "width":338,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/1_4蔬菜宅配订单详情/u79_line.png"}},
{
          "id":"3ff8ae17360a413897813be1dfa0b7c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":269},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1325c1666db7454cb721aea9c0053428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":269},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0e779af3c604b06b6818d9b8ed79215",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":305},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"560c9ce52997423e8b86eb84357dec3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":301,
                  "y":305},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fda04614ca3440d6a0008d47df9148c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":292,
              "y":333},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90edd3a34d2f46a8ad1faefba23ceeca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":292,
                  "y":333},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b509b58d21044cac98cef631a05daa27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":289},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65603c1a33b44792abbcb4cb0ba19da7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":301,
                  "y":289},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f71ab9f2b5eb4ccfada89c7c945b091e":{
      "scriptId":"u0"},
    "ac626980264340e9a8601c7efa943bc9":{
      "scriptId":"u1"},
    "6514a15f0c164eed895ec10eae992464":{
      "scriptId":"u2"},
    "6f0ac57c554b4a019ec97b01f5e27b5e":{
      "scriptId":"u3"},
    "54215657aa204d649cbe67344ec0084d":{
      "scriptId":"u4"},
    "cc1f07e6821b49efaf334485359e8cda":{
      "scriptId":"u5"},
    "0537fa734f214518b09113054f8164bd":{
      "scriptId":"u6"},
    "4b98b3e1ea09489a8dac9b6674585df7":{
      "scriptId":"u7"},
    "ec166e24a8ec4adb87faef19fe727f15":{
      "scriptId":"u8"},
    "9b19ccf2a37a40f68c32c9993a5a8adf":{
      "scriptId":"u9"},
    "e7e89fbd006a460d98787ac14fed2027":{
      "scriptId":"u10"},
    "225375215a554e9f962a608249941d8d":{
      "scriptId":"u11"},
    "7e431a95188647639c335275e044258c":{
      "scriptId":"u12"},
    "97e76a4058df4f149847298cbd33cc72":{
      "scriptId":"u13"},
    "d6e2560c446e413e8866361f0f1ec82c":{
      "scriptId":"u14"},
    "b9121c41030547c0a35a5dd120900d12":{
      "scriptId":"u15"},
    "12cbe6452eeb42efb2f189e4f60d4128":{
      "scriptId":"u16"},
    "75e5896252e34c37a5137c9bf71a9ac8":{
      "scriptId":"u17"},
    "38207f7d856a4eb0bc821f15c49f7bd5":{
      "scriptId":"u18"},
    "7048fceb127e4428a1e96865a416b5f1":{
      "scriptId":"u19"},
    "42947167373e4e53a6278c447f1c6509":{
      "scriptId":"u20"},
    "18bb2920ab444b4b91a006325d6c298e":{
      "scriptId":"u21"},
    "718db051a4f0445daec633c15d4e65a4":{
      "scriptId":"u22"},
    "43aa72c78d65407a9d816c8d13952654":{
      "scriptId":"u23"},
    "81a1742bc4a94ff1915e44de10267543":{
      "scriptId":"u24"},
    "17bb2dc0ba2746829b48dc5e5b79f49d":{
      "scriptId":"u25"},
    "875c65c30fcf4222a28478e4b580d194":{
      "scriptId":"u26"},
    "4bdaf3a37ac64ce390539e49e8b16206":{
      "scriptId":"u27"},
    "f13abec700544bd59d44340361102c2a":{
      "scriptId":"u28"},
    "c7c9d4acc2c34ffd8e541ab5deaf5244":{
      "scriptId":"u29"},
    "84d6dc9faf694e5f9c3eadf10dc77404":{
      "scriptId":"u30"},
    "ae5e0e1696c54723832627145082dd0f":{
      "scriptId":"u31"},
    "59b6eab8e508496e998912204d7ecdff":{
      "scriptId":"u32"},
    "aa2d768ce0ab441db25a1dba2ec16b15":{
      "scriptId":"u33"},
    "510527b79be3405da2af77cbc31a7c7f":{
      "scriptId":"u34"},
    "7308b18033f84838ac58e78ebc569c9b":{
      "scriptId":"u35"},
    "0909415b9707439cbf5c58090fac0d35":{
      "scriptId":"u36"},
    "2b2701a62493475b87401bb3a5b6f744":{
      "scriptId":"u37"},
    "a7044e43d98849cab9a47ebc1235da1f":{
      "scriptId":"u38"},
    "c81a1457e4184bc0a4b76412c4383a6e":{
      "scriptId":"u39"},
    "5b7f107deeac4e0db05f8b04a1a1796d":{
      "scriptId":"u40"},
    "dbb7e0a21f574f0dbd7035a59aa4d085":{
      "scriptId":"u41"},
    "a626fbb941884f83952c2158ecae474c":{
      "scriptId":"u42"},
    "fa7e0c136f304e54a79e373fd117e804":{
      "scriptId":"u43"},
    "2fd652a27d12486da195555779da14ef":{
      "scriptId":"u44"},
    "99b4996757b944bfaec45a364b78a2d7":{
      "scriptId":"u45"},
    "b83fb0e072064b058c1609d19c308866":{
      "scriptId":"u46"},
    "7c0fcdefc8774df28e6a01896fc1d948":{
      "scriptId":"u47"},
    "2dad89276cf047f5950e59c421ff6886":{
      "scriptId":"u48"},
    "d5dd5d71e1cf4a42b0b351e2d463ac70":{
      "scriptId":"u49"},
    "0d84f1ca714f45edb8385b9abc77911c":{
      "scriptId":"u50"},
    "d8803394313745ac8db0816d27588f4c":{
      "scriptId":"u51"},
    "4db2868b25fe44ec8fd00c8d0b1a16e9":{
      "scriptId":"u52"},
    "e27faadc19c847c49b0849b31630931f":{
      "scriptId":"u53"},
    "a408c5ed62854a8fba79bf0d6402cac5":{
      "scriptId":"u54"},
    "ad06e648c51447029063d2c41cd13252":{
      "scriptId":"u55"},
    "96b01c130c704a42a55e9e1a786fbb1d":{
      "scriptId":"u56"},
    "783761ef01b44d6a94ec7ef56833bade":{
      "scriptId":"u57"},
    "76c8307b4fa94d7ea8199948a6a991a4":{
      "scriptId":"u58"},
    "8581ca66b93347ec81ee1c1d6d3add13":{
      "scriptId":"u59"},
    "591ce7cf3b8c4a9d87f6e86b2dcb484f":{
      "scriptId":"u60"},
    "f3b59fd68e004b318edc7741c3c7f17c":{
      "scriptId":"u61"},
    "822379865d1f4ef19f24f36a061b0d24":{
      "scriptId":"u62"},
    "ccfcab1970ee4537a322cc68eafefc9c":{
      "scriptId":"u63"},
    "77454b6214d3464f9e7ae78ec25c3245":{
      "scriptId":"u64"},
    "90810df82a854d36a0edc6ccae12ec0d":{
      "scriptId":"u65"},
    "1c774beb09a44de1b3eee9a60ff5bac6":{
      "scriptId":"u66"},
    "5dead737bcf94d9da2c53566eff2fdd5":{
      "scriptId":"u67"},
    "46aaae04cc7c49198f7944b5f720a41e":{
      "scriptId":"u68"},
    "52ac619e9e5a40c58a4008ec5b7cf047":{
      "scriptId":"u69"},
    "d0d4634aaa4f4e4486cedafc46922a54":{
      "scriptId":"u70"},
    "40460546848240ae80de3babf671c2ee":{
      "scriptId":"u71"},
    "eb02f6eb67a74502b87f9c80ddec4da1":{
      "scriptId":"u72"},
    "fdb603e1de10400fb23bf856c040c658":{
      "scriptId":"u73"},
    "57d2f31c92ef46778d2b665b6e45b6f9":{
      "scriptId":"u74"},
    "39c3f025f9cb4623b940e2bc3e004574":{
      "scriptId":"u75"},
    "c5243b9cbcc94e599da7fbb2f866acf6":{
      "scriptId":"u76"},
    "bbbb7b34cd07448fa582e62a70b2bd5a":{
      "scriptId":"u77"},
    "7697a78dfefd4d9d9cfb335f13054c26":{
      "scriptId":"u78"},
    "a6b781cecbc048fea99c09f5ad40525e":{
      "scriptId":"u79"},
    "3ff8ae17360a413897813be1dfa0b7c2":{
      "scriptId":"u80"},
    "1325c1666db7454cb721aea9c0053428":{
      "scriptId":"u81"},
    "d0e779af3c604b06b6818d9b8ed79215":{
      "scriptId":"u82"},
    "560c9ce52997423e8b86eb84357dec3f":{
      "scriptId":"u83"},
    "fda04614ca3440d6a0008d47df9148c0":{
      "scriptId":"u84"},
    "90edd3a34d2f46a8ad1faefba23ceeca":{
      "scriptId":"u85"},
    "b509b58d21044cac98cef631a05daa27":{
      "scriptId":"u86"},
    "65603c1a33b44792abbcb4cb0ba19da7":{
      "scriptId":"u87"}}});