$axure.loadCurrentPage({
  "url":"走地鸡详情.html",
  "generationDate":new Date(1505201933125.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"b6cf98e475c84d4db1fff632fd296ac8",
    "type":"Axure:Page",
    "name":"走地鸡详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2b1059b81d664d359f313ac267317044",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":211}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfcf45fad7ef4fbdb4714f2cf847f48b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":211}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/走地鸡详情/u0.jpg"}},
{
          "id":"62fd9b59f3f34f0fa95fbe589db70abb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":211},
            "size":{
              "width":360,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"defba758c2834f5bae15398b9cc57581",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":211},
                "size":{
                  "width":360,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/走地鸡详情/u2.png"}},
{
          "id":"edbaf934bef64c9f8b61d49ba614a055",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":276},
            "size":{
              "width":360,
              "height":304}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd15d031be264720b3ed39a31d4f533d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":276},
                "size":{
                  "width":360,
                  "height":304}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/走地鸡详情/u4.jpg"}},
{
          "id":"014a8bc73e334a4f81e9c68d28443d1d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":580},
            "size":{
              "width":360,
              "height":1067}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eeb83996b2246a6b2d313769c2f4bd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":580},
                "size":{
                  "width":360,
                  "height":1067}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/走地鸡详情/u6.jpg"}},
{
          "id":"0801636c49c84795937c78cb3e936b21",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1310},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1670e5afe62943288822558b6f4a5b1b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c94a79388d594169b46ba4a67438360f",
                  "label":"",
                  "parentDynamicPanel":"0801636c49c84795937c78cb3e936b21",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80da90b8c74c4aeeab39b1987312489a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0801636c49c84795937c78cb3e936b21",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 返回",
                              "target":{
                                "targetType":"backUrl",
                                "includeVariables":false},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页2/top_u46.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "2b1059b81d664d359f313ac267317044":{
      "scriptId":"u0"},
    "dfcf45fad7ef4fbdb4714f2cf847f48b":{
      "scriptId":"u1"},
    "62fd9b59f3f34f0fa95fbe589db70abb":{
      "scriptId":"u2"},
    "defba758c2834f5bae15398b9cc57581":{
      "scriptId":"u3"},
    "edbaf934bef64c9f8b61d49ba614a055":{
      "scriptId":"u4"},
    "bd15d031be264720b3ed39a31d4f533d":{
      "scriptId":"u5"},
    "014a8bc73e334a4f81e9c68d28443d1d":{
      "scriptId":"u6"},
    "1eeb83996b2246a6b2d313769c2f4bd1":{
      "scriptId":"u7"},
    "0801636c49c84795937c78cb3e936b21":{
      "scriptId":"u8"},
    "c94a79388d594169b46ba4a67438360f":{
      "scriptId":"u9"},
    "80da90b8c74c4aeeab39b1987312489a":{
      "scriptId":"u10"}}});