$axure.loadCurrentPage({
  "url":"2_2_3_3订单详情（权益农旅）.html",
  "generationDate":new Date(1510229473012.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum"],
  "page":{
    "packageId":"d819935da5b342a89079404009cc8fa7",
    "type":"Axure:Page",
    "name":"2.2.3.3订单详情（权益农旅）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"454e6d72673740f89bbaa23cd3ceabf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a584db4d65b74e1eab810ab009cd5c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u0.png"}},
{
          "id":"95463b67a8194076af9add9814e29a27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40e64226a996467680082067a246e08a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
          "id":"a26fa1af76ec4e0191d3aa40c37392aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64bf29acff1541659aba307b32fe370a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.3我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"2_3我的订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2_2_1确认订单_权益优品_/u4.png"}},
{
          "id":"c4448487167542c2a369b072d4da7484",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":145,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ce997990864d4c8ae8afa3bd08c7c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":145,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3f8cf7b31b8432a9bd391fcf41a3a22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":47},
            "size":{
              "width":360,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"649e37f161144a1f8a21e8c64bdce8b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":47},
                "size":{
                  "width":360,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_3订单详情（权益农旅）/u8.png"}},
{
          "id":"ea35a221ce334b5bb16138d714c97a7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":59},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb4198d7179f41efadd169d72e12359a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":59},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_3订单详情（权益农旅）/u10.png"}},
{
          "id":"11bb1d7bd2254d2ba32c01ee9e6824d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":55},
            "size":{
              "width":251,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77ac48c574294881bd12c2cb72f0b87e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":55},
                "size":{
                  "width":251,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a45d9ce07ae4a81b2817399f7ee983d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":76},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab0df11949204ef5baf76c1331b1aa7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":76},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ead681f3cda4427cb297dc8da1c6a4f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":107},
            "size":{
              "width":360,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a46bf1c61da74c5f9858fd23655e6a2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":107},
                "size":{
                  "width":360,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_3支付成功（农旅卡购卡）/u14.png"}},
{
          "id":"18431b0fc5ae487e9dbcb2df4c1022b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":67,
              "y":115},
            "size":{
              "width":279,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5cda885f6874e57aab5c5e9c7427767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":67,
                  "y":115},
                "size":{
                  "width":279,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d1fcd8d70b8403f88c152e961af8148",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":148},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63a818d4206b4dc98b850dadbf81a1f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":148},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d96b20e1108d45a4b38db247d130723d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":117},
            "size":{
              "width":48,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d02ac80b0834138b2c4b17a91e34b69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":117},
                "size":{
                  "width":48,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_3订单详情（权益农旅）/u22.jpg"}},
{
          "id":"4ed723fd84814176b8728c57a64ef14b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":329,
              "y":153},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4258446068cd4c089c772db441bfeea6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":329,
                  "y":153},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"467075897b654158bb9bb9763f929e2f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":290},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7c558c15aad94c66ac332815f4ece5e0",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"21a6835a2774464385adde8eac715737",
                  "label":"",
                  "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9387b98e395c4d97817ed01a8a372589",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（权益农旅）/u2.png"}},
{
                  "id":"545f63f1c29645ceb6fa263892416331",
                  "label":"",
                  "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":12},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e3492d49bfd44ca943fe6a2168ae00d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":12},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eacc6a09161e43b9a068c74272d2b584",
                  "label":"",
                  "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":283,
                      "y":5},
                    "size":{
                      "width":67,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c4bc03fb9104c6dad170512fc70b19c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":283,
                          "y":5},
                        "size":{
                          "width":67,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/1_9订单详情（农旅卡）/u34.png"}},
{
                  "id":"a714214b279341d8b93c77cd5a0589d4",
                  "label":"",
                  "parentDynamicPanel":"467075897b654158bb9bb9763f929e2f",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 2.5意见反馈",
                              "target":{
                                "targetType":"page",
                                "url":"2_5意见反馈.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]},
{
          "id":"0e2fbcd82ce1435c8fdc8d49dea227eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":11},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09edbd11305d441baca91b70f4bdad1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":11},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_3订单详情（权益农旅）/u34.png"}},
{
          "id":"75b0c49fea4743f4a17b6c5325f3e789",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":0},
            "size":{
              "width":45,
              "height":41}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.0个人中心主页",
                      "target":{
                        "targetType":"page",
                        "url":"2_0个人中心主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"50dc3e3dc96a438c967f704ca2552cfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":187},
            "size":{
              "width":360,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d6984400cf6472cb8b111cdf89bddae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":187},
                "size":{
                  "width":360,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_3_3订单详情（权益农旅）/u37.png"}},
{
          "id":"7db0f2bf045c4dc7acbe556ab3ce96a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":197},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83dec296466947fc937fa624ad26f933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":197},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d68e8792041748efb7995e6f6c079ec6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":197},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ba03dbfdf934062a01e9edca258f842",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":197},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcece0acf6914996a4cd533cdec2f81f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":216},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8988b9db605042f4a59183d924898617",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":216},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b874250b87c04c59b519ce87bd3621c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":216},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"481ecdde22204027b4800ebce4102e33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":216},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"516f5abc96d3485ca830b776eed798b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":253},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad66812b987c4c65ac0651a341d381fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":253},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57a7d92064794e63bb67c3eac078d55c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":251},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abb27cf450d947debfdec45dda93c508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":251},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0af8ef4515c8409ea1240cbc865bf687",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":10,
              "y":233},
            "size":{
              "width":148,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7220ba61a8d845c9920daa04cc76693c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":10,
                  "y":233},
                "size":{
                  "width":148,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "454e6d72673740f89bbaa23cd3ceabf2":{
      "scriptId":"u0"},
    "a584db4d65b74e1eab810ab009cd5c06":{
      "scriptId":"u1"},
    "95463b67a8194076af9add9814e29a27":{
      "scriptId":"u2"},
    "40e64226a996467680082067a246e08a":{
      "scriptId":"u3"},
    "a26fa1af76ec4e0191d3aa40c37392aa":{
      "scriptId":"u4"},
    "64bf29acff1541659aba307b32fe370a":{
      "scriptId":"u5"},
    "c4448487167542c2a369b072d4da7484":{
      "scriptId":"u6"},
    "85ce997990864d4c8ae8afa3bd08c7c5":{
      "scriptId":"u7"},
    "a3f8cf7b31b8432a9bd391fcf41a3a22":{
      "scriptId":"u8"},
    "649e37f161144a1f8a21e8c64bdce8b7":{
      "scriptId":"u9"},
    "ea35a221ce334b5bb16138d714c97a7f":{
      "scriptId":"u10"},
    "cb4198d7179f41efadd169d72e12359a":{
      "scriptId":"u11"},
    "11bb1d7bd2254d2ba32c01ee9e6824d4":{
      "scriptId":"u12"},
    "77ac48c574294881bd12c2cb72f0b87e":{
      "scriptId":"u13"},
    "9a45d9ce07ae4a81b2817399f7ee983d":{
      "scriptId":"u14"},
    "ab0df11949204ef5baf76c1331b1aa7d":{
      "scriptId":"u15"},
    "ead681f3cda4427cb297dc8da1c6a4f4":{
      "scriptId":"u16"},
    "a46bf1c61da74c5f9858fd23655e6a2f":{
      "scriptId":"u17"},
    "18431b0fc5ae487e9dbcb2df4c1022b8":{
      "scriptId":"u18"},
    "f5cda885f6874e57aab5c5e9c7427767":{
      "scriptId":"u19"},
    "0d1fcd8d70b8403f88c152e961af8148":{
      "scriptId":"u20"},
    "63a818d4206b4dc98b850dadbf81a1f6":{
      "scriptId":"u21"},
    "d96b20e1108d45a4b38db247d130723d":{
      "scriptId":"u22"},
    "0d02ac80b0834138b2c4b17a91e34b69":{
      "scriptId":"u23"},
    "4ed723fd84814176b8728c57a64ef14b":{
      "scriptId":"u24"},
    "4258446068cd4c089c772db441bfeea6":{
      "scriptId":"u25"},
    "467075897b654158bb9bb9763f929e2f":{
      "scriptId":"u26"},
    "21a6835a2774464385adde8eac715737":{
      "scriptId":"u27"},
    "9387b98e395c4d97817ed01a8a372589":{
      "scriptId":"u28"},
    "545f63f1c29645ceb6fa263892416331":{
      "scriptId":"u29"},
    "7e3492d49bfd44ca943fe6a2168ae00d":{
      "scriptId":"u30"},
    "eacc6a09161e43b9a068c74272d2b584":{
      "scriptId":"u31"},
    "2c4bc03fb9104c6dad170512fc70b19c":{
      "scriptId":"u32"},
    "a714214b279341d8b93c77cd5a0589d4":{
      "scriptId":"u33"},
    "0e2fbcd82ce1435c8fdc8d49dea227eb":{
      "scriptId":"u34"},
    "09edbd11305d441baca91b70f4bdad1d":{
      "scriptId":"u35"},
    "75b0c49fea4743f4a17b6c5325f3e789":{
      "scriptId":"u36"},
    "50dc3e3dc96a438c967f704ca2552cfd":{
      "scriptId":"u37"},
    "4d6984400cf6472cb8b111cdf89bddae":{
      "scriptId":"u38"},
    "7db0f2bf045c4dc7acbe556ab3ce96a6":{
      "scriptId":"u39"},
    "83dec296466947fc937fa624ad26f933":{
      "scriptId":"u40"},
    "d68e8792041748efb7995e6f6c079ec6":{
      "scriptId":"u41"},
    "6ba03dbfdf934062a01e9edca258f842":{
      "scriptId":"u42"},
    "bcece0acf6914996a4cd533cdec2f81f":{
      "scriptId":"u43"},
    "8988b9db605042f4a59183d924898617":{
      "scriptId":"u44"},
    "b874250b87c04c59b519ce87bd3621c7":{
      "scriptId":"u45"},
    "481ecdde22204027b4800ebce4102e33":{
      "scriptId":"u46"},
    "516f5abc96d3485ca830b776eed798b5":{
      "scriptId":"u47"},
    "ad66812b987c4c65ac0651a341d381fe":{
      "scriptId":"u48"},
    "57a7d92064794e63bb67c3eac078d55c":{
      "scriptId":"u49"},
    "abb27cf450d947debfdec45dda93c508":{
      "scriptId":"u50"},
    "0af8ef4515c8409ea1240cbc865bf687":{
      "scriptId":"u51"},
    "7220ba61a8d845c9920daa04cc76693c":{
      "scriptId":"u52"}}});