$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1505815313839.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"380fcef89eda4a41837b1fe827e9462b",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f66e17d51fe84a149909231884241b86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f7ea8ab2ec4ccb8516131cc8e36583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"b84bf0c862e34e8f8c8f2ffb3dfc8d2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":55},
            "size":{
              "width":36,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81d3a40bf852436fb6a0046355959c14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":55},
                "size":{
                  "width":36,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/u111.png"}},
{
          "id":"60fb413c57634c95be5989033edac766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文新魏 Regular', '华文新魏'",
            "fontSize":"28px",
            "location":{
              "x":152,
              "y":63},
            "size":{
              "width":113,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9a956b0f7404978b57460798bb65db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文新魏 Regular', '华文新魏'",
                "fontSize":"28px",
                "location":{
                  "x":152,
                  "y":63},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1038f34adde45edac90a66d06ddd794",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":120},
            "size":{
              "width":320,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab01fcc81ff4010a4dc6f17d0fcfea5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":120},
                "size":{
                  "width":320,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f66e17d51fe84a149909231884241b86":{
      "scriptId":"u0"},
    "d5f7ea8ab2ec4ccb8516131cc8e36583":{
      "scriptId":"u1"},
    "b84bf0c862e34e8f8c8f2ffb3dfc8d2d":{
      "scriptId":"u2"},
    "81d3a40bf852436fb6a0046355959c14":{
      "scriptId":"u3"},
    "60fb413c57634c95be5989033edac766":{
      "scriptId":"u4"},
    "e9a956b0f7404978b57460798bb65db5":{
      "scriptId":"u5"},
    "c1038f34adde45edac90a66d06ddd794":{
      "scriptId":"u6"},
    "2ab01fcc81ff4010a4dc6f17d0fcfea5":{
      "scriptId":"u7"}}});